install.sh

I will be continually bit by bash forever. Fixes #169, tested on a Ubuntu VM.

Fix install script on linux

---

README.md
lib/shopify-cli/commands/create/project.rb

Fixes #171  
Adds correct URLS for Rails apps, adds note when creating project

add note about different urls

---

README.md

If the user doesn't have curl they will not be able to install the CLI

add note about curl

---

README.md
Rakefile

If you want to play around with any of the classes in this thing you can run this command and use them inside an `irb` console. I do this a lot to test things and thought I should make it easier for everyone to use.

add a development console

---

lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers/gem.rb
test/shopify-cli/helpers/gem_test.rb

I ran into this testing the rails type. We need to pass this env var to the rails server to pick up the gems we installed without sudo. Also the tests are a bit better now

Pass GEM_HOME to rails server

---

lib/shopify-cli/commands.rb
lib/shopify-cli/commands/help.rb

Quick thing to make sure the output of the help command is alphabetized.

alphabetize help output

---

lib/shopify-cli/commands/generate/page.rb

Fixes #202 
Updates UX with spinner and success in green as per design.

[Enhancement] update generate page UX

---

lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/commands/serve.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
lib/shopify-cli/tasks/tunnel.rb
test/shopify-cli/task/tunnel_test.rb

Fixes #205  
Updates as per design requirements. I also fixed the other 'tips' as part of the design audit.

[Enhancement] update UX for serve command

---

README.md

we need to whitelist http, not https for the local server that we use for authentication.

remove https from localhost

---

docs/installing-ruby.md
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/ruby.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/helpers/ruby_test.rb
vendor/lib/semantic/LICENSE
vendor/lib/semantic/semantic.rb
vendor/lib/semantic/version.rb

shopify_app [dropped support for ruby 2.3](https://github.com/Shopify/shopify_api/pull/554) so for now we'll display a message about how people can install other versions, which I've split off into a file in `docs/`.

Display message if user has ruby < 2.4

---

lib/shopify-cli/helpers/env_file.rb

adds spinner that updates when we create an env file

add spinner

---

lib/shopify-cli/tasks/clone.rb

Adds success message after we clone an app

update clone with success message

---

lib/shopify-cli/app_types.rb
lib/shopify-cli/commands/create/project.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb

Two small changes based on the UX updates in issue 217. There's a lot and I'm having issues with the CLI UI kit so I'm breaking it up into small PRs.
This moves the ngrok command later in the create chain and updates a tip. The smallest PR of all time.

UX updates to create

---

lib/shopify-cli/commands/serve.rb
lib/shopify-cli/project.rb

Fixes #206 
Moves ensure env before tunnel, and updates ux

update ux for projects

---

README.md

Addresses question raised in #255 
I've tried to make as few assumptions as possible about the operating environment, but of course there are variations in how different systems do this. I think I've captured the most common case.

Add uninstall directions

---

README.md

This PR bundles together a handful of minor content updates:
- Fix the Readme title to reflect current branding;
- Add a caution emoji to the beta note for higher visibility;
- Add a table of contents with links to the relevant notes (the readme is getting long);
- Add a request to check the code of conduct and design guidelines before starting development work.

Add ToC and other minor content fixes

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/generate/webhook.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/generate/webhook_test.rb
test/test_helpers/app_type.rb

Uses shopify_app to generate webhooks.

Rails generate webhook

---

install.sh
lib/shopify-cli/commands/deploy/heroku.rb
lib/shopify-cli/commands/generate/webhook.rb
lib/shopify-cli/context/output.rb
lib/shopify-cli/tasks/tunnel.rb
test/shopify-cli/task/tunnel_test.rb
vendor/deps/cli-ui/lib/cli/ui/glyph.rb

We're using multiple checkmarks in the success messages.
Updating all checkmarks to use the same character.

Update all checkmarks to be the same character

---

.github/DESIGN.md

Light proofread to fix some typos etc in the doc
Suggested fixes and very minor text tweaks

Light proofread of design doc

---

lib/shopify-cli/tasks/ensure_env.rb

Fixes #267 
This writes the `host` from metadata.

Fix env helper

---

README.md

updating the readme to use the new loopback url

Update whitelist url

---

lib/shopify-cli/commands/populate/customer.rb
lib/shopify-cli/commands/populate/draft_order.rb
lib/shopify-cli/commands/populate/product.rb
lib/shopify-cli/commands/populate/resource.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb

This improves the populate commands UX. We will later add a --silent flag to suppress these messages

Issue 219 populate ux

---

lib/shopify-cli/commands/populate/customer.rb
lib/shopify-cli/commands/populate/draft_order.rb
lib/shopify-cli/commands/populate/product.rb
lib/shopify-cli/commands/populate/resource.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb

As per @davekilljoy , add underlines to URLS

add underlines to urls

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/generate/webhook.rb

Updates webhooks UX to include spinner and file location
closes #271

updates webhooks ux to include spinner

---

.github/DESIGN.md

I noticed a gap in the content, that we needed to supply more information about what a good command looks like and what things you should consider when creating a good command like help and code comments.
Adding content to address the gap.

Add components of a good command to DESIGN.MD

---

lib/shopify-cli/tasks/schema.rb
test/shopify-cli/task/schema_test.rb

Fix method `exist?` to make it `exists?`

fix method name

---

lib/shopify-cli/helpers/store.rb

Reverts Shopify/shopify-app-cli#307
It broke

Revert "Delegate Store Class Methods"

---

lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/commands/generate/page.rb
lib/shopify-cli/options.rb
lib/shopify-cli/sub_command.rb
test/shopify-cli/commands/create/project_test.rb
test/shopify-cli/commands/create_test.rb
test/shopify-cli/commands/generate/page_test.rb
test/shopify-cli/options_test.rb

Fixes #216 
Gives the user a `--type` flag where they can indicate which type of app they want to make. Also updates the generate page tests. @tylerball also helped fix up our options parsing.

add the ability to bypass selection for create project

---

lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/generate.rb

Lets the user know they can pass type

adds help text for types

---

lib/shopify-cli/commands/generate/page.rb

Fixes #327 
We were getting an error for `page_types` because it doesn't exist for rails app types because you can't generate a page in a rails app right now

move rails check

---

README.md
lib/shopify-cli/commands/authenticate.rb
lib/shopify-cli/tasks.rb
lib/shopify-cli/tasks/ensure_loopback_url.rb
test/shopify-cli/task/ensure_loopback_url_test.rb

Fixes #336 
This ensures that before we authenticate, the loopback url is written to the partner dash.
Adds a task to check for loopback url in redirectwhitelisturl array

adds check for loopback url in array

---

lib/shopify-cli/commands/open.rb
lib/shopify-cli/helpers/os.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks/authenticate_identity.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
test/commands/open_test.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve_test.rb
test/shopify-cli/helpers/os_test.rb
test/shopify-cli/oauth_test.rb
test/task/authenticate_identity_test.rb
test/task/authenticate_shopify_test.rb

Fixes #337
Currently opening urls is not cross platform compatible. 
This tries for best guess opening functionality and falls back to outputting the url to the console for the user to open the url for themselves.

Better tooling around opening urls

---

lib/shopify-cli/commands/open.rb
lib/shopify-cli/helpers/os.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks/authenticate_identity.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
test/commands/open_test.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve_test.rb
test/shopify-cli/helpers/os_test.rb
test/shopify-cli/oauth_test.rb
test/task/authenticate_identity_test.rb
test/task/authenticate_shopify_test.rb

Reverts Shopify/shopify-app-cli#339

Revert "Better tooling around opening urls"

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/generate/billing.rb
lib/shopify-cli/commands/generate/webhook.rb

This fixes the broken help text on create as well as adds all the options available to users. 
It also adds green text to `webhook` and `billing` selections
After feedback from @gfscott I've updated the options help to look like this:
!--
Summary of the changes committed.
Before / after screenshots appreciated for UI changes.
-->

small ux fixes from feedback

---

lib/shopify-cli/app_types/rails.rb

Ensures we have `shopify_app` at least `11.3.0` for Rails 6 compatibility.
Fixes #177

update shopify_app version

---

lib/shopify-cli/tasks/clone.rb
test/shopify-cli/task/clone_test.rb

Fixes #347  
Aborts on any failure from git, and checks for existing directory in clone.

adds check for existing directory and aborts on git clone

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/commands/authenticate.rb
lib/shopify-cli/commands/deploy/heroku.rb
lib/shopify-cli/commands/generate.rb
lib/shopify-cli/commands/generate/billing.rb
lib/shopify-cli/commands/generate/page.rb
lib/shopify-cli/commands/load_dev.rb
lib/shopify-cli/forms/create_app.rb
lib/shopify-cli/helpers/partners_api.rb
lib/shopify-cli/project.rb
lib/shopify-cli/tasks/create_api_client.rb
lib/shopify-cli/tasks/js_deps.rb
lib/shopify-cli/update.rb
test/shopify-cli/helpers/partners_api_test.rb
test/shopify-cli/task/create_api_client_test.rb

Just tiding up how errors are presented

Error states

---

lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/forms/create_app.rb
test/shopify-cli/forms/create_app_test.rb

Tiny changes to make create match mocks

update ux for create

---

lib/shopify-cli/help_resolver.rb
lib/shopify_cli.rb
test/shopify-cli/help_resolver_test.rb

Adds a top-level `--help/-h` flag so that a user can view output of help command with this syntax.

Top level help

---

lib/shopify-cli/commands/authenticate.rb

I spoke to @davekilljoy about our two different auth scenarios and he updated the prompts to be more verbose.

upate prompts for auth

---

lib/graphql/all_orgs_with_apps.graphql
lib/graphql/find_organization.graphql
lib/shopify-cli/commands.rb
lib/shopify-cli/commands/connect.rb
lib/shopify-cli/helpers/organizations.rb
lib/shopify-cli/project.rb
test/shopify-cli/commands/connect_test.rb
test/shopify-cli/helpers/organizations_test.rb

Fixes #33 
Adds the ability to connect a project to an app. I'm putting this up now while I write tests just in case there's something I missed. Also it will not say app_name in the end.

Create connect command

---

lib/shopify-cli/command.rb
lib/shopify-cli/commands/help.rb
lib/shopify-cli/commands/populate/resource.rb
lib/shopify-cli/context/output.rb
lib/shopify-cli/options.rb
lib/shopify-cli/sub_command.rb
test/shopify-cli/commands/populate/resource_test.rb
test/shopify-cli/options_test.rb

This PR does a few things:
- outputs help to `$PAGER` or `less` if terminal is smaller than help output.
- fixes the help output of `populate <resource> -h`
- changes `<command> -h` to show extended help

Help fixes

---

README.md

Replaces hardcoded url mention with `open` command.

update open instructions to use Open

---

lib/shopify-cli/forms/create_app.rb
test/shopify-cli/forms/create_app_test.rb

Update copy in create command

---

README.md

Fixes #385 
Adds a note for users to view their generated page.

add info about routing

---

shopify.fish

We were missing the fish shell hook file in this project.
Fixes #404

Fish support

---

lib/shopify-cli/commands/generate.rb

Related to #409
I am pretty sure that the error is mundane but the error message is not formatted correctly so there is no way to debug it.
Formatting the error message

Fixing generate errors

---

README.md
lib/shopify-cli/commands/create/project.rb

The way apps in development are installed [has changed](https://www.shopify.ca/partners/blog/shopify-public-apps), updating the messaging in create to notify users they need to install the app via their Partner Dashboard after running serve.

update create messaging for Public Apps launch

---

lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/generate/webhook.rb
test/shopify-cli/commands/generate/webhook_test.rb

fixes #424 
This is pretty basic but guards against typing a fake webhook topic.

check webhook topic against array and fix file location

---

lib/shopify-cli/app_types/rails.rb
test/shopify-cli/app_types/rails_test.rb

Reverts Shopify/shopify-app-cli#445

Revert "remove spring from rails generation"

---

lib/project_types/node/commands/create.rb
test/project_types/node/commands/create_test.rb

fix npm/node checks

---

lib/shopify-cli/oauth.rb

Fixes #484 
This takes out the URI.decode_www_form call because it seems to be unreliable. I am still calling URI. decode_www_form_component so we are still decoding elements, I am just splitting the elements myself.
All functionality stays the same so the tests do not need to change.

Little change to Oauth request parsing

---

install.sh

The new Shopify create command doesn't look the same anymore so this updates the post-install notice for the cli
simply changes that banner.

Update install notice

---

README.md
docs/development.md

I started capturing some documentation for how and why the CLI works pulled from various other docs to include in the repo/github.io site but didn't get around to finishing it. Could be a good Friday win to finish these off.

WIP development docs

---

.gitignore
lib/shopify_cli.rb
test/shopify-cli/task/ensure_env_test.rb

3 small updates:
1. Adding `.git/*` to `.gitignore` mostly because VSCode will search through all the old history when looking for matching text. It's super annoying and we don't need to be committing anything in `.git` anyway.
2. Adding names/comments to `shopify_cli.rb` just to make it easier for devs to find these objects, since they are just references to other objects. It's hard when first learning this codebase to know where they are defined and what they do.
3. Fixing a flakey test, we updated `Tunnel` to no longer have a `call` function, so these tests (`ensure_env_test.rb`) fail every other time for me.

Small updates

---

README.md
docs/index.md

closes #533 
Our current documentation relies on old infrastructure and implies things exist, that have never existed so I am trimming away the fat. I am also pointing the users to check the command line help to discover more commands currently while we sort out a documentation strategy that is not confusing.
Deleting a lot of docs and replacing them with few

Readme trim

---

lib/project_types/node/commands/deploy/heroku.rb
lib/project_types/rails/commands/deploy/heroku.rb
lib/shopify-cli/git.rb
lib/shopify-cli/process_supervision.rb
lib/shopify-cli/tunnel.rb
test/shopify-cli/git_test.rb
test/shopify-cli/tunnel_test.rb

We need to backfill rdocs so that we can populate our contributor documentation
*Also* I made some code changes either to make things consistent or to hide from documentation generation.
- Documented `ShopifyCli::ProcessSupervision` and hide `unlink` because it did not need to be public.
- Document `ShopifyCli::Tunnel`
- Document `ShopifyCli::Git`
- Change `ShopifyCli::Git.init` to class level for consistency with the rest of the class
- Change `ShopifyCli::Git.branches` to be class level for consistency

Adding docs

---

lib/docgen/index_template.md.erb
lib/docgen/markdown.rb

The current doc generation generates bad filenames
fixes that.

Fix bad doc generation

---

docs/_layouts/default.html
docs/app/node/commands/index.md
docs/app/node/index.md
docs/app/rails/commands/index.md
docs/app/rails/index.md
docs/core/index.md
docs/css/docs.css
docs/getting-started/index.md
docs/index.md

Replaces #553
This PR covers a bunch of style and copy changes aimed at making our user-facing docs more comprehensive and consistent.

User-facing documentation updates

---

.gitignore

This allows one to use IntelliJ-based editors for the project without having to worry about accidentally committing the project configuration folder.
Just added the .idea folder to .gitignore.

Add idea folder to gitignore

---

.travis.yml
Rakefile

Set default Rake task

---

lib/project_types/rails/commands/create.rb

Fixes #572  
To apply best practices in Rails projects by not adding .env to Git.
Appending .env to .gitignore in the newly generated Rails project.

Adding .env to new rails apps

---

lib/project_types/script/layers/application/project_dependencies.rb
lib/project_types/script/messages/messages.rb

This corresponds to [this issue](https://github.com/Shopify/script-service/issues/1165).
The purpose is to simplify the dependency checking and installation UX.
Annette has seen these changes and made a note on the issue. 
**Before:**
**After:**
When some dependencies need to be installed.
When no dependencies need to be installed.
When no dependencies need to be installed (deploy command version).

Simplify Dependency Installation UI

---

lib/project_types/script/config/extension_points.yml

Changes made to the EPs should be used for newly created scripts.
Updating the EP versions for discount, unit-limit-per-order and payment-filter.

Updated EP versions for script creation

---

packaging/debian/control.base
packaging/homebrew/shopify-cli.base.rb
packaging/rpm/shopify-cli.spec.base

One of the big advantages of adding package manager support for the CLI is that we get to dictate what kinds of external dependencies we need without the user having to manually install them. This PR kicks off that process by adding git as the first dependency needed for the CLI packages.
Simply adds `git` as a dependency to all (`deb`, `rpm`, `homebrew`) CLI packages.

Add git as a dependency to all packages

---

lib/shopify-cli/version.rb

We have decided that the release version for the new CLI deliverables will be 0.9.0 so we have some wiggle room to fix issues before declaring it v1.0-worthy.
Simply updates the version number.

Set version to the release value: 0.9.0

---

RELEASING.md

`RELEASING.md` was not displaying correctly.
- Corrected indentations in `RELEASING.md` and added blank lines for readability.

Fix formatting of RELEASING.md

---

CHANGELOG.md
lib/shopify-cli/version.rb

Releasing latest changes to the CLI as version 0.9.1

Release v0.9.1

---

.github/CODEOWNERS

As discussed on slack the other day!

Add scripts as codeowners of script project type

---

CHANGELOG.md
lib/shopify-cli/version.rb

To keep the feature branch up to date with master branch
Merging in latest pull requests from master branch into feature branch

Packaging for release v0.9.2

---

docs/_config.yml
docs/_data/nav.yml
docs/getting-started/index.md
docs/getting-started/install/index.md
docs/getting-started/migrate/index.md
docs/getting-started/uninstall/index.md
docs/getting-started/upgrade/index.md
docs/index.md

Preliminary prep for overhauling docs for our post-package world. 
Still a work in progress!

Installation and upgrade docs changes for packages

---

CHANGELOG.md
lib/shopify-cli/version.rb

Internal release to test rebase, prior to launch
Pulling in changes to master since last rebase

Release 0.9.3

---

CHANGELOG.md
lib/shopify-cli/version.rb

Releasing initial installer-based version of the CLI.

Packaging for release v1.0.0

---

docs/getting-started/install/index.md
docs/getting-started/migrate/index.md

Some issues raised by users highlighted some additional information is needed in install and migrate docs.
Updating install and migrate docs to highlight that `shopify_api` may need to be updated and to emphasize restarting their terminal.

Add known nuances to documents

---

lib/project_types/node/messages/messages.rb
lib/project_types/rails/messages/messages.rb

Outcome of [discussion](https://github.com/Shopify/shopify-app-cli/pull/747#issuecomment-659466276) in #747 about how we describe the act of changing directories.

“Change into” > “Change directories to”

---

lib/project_types/script/commands/create.rb
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/script_project.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/test_helpers/fake_script_project.rb

Since we no longer change directories for the user, we need to update our output messages so that it is more clear. 
- Updates the output when creating a script to more accurately fit with the new flow.
- Followed the pattern of other projects

[Scripts] update create script output

---

lib/project_types/script/config/extension_points.yml

Not much more than that really, just adding support for a new EP.

[Scripts v2] Add Shipping Filter EP

---

CHANGELOG.md
lib/shopify-cli/version.rb

This PR releases the latest changes and updates, including fixing the `Schema.get_shop` call which was failing some instances of `populate products`.

Packaging for release v1.0.3

---

CHANGELOG.md
lib/shopify-cli/version.rb

This fixes a bug reported in the Partner Slack on the `connect` command on accounts with multiple organizations.

Packaging for release v1.0.4

---

lib/project_types/script/config/extension_points.yml

Updated dependency to newer EPs

[scripts] latest & greatest EP versions

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release quickfix for opt-in metrics

Release 1.0.5

---

lib/project_types/script/config/extension_points.yml

Bump EP packages to reflect the changes made in here https://github.com/Shopify/extension-points/pull/133

Bump EP packages*

---

lib/shopify-cli/process_supervision.rb

As part of the changes to support Windows, we removed the `fork` call for supervised processes, since Windows only supports `spawn`-ing them. However, that has a side effect of killing both processes if the command is interrupted - for instance when `shopify serve` is interrupted the ngrok tunnel would go down along with it with `spawn`.
These changes restore the original behaviour of forking the supervised process so it is not tied to the command. In the example, ngrok stays up even if the command drops.
Restoring the original code that `fork`-ed the supervised process for UNIX-based systems.

Fork supervised processes on UNIX

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release 1.1.0 (Windows 10 support)

Packaging for release v1.1.0

---

docs/getting-started/index.md
docs/getting-started/install/index.md
docs/getting-started/uninstall/index.md
docs/getting-started/upgrade/index.md

Added references to Windows 10 to install/upgrade/uninstall documentation.
- Restructured install doc around systems first, then installation methods.
- Updated upgrade/uninstall docs to include references to Windows 10.
- Updated requirements section for Windows 10 on getting started landing page.

Added Windows 10 to install/upgrade/uninstall

---

docs/getting-started/install/index.md

Incorrect links in install page needed to be fixed

Fixed links in install doc

---

lib/project_types/script/messages/messages.rb

When refactoring other parts of the code it looks like we forgot to remove old content.
Removes every unused message for scripts.

Remove old and unused content in scripts messages

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release of v1.1.2 for various minor bug fixes
- Check for dir before creating rails projects
- Remove Ctrl-T from serve and always print URLs
- Catch entire git stderr when cloning
- Add message to user if new version available

Packaging for release v1.1.2

---

lib/project_types/extension/cli.rb
lib/project_types/extension/features/argo_config.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/types/checkout_post_purchase.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project.rb
test/project_types/extension/features/argo_config_test.rb
test/project_types/extension/models/types/checkout_post_purchase_test.rb

fixes https://github.com/Shopify/cross-sell-app/issues/180 
Context and non-code discussions for this PR can be found in this issue.

read and push post purchase config

---

lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb

Fixes https://github.com/Shopify/script-service/issues/1770

WIP:Scripts-UX Content correction (error message strings for push command)

---

lib/shopify-cli/commands/config.rb
test/shopify-cli/commands/config_test.rb

Wrong variable in place, caught by @tanema !
Changing the variable in the message from a boolean value to the feature name.

Fix wrong variable name

---

docs/core/index.md

Follow up of #889
Adding to the github pages documentation
~~([not sure how to view changes locally, heres the markdown preview](https://user-images.githubusercontent.com/30154753/94828672-b5ed1e80-03d7-11eb-9dcc-b59f38bea3f0.png))~~

Add config analytics documentation

---

CHANGELOG.md
lib/shopify-cli/version.rb

Packaging for release v1.3.0

---

CHANGELOG.md
lib/shopify-cli/version.rb

Packaging for release v1.3.1

---

lib/shopify-cli/core/entry_point.rb

Skip version check when running tests

---

lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb

Closes https://github.com/Shopify/script-service/issues/2117
Update AssemblyScript to v0.14.0
Checked that everyting works by creating a script and running the tests

chore: Update AssemblyScript to v0.14.0

---

lib/project_types/node/commands/create.rb
lib/project_types/rails/commands/create.rb

Fixes #880 
Partners URL no longer hardcoded, introduces extra function to detect if user is using local partners and use the appropriate link.

Conditional partners url

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release v1.4.0 of the CLI, with improved debugging for errors in Partners API requests.

Packaging for release v1.4.0

---

test/project_types/script/commands/create_test.rb

[tests] Fix use of FakeFS

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release v1.4.1 of the CLI, with improved and simplified testing.

Packaging for release v1.4.1

---

lib/shopify-cli/project.rb
test/minitest_ext.rb

This appears to resolve a failure that we frequently see in the tests:
https://travis-ci.com/github/Shopify/shopify-app-cli/jobs/399942541
Fixes #914

Fix bad config caching in tests

---

lib/shopify-cli/project.rb

As suggested by @paulomarg in #947

Simplify `force_reload` behaviour

---

test/minitest_ext.rb

https://github.com/Shopify/shopify-app-cli/pull/517#discussion_r515342873

Remove unused test helper method

---

test/shopify-cli/tasks/select_org_and_shop_test.rb

Rather than stubbing at the HTTP level, we can stub at the boundary of `ShopifyCli::PartnersAPI::Organizations`.
This allows for a more concise and readable test with less incidental detail as it does not need to be concerned with the underlying JSON data structure.
The real method `fetch` and `fetch_all` methods are already covered by tests in `partners_api/organizations_test.rb`.

Simplify stubbing for `select_org_and_shop_test.rb`

---

.github/CONTRIBUTING.md

[docs] Add note about `SHOPIFY_APP_CLI_LOCAL_PARTNERS`

---

.github/workflows/release.yml
RELEASING.md

Update the RELEASE instructions for when the workflow is triggered.

Update release instructions

---

lib/shopify-cli/shopifolk.rb
test/shopify-cli/shopifolk_test.rb

Extracted out of #906 to unblock @mllemango's work on Monorail logging.

Add `act_as_shopify_organization`

---

test/project_types/node/commands/create_test.rb

I'm preparing to add a new test, but found a lot of repeated setup in the existing tests.

[tests] Extract some common setup code for node create command test

---

lib/project_types/theme/cli.rb
lib/shopify-cli/api.rb
lib/shopify-cli/http_request.rb
test/project_types/theme/commands/pull_test.rb
test/project_types/theme/forms/create_test.rb
test/project_types/theme/forms/pull_test.rb
test/shopify-cli/api_test.rb
test/shopify-cli/http_request_test.rb

* Rebase broke some stuff that needs to be fixed before I can continue
* Fixing that stuff (HTTP request + tests, split `creator` into `title` and `creator`, Rubocop offenses)

Fix branch after rebase

---

test/shopify-cli/tasks/update_dashboard_urls_test.rb

Fix faulty test for UpdateDashboardUrls

---

.github/PULL_REQUEST_TEMPLATE.md

See https://github.com/Shopify/shopify-app-cli/pull/993#discussion_r531233302

Clarification for pull request template

---

lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb

Ensure that build artifacts are scoped under `build/`
Ensure that the generated web assembly binary is placed under `./build`

fix: Fix web assembly build output

---

CHANGELOG.md
lib/shopify-cli/version.rb

This also includes #1003 but I didn't mention it in the changelog since it's an internal-only beta feature.

Packaging for release v1.5.0

---

test/test_helper.rb

Use color in minitest output

---

.github/PULL_REQUEST_TEMPLATE.md

Add reminder about cross-platform to pull request template

---

lib/shopify-cli/messages/messages.rb
lib/shopify-cli/tunnel.rb

Fixes #1036, fixes #1023 
Adding a final check to see if ngrok is being installed properly. Otherwise throws a more helpful error message.

Add validation for ngrok during installation

---

lib/shopify-cli/commands/system.rb
lib/shopify-cli/context.rb
lib/shopify-cli/tunnel.rb

Follow up for https://github.com/Shopify/shopify-app-cli/pull/1038
Putting file extension logic into a helper method

Move file extension into helper method

---

lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb

Closes https://github.com/Shopify/script-service/issues/2438
🎩 
- Create a script
- Run tests
- Deploy

chore: Update AS to v16

---

lib/project_types/script/config/extension_points.yml

Updates the toolchain dependency for each extension point

chore: Bump toolchain version to v4

---

lib/shopify-cli/partners_api.rb

Fix typo in code comment

---

lib/project_types/script/cli.rb
lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/domain/extension_point.rb
lib/project_types/script/layers/infrastructure/project_creator.rb
lib/project_types/script/layers/infrastructure/rust_project_creator.rb
lib/project_types/script/layers/infrastructure/rust_task_runner.rb
lib/project_types/script/layers/infrastructure/task_runner.rb
test/project_types/script/layers/infrastructure/rust_project_creator_test.rb

Closes https://github.com/Shopify/script-service/issues/2454
Important things to note:
- This PR uses sparse checkout to fetch the default payment filter script located here https://github.com/Shopify/scripts-apis-rs/pull/3.
- This PR is _only_ concerned about scaffolding the script, and that's why the `RustTaskRunner` is empty. Running the build task and installing the dependencies will be tackled in https://github.com/Shopify/script-service/issues/2455
To 🎩 
- Create a new script
- Select `payment_filter` as the api type
- `cd <your-script-name>`
- In your script's directory you should have the following files: `Cargo.toml, src/lib.rs`

[scripts] Scaffold Rust project

---

lib/project_types/script/layers/infrastructure/rust_project_creator.rb
lib/project_types/script/layers/infrastructure/rust_task_runner.rb
test/project_types/script/layers/infrastructure/rust_project_creator_test.rb
test/project_types/script/layers/infrastructure/rust_task_runner_test.rb

Closes https://github.com/Shopify/script-service/issues/2455
- Builds a rust script
- Ensures that the generated artifacts are named after the script name
- Reads the binary and pushes it to script service
`push` the first time will probably take a long time, given that it will trigger Rust's cargo build process which by nature is slow. Any subsequent time that you run push, it should be considerably faster as it will only re-compile the dependencies that have changed.

[scripts] Deploy rust generated binaries

---

lib/shopify-cli/partners_api.rb

Just spotted after merging #1055. 
Fixes #0000

Only send employee scope if choosing to act for Shopify org

---

CHANGELOG.md
lib/shopify-cli/version.rb

Packaging for release v1.6.0

---

lib/shopify-cli/commands/config.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/shopifolk.rb
test/shopify-cli/commands/config_test.rb
test/shopify-cli/shopifolk_test.rb

Remove `shopifolk-beta` flag, so this feature is available to all employees.

Remove shopifolk-beta flag

---

CHANGELOG.md
lib/shopify-cli/version.rb

Packaging for release v1.7.0

---

CHANGELOG.md
lib/shopify-cli/version.rb

Packaging for release v1.7.1

---

test/project_types/extension/commands/extension_command_test.rb
test/project_types/extension/commands/register_test.rb

[Issue 117](https://github.com/Shopify/shopify-app-cli/issues/1177)
This is part of a bigger task to refactor test code for easy readability

Extension test refactor

---

test/project_types/extension/commands/push_test.rb
test/project_types/extension/extension_test_helpers.rb

[Issue 117](https://github.com/Shopify/shopify-app-cli/issues/1177)
This is part of a bigger task to refactor test code for easy readability

Refactoring - organize extension test helper and modify tests

---

lib/project_types/extension/extension_project.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/extension_project_test.rb
test/project_types/extension/extension_test_helpers.rb

https://github.com/Shopify/shopify-app-cli/issues/1177
This is part of a bigger task to refactor test code for easy readability

Refactor extension project and serve test

---

lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/tasks/ensure_env_test.rb

Corresponding CLI changes of https://github.com/Shopify/partners/pull/33495

[scripts] filter public apps before continue

---

lib/project_types/script/messages/messages.rb
lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/tasks/ensure_env_test.rb

To make it more clear which app/org a dev is using while 
When autoselecting a prompt (when there is only one option), print the selection.

Update script env selection messages

---

CHANGELOG.md
lib/shopify-cli/version.rb

Part of Release v1.13.0
* Update the CHANGELOG
* Update version number 1.12.0 -> 1.13.0

Release v1.13.0

---

.github/PULL_REQUEST_TEMPLATE.md

There was a spelling mistake on the pr template
Fix a spelling mistake in this pr template.

docs: fix spelling on pr template

---

CHANGELOG.md
lib/shopify-cli/version.rb

Release version 1.13.1
* Bump version
* Changelog was updated in previous PR here https://github.com/Shopify/shopify-app-cli/pull/1272
* Adding 1 more entry to changelog that is user-facing (scripts error fix)
~- [ ] I've left the version number as is (we'll handle incrementing this when releasing).~

Packaging for release v1.13.1

---

CHANGELOG.md
lib/shopify-cli/version.rb

Bumps a new release that adds support for script.json file in script projects and fixes some scripts bugs.

Packaging for release v1.14.0

---

CHANGELOG.md
lib/project_types/theme/cli.rb
lib/project_types/theme/commands/init.rb
lib/project_types/theme/messages/messages.rb
test/project_types/theme/commands/init_test.rb

`theme init` yo!
Fixes #0000 
Reverts commit e4e6047e64fb942448a3684ff0c10e251d45c495, where it was removed.

Add `theme init` command

---

CHANGELOG.md
lib/shopify-cli/theme/file.rb
lib/shopify-cli/theme/syncer.rb

Fixes #1315
Write in binary mode when the asset is returned as a base64 encoded attachment.
Top hatted w/ images.

Fix `theme pull` error when pulling images

---

CHANGELOG.md
lib/project_types/extension/messages/messages.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/messages/messages.rb
lib/project_types/theme/messages/messages.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/packager.rb
lib/shopify-cli/theme/dev_server.rb
lib/shopify-cli/theme/syncer.rb
lib/shopify-cli/tunnel.rb

Fixes #1194
Changes output messages using `...` to use `…` instead.
Captures changes made in PR #1209 that weren't merged due to changes in overall codebase (due to `v2` of CLI)
Thank you to @sharvy for the original PR contribution.

Recapture fixes from PR 1209 to fix issue 1194

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

Release 2.0.2
See [CHANGELOG.md](https://github.com/Shopify/shopify-cli/blob/47ee6d274771e4a0bf8d2edfa36619b85ffa1a8a/CHANGELOG.md#version-202) for fixes

Packaging for release v2.0.2

---

CHANGELOG.md
Gemfile.lock
shopify-cli.gemspec

Theme Check 1.1.0 was released.
Fixes https://github.com/Shopify/theme-check/issues/339
Bump the version in gemspec.

Bump Theme Check version to 1.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

Release 2.1.0
See [CHANGELOG.md](https://github.com/Shopify/shopify-cli/blob/3c74693dab42d070e559b90feb1cf1b0fc8d1f93/CHANGELOG.md#version-210) for fixes

Packaging for release v2.1.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

Packaging for release 2.2.0
* Bump version
* Add changelog entry

Packaging for release 2.2.0

---

.gitignore
lib/project_types/node/commands/create.rb
lib/project_types/rails/commands/create.rb
lib/shopify-cli/constants.rb
lib/shopify-cli/environment.rb
lib/shopify-cli/identity_auth.rb
lib/shopify-cli/partners_api.rb
lib/shopify_cli.rb
test/shopify-cli/environment_test.rb
test/shopify-cli/identity_auth_test.rb

While debugging some code, I realized there were some hardcoded values and duplications across the codebase.
I created two modules:
- `ShopifyCli::Environment` with accessors to get information from the environment.
- `ShopifyCli::Constants` with constants that are shared across the codebase.

[Tecdebt] Extract constants and environment-related accessors to a module

---

.github/workflows/shopify.yml

I noticed there's some room for improvement in our GitHub Actions workflow so I decided to tackle that.
- Added the os to the `matrix:` attribute with the goal of having more OSs in the future.
- Rename the workflow file to `shopify.yml` and the name to `Shopify`.
- Rename the job to `test` and the name to `Test with Ruby ${{ matrix.version }} on ${{ matrix.os }}` to be representative of what it does.
Note the GitHub commit checks now include the OS in which the jobs are executed:

Improve the GitHub Actions workflow

---

lib/project_types/script/layers/infrastructure/script_service.rb

This is an initial refactor to make it easier to do further refactoring in the ScriptService class. The goal is to get rid of `MakeRequest` and move `UploadScript` out. These two proxy classes represented a bit of a barrier to this, so they needed to be refactored in order to move the proxy related code out of `MakeRequest`.
Instead of using the query method on the two API based subclasses statically, I've instead made them instance based in order to create a common interface between them. This allows us to swap them out instead of having to have `MakeRequest` perform this distinction by wrapping the calls to either.

Refactored PartnersProxyAPI and ScriptServiceAPI (now PartnersProxyBypassAPI) in ScriptService

---

lib/project_types/script/cli.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/infrastructure/api_clients/partners_proxy_api_client.rb
lib/project_types/script/layers/infrastructure/api_clients/script_service_api_client.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/layers/infrastructure/service_locator.rb
lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/infrastructure/api_clients/partner_proxy_api_client_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/layers/infrastructure/script_uploader_test.rb

These tests were left out of date after refactoring work (concluding with https://github.com/Shopify/shopify-cli/pull/1499). Everything was covered still, it's just that they could be cleaned up.
Cleans up tests related to `ScriptService`, `ScriptUploader` and `PushScript`. We were mocking out responses for the partner specific calls, like responses and payloads, which is no longer necessary.

Updating scripts related tests

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm creating a new release off-schedule to include the new PHP app. This is exceptional because the team already has all the communications planned, but in the future, we'll require teams to stick to our release cadence.

Release v2.5.0

---

lib/project_types/script/cli.rb
lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/domain/extension_point.rb
lib/project_types/script/layers/infrastructure/languages/project_creator.rb
lib/project_types/script/layers/infrastructure/languages/task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_project_creator.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
test/project_types/script/layers/infrastructure/languages/typescript_project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb

Renames `javascript` to `typescript`

refactor: Rename to TypeScript

---

lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/application/project_dependencies.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/application/project_dependencies_test.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb
test/project_types/script/ui/error_handler_test.rb

Reverts Shopify/shopify-cli#1454

Revert "[Scripts] Add dependency check for `npm` and `node` before `task_runner` initiated "

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the CLI, 2.6.0.

Packaging for release v2.6.0

---

lib/project_types/script/errors.rb
lib/project_types/script/layers/infrastructure/api_clients/partners_proxy_api_client.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/api_clients/partners_proxy_api_client_test.rb
test/project_types/script/ui/error_handler_test.rb

Kate is going through content and it appears that we have a lot of code that is no longer used. 
* Removes all dead error classes and messages.
* Removes logic that depends on dead Partner's code https://github.com/Shopify/partners/pull/36378.

Remove dead scripts code

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

Packaging for release v2.6.6

---

lib/project_types/script/config/extension_points.yml

See https://github.com/Shopify/script-service/issues/3870
Update the package name of the TypeScript checkout library.
Prerequisites: 
- Set yourself up to use Scripts (instructions [here](https://shopify.dev/apps/checkout/scripts/setup))
- Enable the `scripts_beta_languages` feature in the CLI (used [here](https://github.com/Shopify/shopify-cli/blob/e89cb4c018e40d84227f937000cec63a93d6a8e2/lib/project_types/script/layers/application/extension_points.rb#L31))
Steps:
1. Create a new script from your app by running `shopify script create --branch=ap/checkout-api-library-name-shuffle` (the `--branch` flag tells the CLI to bootstrap from that branch of the [scripts-apis-examples](https://github.com/Shopify/scripts-apis-examples) repo, which should not be merged until this change is merged and …

[Scripts] Update package name for TS checkout scripts

---

lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb

Fixes https://github.com/Shopify/script-service/issues/3616
Moves the filesystem operations to be the responsibility of the `Infrastructure::ScriptProjectRepository` class.
Run `shopify script create`

Remove filesystem operations from Application::CreateScript

---

CHANGELOG.md
lib/shopify_cli/commands/login.rb
lib/shopify_cli/messages/messages.rb
test/shopify-cli/commands/login_test.rb

Reverts Shopify/shopify-cli#1873

Revert "Fix partners ability to login to external shops"

---

.github/ISSUE_TEMPLATE/bug_report.yaml
lib/shopify_cli/github/issue_url_generator.rb
test/shopify-cli/github/issue_url_generator_test.rb

We're working on a better issue template, here are some improvements alongside pre-filling what we can automatically.
Makes the form a bit better, you can see [before](https://github.com/Shopify/shopify-cli/blob/b5bee776b82bd9e56c0edc794f18dbda5dc917e4/.github/ISSUE_TEMPLATE/bug_report.yaml) and [after](https://github.com/Shopify/shopify-cli/blob/d9a0d9649fa849a5e9ae716e669fa2007cfa828d/.github/ISSUE_TEMPLATE/bug_report.yaml).
Noteworthy changes:
* Less text
* Checklist instead of instructions
* Better placeholder text
* Prefilling environment information
N/A
All N/A

Improve Bug Issue Template

---

.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/feature.yaml

We recently introduced our bug template, so now that we're constricting the formatting more severely, we need to have templates for other issue types.
Adding new templates for features and enhancements, loosely based on https://github.com/Shopify/shopify-app-php/issues/new/choose
Look at them?
All N/A

Feature issue templates

---

dev.yml

This will come in handy for the scripts team to run only
script-related tests.
N/A

Add `dev test:script` command

---

lib/project_types/script/loaders/project.rb
lib/project_types/script/messages/messages.rb

[Content audit](https://docs.google.com/document/d/1Kg0AGIVUiJvErxq3dsRY5VPoExHb9h3NT4OP_ghvdaI/edit#) for the error messages was done in the Fall, but it doesn't seem that the updates were made to the file. This PR is an attempt to rectify that and to correct some of the new errors that have been added since.
Updating the error message strings 
Relying on development to help in this stage.

Scripts: updating Script error messages to conform to best practices

---

CHANGELOG.md
lib/project_types/theme/commands/init.rb
lib/shopify_cli/commands/app/create/node.rb
lib/shopify_cli/commands/app/create/php.rb
lib/shopify_cli/commands/app/create/rails.rb
lib/shopify_cli/commands/app/deploy.rb
lib/shopify_cli/git.rb
lib/shopify_cli/messages/messages.rb
lib/shopify_cli/tasks.rb
lib/shopify_cli/tasks/ensure_git_dependency.rb
test/shopify-cli/services/app/deploy/heroku/php_service_test.rb
test/shopify-cli/tasks/ensure_git_dependency_test.rb
test/test_helpers/heroku.rb

Bugsnag indicates we often attempt a git-requiring operation but fail because git doesn't exist in the current environment (likely Windows). This adds a preflight check to ensure we give a proper warning to the user.
Checks for git availability before attempting an operation that requires git. Warns the user if git is not installed.
Stub `Git::available?` to return `false` and see what happens.

[Feature] Enforce git dependency

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#1866](https://github.com/Shopify/shopify-cli/pull/1866): Enforce git dependency
* [#2009](https://github.com/Shopify/shopify-cli/pull/2009): Add localization support for Checkout Extensions
* [#2060](https://github.com/Shopify/shopify-cli/pull/2060): Improve CLI error messages for token-based auth (scripts)
* [#2076](https://github.com/Shopify/shopify-cli/pull/2076): Release Wasm Script Projects
* [#2051](https://github.com/Shopify/shopify-cli/pull/2051): Update `theme serve` to accept `root` argument
* [#2025](https://github.com/Shopify/shopify-cli/pull/2025): Improve `theme pull`/`push` help messages to indicate multiple `--only`/`--ignore` flags are allowed.
* [#2030](https://github.com/Shopify/shopify-cli/pull/2030): Fix Theme::Syncer handling of file deletions in `download_file!` …

Packaging for release v2.12.0

---

.github/CODEOWNERS

Add `@shopify/theme-platform-dev-experience` team to the `CODEOWNERS` file.

Add `@shopify/theme-platform-dev-experience` team to the `CODEOWNERS` file

---

shopify-cli.gemspec

*If you don't find this comment needed, feel free to close the PR.
As per @charlespwd comment here:
https://github.com/Shopify/shopify-cli/pull/2088#issuecomment-1050903320
> :D This is probably the third time someone mentions this. It was that like that and then got changed because folks here prefer to have a deterministic build.
>
> Plus, if a user upgrades the CLI, he will get a theme-check update. Whereas if we were to have ~> 1.9, that version would still be satisfied and thus not upgraded.
If there's a bit of code that might raise some questions to someone reading it, it might be good to add a comment to answer those questions.
N/A

[Docs] Add explanation for theme-check version range

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

PR for release v2.15.0 with changelog:
```
* [#2086](https://github.com/Shopify/shopify-cli/pull/2086): Improve check of dependency versions
* [#2149](https://github.com/Shopify/shopify-cli/pull/2149): Fix `ThemeAdminAPI` not to handle asset errors
* [#2146](https://github.com/Shopify/shopify-cli/pull/2146): Prevent duplicate locales for Checkout extension localization
```

Packaging for release v2.15.0

---

CHANGELOG.md

Continuation of #1934, I forgot to push the commit with changelog update before merging. 🤦‍♂️

Block directories in theme assets: Update changelog

---

Rakefile
lib/shopify_cli/release.rb

Releasing is a good amount of manual labor, let's have machines do it instead!
Makes the release process happen automatically by running a rake task.
I wouldn't recommend it... but it definitely works!
All N/A

Script release of packages

---

lib/shopify_cli/messages/messages.rb

https://shopify.dev/apps/tools/cli/core-commands#optional-parameters
Fixes #2159 
https://github.com/Shopify/shopify-cli/issues/2159
- [ x ] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [ x ] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [ x ] I've left the version number as is (we'll handle incrementing this when releasing).
- [ x ] I've included any post-release steps in the section above (if needed).

Fixed typo of login's store param

---

Rakefile
lib/shopify_cli/changelog.rb
test/shopify-cli/changelog_test.rb

Saves us the manual task of finding the PR and copypasting the title/number into the changelog.
The same thing we do already, just automatically.
Note that no GitHub auth token is required for this task, as it's operating on public data.
If we wanted, we could build this into a GitHub action, but I'm not sure it's worth it.
Note this doesn't work for external contributors yet.
I'll test on this PR (but won't push the change since it's not actually user-facing!)
N/A

Rake task for changelog updates

---

CHANGELOG.md
lib/shopify_cli/commands/login.rb
lib/shopify_cli/identity_auth.rb
lib/shopify_cli/messages/messages.rb

Inspired by https://github.com/Shopify/shopify-cli/issues/2052#issuecomment-1081690074
Not sure what we can do to make login faster, but it's definitely possible to give more feedback to the user along the way.
I imagine we could do a cleaner implementation, and the content needs @MeredithCastile's input, but first I wanted to prototype and see what y'all think.
Before:
https://user-images.githubusercontent.com/6288426/160610201-7ac96abf-9c73-420f-b4dc-881616de9dd0.mov
After:
https://user-images.githubusercontent.com/6288426/160610334-edc0ea85-15c9-47cf-be28-4b8fcfa23996.mov
`shopify login` when logged out and when logged in.

Better login experience with spinner

---

lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/specification_handlers/beacon_extension.rb
lib/project_types/extension/models/specification_handlers/beacon_extension_utils/script_config.rb
lib/project_types/extension/models/specification_handlers/beacon_extension_utils/script_config_repository.rb
lib/project_types/extension/tasks/configure_options.rb
lib/shopify_cli/messages/messages.rb
test/project_types/extension/models/development_server_requirements_test.rb
test/project_types/extension/models/specification_handlers/beacon_extension_test.rb
test/project_types/extension/models/specification_handlers/beacon_extension_utils/script_config_repository_test.rb
test/project_types/extension/models/specification_handlers/beacon_extension_utils/script_config_test.rb

ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/983
CORE: https://github.com/Shopify/shopify/pull/337128
PARTNERS: https://github.com/Shopify/partners/pull/38083
CLI-EXTENSIONS: https://github.com/Shopify/shopify-cli-extensions/pull/271 <- blocker (MERGED)
added new beacon extension

 add 'beacon extension'

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2230](https://github.com/Shopify/shopify-cli/pull/2230): Show an error without ngrok account
* [#2235](https://github.com/Shopify/shopify-cli/pull/2235): Update shopify-extensions to v0.3.0 and fix issues with template choosing and missing dependencies
* [#2226](https://github.com/Shopify/shopify-cli/pull/2226): Fix liquid file size validation to disclude locales directory

Packaging for release v2.15.4

---

lib/project_types/extension/cli.rb

Fixes too many "yaml" require removals.

Re-add CLI yaml require

---

lib/project_types/extension/models/server_config/extension.rb
lib/project_types/extension/tasks/convert_server_config.rb
lib/project_types/extension/tasks/merge_server_config.rb
test/project_types/extension/tasks/convert_server_config_test.rb

This is a bug fix. Previously, metadata was missing on `shopify extensions serve` where metadata were configured for the extension.
Fixes [#2298](https://github.com/Shopify/shopify-cli/issues/2298)
Ensures server config merges metadata properly.
Using this branch from your local shopify-cli project:
- `shopify-local extension create`,  responding to the prompts.
- Edit the resulting extension's `extension.config.yml` file, ensuring metadata are included, e.g.,
```
metafields:
- namespace: my-namespace
key: my-key
- namespace: my-namespace
key: my-key-2
```
- From the extension directory, `shopify-lcoal extension serve`, responding to the prompts. Depending on the extension type you should see something like the following image. The extension can be reached at the URL at the bottom. 
Strip …

Bug Fix: Pass extension metafields through to Ngrok extensions endpoint

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2262](https://github.com/Shopify/shopify-cli/pull/2262): Add `capabilities` permissions to checkout extensions config
* [#2292](https://github.com/Shopify/shopify-cli/pull/2292): Add support for App Bridge create/details URLs for scripts
* [#2287](https://github.com/Shopify/shopify-cli/pull/2287): Fix `Encoding::UndefinedConversionError` on `theme serve` and `theme pull`
* [#2310](https://github.com/Shopify/shopify-cli/pull/2310): Fix live-reload to be resilient and no longer raise an error when a locale file is invalid
* [#2297](https://github.com/Shopify/shopify-cli/pull/2297): Only show update message when the new version is higher
* [#2270](https://github.com/Shopify/shopify-cli/pull/2270): Use ignore filter regex in watcher class
* …

Packaging for release v2.17.0

---

lib/project_types/script/config/extension_points.yml

This PR registers the new `payment_customizations` API to extension_points.yml

Register payment_customizations API

---

lib/project_types/script/config/extension_points.yml

We decided to make the name singular

payment_customizations -> payment_customization

---

CHANGELOG.md

This PR fixes changelog entries for the following PRs:
- https://github.com/Shopify/shopify-cli/pull/2325
- https://github.com/Shopify/shopify-cli/pull/2330

Fix 'CHANGELOG.md'

---

CHANGELOG.md
lib/shopify_cli/assets/post_auth_page/index.html.erb
lib/shopify_cli/assets/post_auth_page/style.css
lib/shopify_cli/identity_auth/servlet.rb
lib/shopify_cli/messages/messages.rb
test/shopify-cli/identity_auth/servlet_test.rb

Fixes #649, fixes Shopify/shopify-cli-planning#29 
Related to Shopify/cli#45
**Before**
**After**
- `SHOPIFY_CLI_DEVELOPMENT=0 bin/shopify logout` (if necessary)
- `SHOPIFY_CLI_DEVELOPMENT=0 bin/shopify login`
- proceed through the authentication steps to view the post-authentication page

[Feature] Add Shopify branding and styling to post-authentication browser page

---

lib/project_types/extension/messages/messages.rb
lib/project_types/extension/tasks/fetch_specifications.rb
test/project_types/extension/extension_test_helpers/stubs/fetch_specifications.rb
test/project_types/extension/tasks/fetch_specifications_test.rb

Remove support for creation of Checkout UI Extensions

---

lib/project_types/extension/tasks/fetch_specifications.rb

I've introduced this temporary mock to power some of our end-to-end tests :)

Add a temporary extension mock

---

lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
test/project_types/extension/models/specification_handlers/theme_app_extension_test.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2535

Add unit tests for TAE spec handler
