Shopify/shopify-cli

lib/shopify-cli/commands/generate.rb
lib/shopify-cli/commands/generate/billing.rb
lib/shopify-cli/commands/generate/page.rb
lib/shopify-cli/commands/generate/webhook.rb
test/shopify-cli/commands/generate/webhook_test.rb

Fixes #176  
The check to ensure generate commands didn't run for Rails apps was happening too late. It was giving the user the idea that they were available, throwing errors.
Checking early in call to make sure it raises before it moves on. This is not an elegant approach, but I'm going to be working on a refactor of generate tomorrow.

moves check for rails app

---

lib/shopify-cli/commands/load_dev.rb
lib/shopify-cli/commands/load_system.rb
lib/shopify_cli.rb
test/shopify-cli/commands/load_dev_test.rb

Currently these two commands don't display any output when you run them, so it's hard to tell if they worked or not.

add messaging to load-dev and load-system

---

install.sh

Fairly certain the current wording in the install script is incorrect and definitely confused me:
It says *"shopify create app <appname>"* when it should be *"... create project <appname>"*
Fixes wording error

[Fix] Update install.sh to correctly reference `project` in create option

---

lib/shopify-cli/app_types/node.rb
test/shopify-cli/app_types/node_test.rb

If the user hasn't added their SSH public key to github they're met with a `fatal: Could not read from remote repository.`, like in #184. If we use https it should just work.

use https clone for node app

---

lib/shopify-cli/tasks/schema.rb
test/shopify-cli/task/schema_test.rb

Tim and I noticed the populate command was returning a big JSON.parse error. Turns out it was storing the schema as a ruby Hash, not JSON and we didn't have a test for this.

fix schema dumping/parsing

---

test/shopify-cli/commands/create/project_test.rb

I only have a local non-functional version of node installed so this
test was failing because my system did not have node installed which is
probably not what we want.
stubs the check deps call since the build call is also stubbed

Fix for create project test.

---

test/commands/open_test.rb
test/fixtures/app_types/rails/.env
test/fixtures/project/.env
test/fixtures/project/.shopify-cli.yml
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/deploy_test.rb
test/shopify-cli/commands/generate/billing_test.rb
test/shopify-cli/commands/generate/page_test.rb
test/shopify-cli/commands/generate/webhook_test.rb
test/shopify-cli/commands/generate_test.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/commands/populate/resource_test.rb
test/shopify-cli/commands/populate_test.rb
test/shopify-cli/commands/serve_test.rb
test/shopify-cli/helpers/api_test.rb
test/shopify-cli/helpers/env_file_test.rb
test/shopify-cli/task/schema_test.rb
test/task/authenticate_shopify_test.rb
test/test_helper.rb
test/test_helpers.rb
test/test_helpers/app_type.rb
test/test_helpers/project.rb

Currently we test commands and tasks that depend on being run in a project context with a lot of stubbing and mocking. I've instead created a `Project` TestHelper that you can include in a test class and it will provide what's needed for this. 
Closes #190

Cleanup how we test in a Project context

---

docs/development.md
lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/generate/billing.rb
lib/shopify-cli/commands/generate/page.rb
lib/shopify-cli/commands/generate/webhook.rb
lib/shopify-cli/commands/open.rb
lib/shopify-cli/commands/populate/resource.rb
lib/shopify-cli/commands/serve.rb
lib/shopify-cli/context.rb
lib/shopify-cli/helpers/api.rb

This PRs attempts to begin a clearer delineation between Context and Project. A lot of stuff was accessing Project via the `ctx.project` convenience method, which I've removed. Instead everything should access it the same way, via `Project.current`. I also started a development.md file for documenting some of this thinking.

make Project access consistent

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers/access_token.rb
lib/shopify-cli/helpers/env_file.rb
lib/shopify-cli/project.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
lib/shopify-cli/tasks/schema.rb
test/shopify-cli/helpers/env_file_test.rb

Right now EnvFile takes a bunch of unnecessary arguments: it asks for `app_type`, but we can just use `Project.current` to get that, and `write` takes a filename although we only have stacks that read from `.env` files.
Prerequisite for #156

Simplify EnvFile's interface

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers/env_file.rb
lib/shopify-cli/helpers/gem.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/helpers/env_file_test.rb

Fixes #198 
Fixes #191 
I made a mistake in #195 in [node_test.rb](https://github.com/Shopify/shopify-app-cli/pull/195/files#diff-f1428f8b5ee35d21756214f9e8457f74) where I included the `project_context` method in the setup for all tests including tests for the `build` method. These tests should _not_ have a project context since one doesn't exist during project creation. Because of this my changes in #197 passed these tests even though they fail in real usage.
I'm temporarily passing in the template to the `EnvFile.write` method instead of relying on `Project.current`. This will be solved for good in an upcoming PR for #156

Fix EnvFile write during project create

---

README.md

We haven't provided information to the user about installing their app. This is causing confusion when the shopOrigin prop is returned undefined, or they cannot access app bridge features. 
Let me know if this is the right place to put this, or if the wording should be changed.

add info about installation

---

lib/shopify-cli/app_types/node.rb
test/shopify-cli/app_types/node_test.rb

We use an internal repository for certain packages at Shopify but this can cause conflicts with the public versions installed in the Node example app. I'm adding a message to check for this configuration and exit with an error.
Fixes #207

node: check for public shopify npm repository before installing

---

lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers/gem.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/helpers/gem_test.rb

Quick cleanup allowing the Gem.install method to accept another argument for version.

Allow Gem.install to take a version

---

lib/shopify-cli/commands/populate.rb

Fixes `populate help` pages having `generate help` content
Updating help copy to the correct examples.

Populate help fix

---

lib/shopify-cli/register.rb
lib/shopify_cli.rb
test/minitest_ext.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/deploy/heroku_test.rb
test/shopify-cli/commands/generate/billing_test.rb
test/shopify-cli/commands/generate/page_test.rb
test/shopify-cli/commands/serve_test.rb
test/shopify-cli/helpers/gem_test.rb
test/shopify-cli/smoke_test.rb
test/shopify-cli/task/clone_test.rb
test/shopify-cli/task/js_deps_test.rb
test/test_helper.rb
test/test_helpers.rb
test/test_helpers/fake_ui.rb

Fixes #189 
The tests produce a lot of unnecessary output which I find makes it hard to scan for failures and also makes them slightly slow.
Unfortunately some of the cli-ui methods write directly to the terminal via ANSI escape codes so the `capture_io` test helper can't block them. I'll possibly make some changes in the library to make these test-aware but for now I'm stubbing them out with a fake interface in the tests that use them.
Before
After
There's also a bit of cleanup of unused code and reorganization of the minitest patch class.

Clean up test output

---

lib/shopify-cli/app_types/rails.rb

Quick fix for incorrect Gemfile format in the rails app.

fix shopify_app gem version format

---

lib/shopify-cli/app_types/node.rb

The missing end quote confused me at first. This adds it to reduce future confusion.
Add a missing end singlequote

Add missing single quote for Shopify registry command

---

lib/shopify-cli/commands.rb
lib/shopify-cli/commands/authenticate.rb
lib/shopify-cli/helpers/access_token.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks.rb
lib/shopify-cli/tasks/authenticate_identity.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
lib/shopify_cli.rb
test/shopify-cli/oauth_test.rb
test/task/authenticate_identity_test.rb

There are a few services that we will need to authenticate with, so I am hoping to refactor the authentication code into something we can share between the multiple actions.
- creates `ShopifyCli::OAuth`
- added temporary auth command to allow me to test the functionally (copied from @katiedavis ) with a shop and ident subcommand
- created `ShopifyCli::Tasks::AuthenticateIdentityTest` to call authentication with identity
- Error handling/raising for different authentication errors.
- Added a response page that automatically closes itself if the request was successful. If it wasn't successful then the page stays open to display the error.

Abstracting the oauth functionality into a separate class

---

lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/pkce_token.rb
lib/shopify-cli/tasks/authenticate_identity.rb
test/task/authenticate_identity_test.rb

Need a way to persist the identity token for later usage with Partners.
I copied the patterns of the AccessToken but simpler since there is only one pkce token rather than a token per store.

Adding persistence of the token

---

lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks/authenticate_identity.rb
test/task/authenticate_identity_test.rb

This will allow us to authenticate with partners soon and then use the graphapi.
just change client id and endpoint

Changing identity authentication to use production identity

---

lib/shopify-cli/tasks/ensure_env.rb

When we created the ensure_env tasks, we forgot to add the scopes required to make requests for webhook etc.

add missing scopes

---

lib/shopify-cli/helpers/api.rb
lib/shopify-cli/tasks/schema.rb
test/fixtures/api/mutation.json
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/commands/populate/resource_test.rb
test/shopify-cli/helpers/api_test.rb
test/shopify-cli/task/schema_test.rb

I need this to be able to use it for the admin API and the Partners API
- refactored the API to take a URI argument to point it at with a default to the latest admin api.
- refactored the API to have a smaller public interface. Making it easier to reason about and easier to maintain in the future.
- added an `Authorization` header with the token as well to support partners.
- fixes the constant loading issue with Net, in the API class.

Making Api Helper sharable

---

lib/shopify-cli/commands/authenticate.rb

This PR corrects the help text for the `shopify authenticate` command. Currently the help text says usage is `shopify auth`:
Which doesn't actually exist:
It also corrects the capitalization of "Admin API"

Corrects `authenticate` help text

---

.github/CONTRIBUTING.md

Link to DESIGN.MD points to the branch, not master.
Pointing the link to the master version of DESIGN.MD

Fix link to DESIGN.MD from CONTRIBUtING.MD

---

.travis.yml

Adding a before install step to travis config to install bundler. 
I had to add a version because:
```Bundler 2 introduced a new feature that will automatically switch between Bundler v1 and v2 based on the lockfile. This feature is enabled by RubyGems (only on versions 2.7.0+) which unfortunately has a bug when you run Bundler without the appropriate version installed.```

add before install

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/open.rb
test/commands/open_test.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/test_helpers/app_type.rb

Related to #267 
Makes the `open` command OS-aware and escapes the URL being opened in quotes, which I've had issues with in zsh.

Support opening URLs on Linux and escape them

---

install.sh
shopify.sh

Fixes #246 
Currently the install path for debian based systems is XDG_Runtime_dir which is temporary and it deleted on restart.
This PR unifies installation directories to $HOME/.shopify_app_cli directory. I made this decision because quite a few other applications do this as well and it seems like the safest course of action. I would love feedback if there is another location that is should be located in.
This PR is also fixing the bash shim because the string interpolation was broken while echoing the  the installation path into the bashrc.

Changeing the location of installation for debian installs

---

lib/shopify-cli/commands/tunnel.rb
lib/shopify-cli/tasks/tunnel.rb
test/fixtures/ngrok_account.log
test/shopify-cli/commands/tunnel_test.rb
test/shopify-cli/task/ensure_env_test.rb
test/shopify-cli/task/tunnel_test.rb

Adds an `auth` subcommand to the `tunnel` command to automate writing a user token to their ngrok config, which the ngrok binary we download will read from. I'm also printing the account name when the tunnel starts.

add tunnel auth command to add ngrok token

---

lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/api.rb
lib/shopify-cli/helpers/partners_api.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks/authenticate_identity.rb
test/shopify-cli/helpers/api_test.rb
test/shopify-cli/helpers/partners_api_test.rb
test/shopify-cli/oauth_test.rb
test/task/authenticate_identity_test.rb

These are all the changes that were required to get authorization working with the partners app that work is done here: https://github.com/Shopify/partners/pull/17927
There were a few things that helped this along
- an env var that called `SHOPIFY_APP_CLI_LOCAL_PARTNERS` that will allow the cli to work with local partners and identity. 
- A Helpers::PartnersAPI wrapper around the Helpers::API to allow it to handle some expected responses from partners in a consistent way.
- An exchange_token request from identity to fetch a special token for token exchange in partners.
- Changed from listening on localhost to 127.0.0.1 and then use our custom loopback domain to receive oauth redirect
- add the orgs command shopify-cli (see snippet below)
- `shopify orgs`. This should open identity to …

Changes required to get partners authentication working

---

lib/shopify-cli/commands/authenticate.rb
lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/access_token.rb
lib/shopify-cli/helpers/pkce_token.rb
lib/shopify-cli/helpers/store.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks/authenticate_identity.rb
lib/shopify-cli/tasks/authenticate_shopify.rb
test/shopify-cli/helpers/store_test.rb
test/shopify-cli/oauth_test.rb
test/task/authenticate_identity_test.rb
test/task/authenticate_shopify_test.rb
test/test_helpers/app_type.rb

fixes #17359
The Oauth flow, especially for identity, is not quite fully featured yet. There are many mechanisms that we are no using and so we are forcing the user to log in again when it is not required. 
- exchange tokens have 2 hour expiry
- we get a refresh token from identity
- Once we have that, we can keep refreshing our access_token as long as the user has not logged out of identity
This means we should VERY rarely have to open the browser again after the initial authentication but I need to implement this refresh token behaviour.
I am re-writing the Oauth mechanism to do a few things
- Use a storage system to control storing tokens within the flow. This is because I needed first party access to token stores to check for existence of tokens. The reason being point 2
- Implement a …

Backoff Oauth Flow

---

lib/shopify-cli/command.rb
lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/commands/populate.rb
lib/shopify-cli/commands/populate/resource.rb
lib/shopify-cli/options.rb
lib/shopify-cli/sub_command.rb
lib/shopify_cli.rb
test/shopify-cli/commands/create_test.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/commands/populate/resource_test.rb
test/shopify-cli/commands/populate_test.rb
test/shopify-cli/executor_test.rb
test/shopify-cli/options_test.rb

We want to add more switches (like `--verbose`) to this tool. Right now we have only added them to the `populate` command which does all the parsing within that command. In order to do this well, I also needed to come up with a more robust structure for organizing subcommands.
This PR implements switch parsing at the Command level so that commands only need to call an `options` classmethod, which gives them an [OptionParser](https://docs.ruby-lang.org/en/2.1.0/OptionParser.html) instance to define options with.
It also introduces a `subcommand` classmethod which takes the path to a file containing a subclass of `ShopifyCli::SubCommand` for adding a subcommand to a Command without having to parse it manually and execute it conditionally.
TODO

Implement command line switch parsing and a subcommand structure

---

lib/shopify-cli/command.rb
lib/shopify-cli/options.rb
lib/shopify-cli/sub_command.rb
lib/shopify_cli.rb
test/shopify-cli/executor_test.rb
test/shopify-cli/options_test.rb

Redo of #290 but without touching the create and populate commands. Still working on some better ways to test that implementation but want to unblock @katiedavis on using this pattern.

Redo "Implement command line switch parsing and a subcommand structure"

---

lib/shopify-cli/commands/open.rb
lib/shopify-cli/commands/serve.rb
lib/shopify-cli/context/system.rb
test/commands/open_test.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve_test.rb

Fixes #295 
The Open command wasn't being called properly from `serve` and this was not tested. Now it is.

Fix open behaviour during serve command

---

lib/shopify-cli/helpers/api.rb

At some point Shopify stopped accepting the `Authentication` header, returning a `[API] Service is not valid for authentication` error. We should just be using `X-Shopify-Access-Token` anyway.

remove Authentication header from api requests

---

lib/shopify-cli/commands/populate/resource.rb
lib/shopify-cli/helpers/api.rb
lib/shopify-cli/helpers/partners_api.rb
test/fixtures/api/mutation.json
test/fixtures/populate/customer.graphql
test/fixtures/populate/draft_order.graphql
test/fixtures/populate/product.graphql
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/helpers/api_test.rb
test/shopify-cli/helpers/partners_api_test.rb

Since the mutation was the exact same as the query call except that it is wrapped in `mutation {}` and that wrapping was not allowing us to name mutations I thought it would be just simpler to have a single call for all graphql calls. This way we can pass in any mutation or query and we have full power of the queries. Also to be able to fully instrument the calls we will need to name the queries.
- remove `mutation` from Helpers::Api
- Accept `**variables` into partners API so that variables can be passed in, in-line

Simplify graphql query interface

---

lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/commands/populate.rb
lib/shopify-cli/commands/populate/resource.rb
lib/shopify-cli/sub_command.rb
test/shopify-cli/commands/create/project_test.rb
test/shopify-cli/commands/create_test.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/commands/populate/resource_test.rb
test/shopify-cli/commands/populate_test.rb

Converts Create and Populate commands to use the `subcommand` helper method. I've :tophat:ed but could use a double check.

Convert subcommands to new structure

---

lib/shopify-cli/helpers/store.rb

Last week these methods were broken and it lead me to look closer into how this is implemented and I found a lesser known function of the stdlib that allows me to remove all of that extra code.
Remove class methods that just delegate to the instance by importing forwardable and using SingleForwardable.

Delegate Store Class Methods

---

lib/shopify-cli/helpers/store.rb
lib/shopify-cli/tasks/schema.rb
test/shopify-cli/task/schema_test.rb

The schema task was broken so populate is broken
putting store delegates back in and fixing schema

fixing store use in schema

---

lib/shopify-cli/commands/populate.rb
lib/shopify-cli/commands/populate/resource.rb

Adds a `--silent` flag to populate. Gives the user the ability to see the output of populated customers/products etc or silence it. It also adds a missing success message and uses a spinner for silent because it hangs for a second.

adds silent flag and updates ux

---

docs/installing-ruby.md

Previously the ruby-install commands in the docs were incorrect and would print
`!!! Unknown ruby: 2.4` in console.
This PR updates docs with correct commands
Also bumps version recommended to install to 2.5.1, aligns with ruby version defined in dev.yml

Fixed Ruby installation docs

---

lib/shopify-cli/commands/generate/page.rb
test/shopify-cli/commands/generate/page_test.rb

WHY are these changes introduced?
When we generate a page with the --type flag we should also check to make sure it's a valid type and throw error if it isn't.

check page type

---

README.md

In issue #323 Tim noticed this path is listed wrong.

Update path for authentication

---

README.md

This reverts commit aa3552e80912d03d8ca91cd0fd65d8703ccb2306.
The `install` route is /login
the callback route still has auth

Revert "Update path for authentication (#325)"

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
test/fixtures/app_types/node/.env
test/fixtures/app_types/rails/.env

In #323   Tim pointed out the [Rails gem is expecting](https://github.com/Shopify/shopify_app/blob/55c607d27d9c1395d4e1d1003965882772e0f2a6/lib/generators/shopify_app/install/templates/shopify_app.rb) `SHOPIFY_API_SECRET` and we have it listed as `SHOPIFY_API_SECRET_KEY`. I wasn't going to change it across both apps to match, but then I figured it should be as consistent as possible. I didn't want to update the gem because people use that without the CLI.
The node app has changes that need to be reviewed [here](https://github.com/Shopify/shopify-app-node/pull/52)

update api_secret to match gem

---

lib/graphql/find_organization.graphql
lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/forms.rb
lib/shopify-cli/forms/create_app.rb
lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/env_file.rb
lib/shopify-cli/helpers/organizations.rb
lib/shopify-cli/oauth.rb
lib/shopify-cli/tasks.rb
lib/shopify-cli/tasks/create_api_client.rb
lib/shopify_cli.rb
test/shopify-cli/commands/create/project_test.rb
test/shopify-cli/forms/create_app_test.rb
test/shopify-cli/forms_test.rb
test/shopify-cli/helpers/organizations_test.rb
test/shopify-cli/oauth_test.rb
test/shopify-cli/task/create_api_client_test.rb
test/test_helpers.rb
test/test_helpers/partners.rb

Now that we have the integration with Partners Dashboard ready, this adds the ability to create and app on the Partners Dashboard and automatically get apiKey and secret then automatically adding it to the env file. It will also add a dev shop to the config as well if it is available so that the app can be installed easier.
This should set up an app ready to install and use right away.
SOOOOOO Much
- Extract input of the create command into a presenter/decorator to format our user inputs
- Add ApiClientCreate task to generate an app in the partners dash and call it from create
- Add writing of the env file to the create command with all of the collected information.

Create Project generate app config automatically and add to env 

---

lib/shopify-cli/forms.rb
lib/shopify-cli/forms/create_app.rb
test/shopify-cli/forms/create_app_test.rb
test/shopify-cli/forms_test.rb

Fixes #344 
Create project crashes if the user has never signed into partners dash before and has access to no orgs
It adds a case to handle this but also a way to abort forms and output how they are invalid in a critical way.

Fixing a no org situation for project create

---

test/shopify-cli/commands/serve_test.rb

I've been having trouble while working on another PR that touches serve, because I keeping this error `sh: a: command not found` on a test.
It turns out this test was missing the expectation that system would be called so it was throwing it on master.

adds expectation of system call

---

lib/shopify-cli/tasks/update_whitelist_url.rb
test/shopify-cli/task/update_whitelist_url_test.rb

This allows the admin to point to the running app on serve 
Pass in the applicationUrl to the update whitelist mutation

Update App Urls with ngrok hosts on Serve

---

lib/shopify-cli/commands/generate/webhook.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/create_test.rb
test/shopify-cli/commands/deploy/heroku_test.rb
test/shopify-cli/commands/generate/billing_test.rb
test/shopify-cli/commands/generate/webhook_test.rb
test/shopify-cli/commands/populate/customer_test.rb
test/shopify-cli/commands/populate/draft_order_test.rb
test/shopify-cli/commands/tunnel_test.rb

Follows up #355 by updating all remaining tests referencing `Command.call` to use `run_cmd`. Bonus found an issue with `generate webhook` not finding an argument correctly.

Update .call methods to run_cmd in tests

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/tasks/js_deps.rb
test/fixtures/app_types/node/package.json
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/task/js_deps_test.rb

`npm install` is unnecessarily noisy.
Fixes #264 
Parses the package.json file and shows a number of dependencies the tool is installing.

Silence npm install and output number of deps

---

docs/getting-started.md
lib/shopify-cli/app_types.rb
lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/create/project.rb
lib/shopify-cli/forms/create_app.rb
lib/shopify-cli/tasks/js_deps.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/create/project_test.rb
test/shopify-cli/forms/create_app_test.rb
test/shopify-cli/task/js_deps_test.rb

After review, we realized we could make the app create flow a lot easier and more transparent.
- Output automatically selected Organization
- Output automatically selected Dev Store
- Added a getting-started page to be displayed as the application url incase `shopify serve` did not update the app url.
- Changed the app url in project create to be a link to that getting started url so that the user does not have to enter it.
- Added green highlights to the Org and Shop so that they stick out and any links that may need to be followed stick out as well.

Updating create flow

---

lib/shopify-cli/command.rb
lib/shopify-cli/options.rb
lib/shopify-cli/sub_command.rb
test/shopify-cli/commands/command_test.rb

Adds a help flag to the default OptionsParser, which means it gets added to every command and subcommand.
Fixes #321

add global help flags

---

lib/shopify-cli/commands/populate/customer.rb
lib/shopify-cli/commands/populate/draft_order.rb
lib/shopify-cli/commands/populate/product.rb
lib/shopify-cli/commands/populate/resource.rb
test/shopify-cli/commands/populate/product_test.rb
test/shopify-cli/commands/populate/resource_test.rb

Default values for resources were being calculated at command call time and not per mutation, which means that products get generated with the same title by default and not randomized. This updates the structure of the `defaults` method to return a hash that gets merged into the mutation data during each iteration.
Fixes #372

Fix resource titles in populate

---

lib/shopify-cli/commands/authenticate.rb

This adds a prompt to ensure the user wants to auth against admin as per our figma mocks.
I did not add this ability to identity, I wasn't sure if we wanted to surface that as part of the command?
If we do, I can update this task to be a bit more simple and add information to help about this.

add ux details to auth task

---

lib/shopify-cli/tasks/tunnel.rb
test/shopify-cli/commands/tunnel_test.rb
test/shopify-cli/task/tunnel_test.rb

If you are switching back and forth between `load-dev` and `load-system` the CLI can't keep track of the PID for ngrok easily, so it will throw a long traceback about multiple tunnels being run. I don't want to run something like `killall` behind the user's back so we'll just show a clean error instead.

Abort cleanly when ngrok tunnel cannot be stopped

---

lib/shopify-cli/help_resolver.rb
test/shopify-cli/help_resolver_test.rb

Displaying help output when no command is given.

fix help output when no command is given

---

lib/shopify-cli/forms/create_app.rb
test/shopify-cli/forms/create_app_test.rb

Fixes #388  
The space in this regex was causing capitalized titles to print with spaces in them.

removes space in gsub

---

lib/shopify-cli/helpers/partners_api.rb
test/shopify-cli/helpers/partners_api_test.rb

I noticed in an issue output there were brackets around string that didn't need them.

remove brackets

---

lib/shopify-cli/forms/create_app.rb
test/shopify-cli/forms/create_app_test.rb

There was an issue with screaming case titles https://github.com/Shopify/shopify-app-cli/issues/388
This appropriately fixes this issue so that the fallback title will work with SCREAM_CASE, camelCase, snake_case and kebab-case
I actually stole most of the implementation here from rails active support's `to_underscore` so it should work in most cases because it has been used for quite some time.

Fixing fallback app title replacements

---

lib/shopify-cli/log.rb
lib/shopify-cli/monorail.rb

The code we're using to `tail` wasn't protected against seeking to a negative index. Also we should be truncating the events log file after sending them successfully.
Fixes #411

truncate logfile after sending events

---

lib/shopify-cli/log.rb
lib/shopify-cli/monorail.rb

We received a report that the array of events returned from `Log` is nil. This PR protects against that in a few ways.

fix send_events when log is empty

---

docs/installing-ruby.md

It's too easy to overlook that opening a new terminal window (or reloading the environment) is necessary to activate the new ruby.
Improve documentation.
Just a tiny documentation change.

Emphasize opening a new terminal window

---

lib/shopify-cli/tasks/update_dashboard_urls.rb
test/shopify-cli/task/update_dashboard_urls_test.rb

Fixes #422  
We should just prompt if we have a new application url instead of only prompting if it's not a ngrok url. This also fixes an issue with the callback url being written twice.

fixes logic in prompt for updating application url

---

lib/shopify-cli/commands/serve.rb
lib/shopify-cli/helpers/env_file.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve_test.rb

We were using `dotenv` for getting ENV variables in the generated rails app, but we can pass these in via the `system()` call, removing the need for `dotenv`.
Related to https://github.com/Shopify/shopify_app/pull/837

pass Project.env to serve commands

---

lib/shopify-cli/app_types/node.rb
lib/shopify-cli/commands/serve.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve_test.rb

Rails uses the HOST env var to set which IP address to bind the server to, which caused a SocketError in rails apps with my previous change #421 
For now, it deletes the HOST var from the env hash before passing it to the serve command. I don't think it's even necessary that we store this value in the env file, we should just pull it from the Tunnel task directly.

exclude HOST env var from being passed to serve command

---

lib/shopify-cli/log.rb

`[]` returns `nil` when the requested range doesn't exist.  `last(n)` returns as much as possible.

Make tail work for small logs

---

lib/graphql/all_organizations.graphql
lib/graphql/all_orgs_with_apps.graphql
lib/graphql/find_organization.graphql

Fixes #434 
I am arbitrarily expanding both app and store queries so that no one hits a limit. I faintly remember the average app per org and store per org and 500 should cover *most* cases. I am worried about exapanding the query any further
Just updating our queries that query apps and stores to request the first 500

Expanding query page sizes so that limits are not reached

---

lib/shopify-cli/app_type_command.rb
lib/shopify-cli/app_types.rb
lib/shopify-cli/app_types/node.rb
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/commands/serve.rb
lib/shopify-cli/commands/serve/node.rb
lib/shopify-cli/commands/serve/rails.rb
lib/shopify-cli/context/output.rb
lib/shopify-cli/project.rb
lib/shopify_cli.rb
test/shopify-cli/app_type_command_test.rb
test/shopify-cli/app_types/node_test.rb
test/shopify-cli/app_types/rails_test.rb
test/shopify-cli/commands/serve/node_serve_test.rb
test/shopify-cli/commands/serve/rails_serve_test.rb
test/shopify-cli/commands/serve_test.rb
test/test_helpers/app_type.rb

As discussed in https://github.com/Shopify/temp-shopify-app-cli/issues/8, it's difficult for us to define commands that vary a lot by AppType. Currently we have strings defined for commands in each AppType class, that a given command will reach for conditionally based on the project type, which is fine for small differences but upcoming projects could introduce the need for wildly different behaviour.
Implements a new `AppTypeCommand` that has a `type` classmethod, allowing you to define classes whose `call` methods will be executed by the command dynamically. I've moved `Serve` to this new format in this PR as an example and will move other commands to this structure if we agree on the approach.

implement an AppType-aware command

---

test/shopify-cli/context_test.rb
test/test_helpers/fake_fs.rb

This change only affects tests. My team is working on the private temp fork of this repo for our work, and we use [FakeFS](https://github.com/fakefs/fakefs) in a lot of our tests. Currently in master, FakeFS is only used in a single test and the `setup` method defined in the FakeFS helper is overridden. Any test using `TestHelper::FakeFS` without overriding `setup` would actually fail, because many tests inherit from `MiniTest::Test` where the [setup method](https://github.com/Shopify/shopify-app-cli/blob/bb37b966c78ba19b25e4ae8829fca65cb41253e8/test/minitest_ext.rb#L13) relies on a physical file.
These changes fix that problem so FakeFS can be used in any test file without causing failures or requiring overriding `setup`. 
- In _test/test_helpers/fake_fs.rb_ I move the `super` call to …

Refactor TestHelpers::FakeFS to work in any test file when included

---

lib/shopify-cli/commands/serve/node.rb
lib/shopify-cli/commands/serve/rails.rb
test/shopify-cli/commands/serve/node_serve_test.rb
test/shopify-cli/commands/serve/rails_serve_test.rb

I was finding, often that my API key was not being loaded while calling shopify serve even though it was all available. 
I changed the system call to use the direct system class instead of calling the context system command since all it was doing was adding in another env key which causes confusion. 
After this change, my serve calls are no longer failing.

Directly call system for serve

---

lib/shopify-cli/commands/populate.rb
lib/shopify-cli/commands/populate/resource.rb

Fixes #415
Moves the ensure_env task because it runs before we have the chance to check if you're in a shopify project.

checks for shopify project in resource

---

lib/shopify-cli/app_types/rails.rb
test/shopify-cli/app_types/rails_test.rb

This PR removes [Spring](https://github.com/rails/spring) from our rails generation. 
Recently users have reported issues [running their servers](https://github.com/rails/spring/issues/610) with Spring, and it's not required for our apps. When required, users can add Spring to their projects.

remove spring from rails generation

---

lib/shopify-cli/app_types/rails.rb
test/shopify-cli/app_types/rails_test.rb

This PR removes [Spring](https://github.com/rails/spring) from our rails generation. 
Recently users have reported issues [running their servers](https://github.com/rails/spring/issues/610) with Spring, and it's not required for our apps. When required, users can add Spring to their projects.

remove spring from rails generation (again)

---

README.md
lib/shopify-cli/app_types/rails.rb
lib/shopify-cli/helpers.rb
lib/shopify-cli/helpers/node.rb

Fixes #462 
The shopify_app has a dependency of webpacker, which requires a node version of higher than 8. Users are having errors building the app if they don't have a high enough node version (and then, serving) the error messages are hard to read in the out put after failure. This adds a helper to check for a min of 10.

warns users they must use 10.0.0 min of node

---

Gemfile
Gemfile.lock
test/test_helper.rb

I like using `binding.pry` for debugging instead of `byebug`. It gives a lot of handy features that aren't necessarily available in byebug. I'd like to add it so it's available all the time.
Adding the use of `binding.pry` for debugging.

Add pry for debugging

---

docs/implementing_a_new_project_type.md
lib/project_types/rails/cli.rb
lib/shopify-cli/command.rb
lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/help.rb
lib/shopify-cli/commands/load_dev.rb
lib/shopify-cli/commands/load_system.rb
lib/shopify-cli/project_type.rb

We need a way of hiding commands and project types so that the users dont see things that will confuse them. Also so that people developing project types don't need to worry about half rolled out states.
- Adds `hidden_command` to commands to hide them from help but still makes it callable
- Adds `hidden_project_type` to project types to hide the project types from the create command.
shopify load commands are hidden:
we currently don't really have any setup to test help output so I am not sure I know how to test this currently.

Hidden commands and project types

---

shopify.fish

Fixes an issue where reloading using the `shopify load-dev` command did not work while using the `fish` shell.
The problem was that the message sent from `lib/finalize.rb` [here](https://github.com/Shopify/shopify-app-cli/blob/master/lib/shopify-cli/finalize.rb#L40) did not have the prefix expected by `shopify.fish` [here](https://github.com/Shopify/shopify-app-cli/blob/master/shopify.fish#L75-L76). Fixing these two lines in the latter to match the correct prefix of `reload_shopify_cli_from` fixes the problem.

Fix reload command for fish shell users

---

Gemfile
Gemfile.lock
lib/shopify-cli/commands/deploy/heroku.rb
lib/shopify-cli/heroku.rb
lib/shopify_cli.rb
test/shopify-cli/commands/deploy/heroku_test.rb
test/shopify-cli/heroku_test.rb

I wanted to group all the Heroku-related methods together at the top-level so they can be used by any project type.
I also realized I previously added the wrong `pry`, I actually need `pry-byebug` so I added that as well and removed `pry`.
Moving the code out of `lib/shopify-cli/commands/deploy/heroku.rb` and move it into `lib/shopify-cli/heroku.rb`. 
And then in the future/next PR break out `lib/shopify-cli/commands/deploy/heroku.rb`
into `lib/project_types/node/commands/deploy/heroku.rb` and `lib/project_types/rails/commands/deploy/heroku.rb`

Add top-level Heroku class

---

lib/shopify-cli/helpers/partners_api.rb
test/shopify-cli/helpers/partners_api_test.rb

Currently  we just call `ctx.puts(msg)` so execution continues and the method returns nil. This is a problem because for most authenticated requests, we check the response hash like [this](https://github.com/Shopify/shopify-app-cli/blob/7cdb93fea746edbe84b7e485cd2d64c941fffc5e/lib/shopify-cli/helpers/organizations.rb#L23). This then causes an undefined method exception, so the actual error message gets hidden behind a stack trace so its hard to figure out what actually went wrong.
Aborts rather than printing the error and letting execution continue.

Abort when rescuing 404 from parters in authenticated_req

---

lib/shopify-cli/context/output.rb
lib/shopify-cli/git.rb
test/shopify-cli/git_test.rb

Tidy up some outstanding items from `consistent-context-usage` branch
- Removing unnecessary calls to `CLI::UI.fmt()` in `Context` (`output.rb`) - the underlying methods already call that `fmt()` method.
- `ShopifyCli::Git`: using `abort()`, `system()`, `done()` from `Context` instead of direct calls
- Changing associated test cases for `ShopifyCli::Git` as a result of previous point.

Tidy up context usage

---

lib/project_types/node/cli.rb
lib/project_types/node/commands/tunnel.rb
lib/project_types/rails/cli.rb
lib/project_types/rails/commands/tunnel.rb
lib/shopify-cli/commands.rb
test/project_types/node/commands/tunnel_test.rb
test/project_types/rails/commands/tunnel_test.rb

Expands on #458 and #470 by adding **Tunnel** command to **Create**, **Serve**, **Open** (already converted), aligning with `project_type` structure for extensibility.
- adding `Tunnel` to `cli.rb` files under `{node,rails}` directories
- copying and modifying `tunnel.rb` to `{node,rails}/commands` directories
- copying and modifying `tunnel_test.rb` to `{nodes,rails}` test directories
- deleting `tunnel.rb` and `tunnel_test.rb` from respective directories under previous system

Convert tunnel command to Project Type-based system

---

lib/project_types/node/commands/generate.rb
lib/project_types/rails/commands/generate.rb
lib/shopify-cli/commands/help.rb
lib/shopify-cli/project_type.rb
test/project_types/node/commands/generate/webhook_test.rb
test/project_types/node/commands/generate_test.rb
test/project_types/rails/commands/generate_test.rb

I noticed that the `extended_help` in `Node::Commands::Generate` was missing, and I added tests for `extended_help` in both Node/Rails. 
I also added `ShopifyCli::ROOT` to `ShopifyCli::ProjectType.load_type`, as I think we're talking about the CLI Root, and just to make sure we namespace stuff so we don't get into any weird `root` issues.

Update Generate and ProjectType

---

README.md
docs/index.md
lib/shopify-cli/project.rb

Our create command was different before v2
Changes all references of `shopify create project` to `shopify create`
This is a small change, but a bigger change will eventually need to be made because all of our documentation seems like rails/node project are the only function of the Shopify command so we need to document how they work in a project context.

Update create command docs

---

lib/docgen/index_template.md.erb
lib/docgen/markdown.rb

We need a way of having a index for the classes that we are documenting so that we can keep them separate from our more Tutorial-like content.
Adds a template and generation of a list of all the classes that we document.
I am going to hold off on merging and running this until I merge #536 and #537

Added a doc index for all the generated docs

---

Rakefile
lib/shopify-cli/project.rb

This adds docs to `ShopifyCli::Project` as well as hides `directory` because it does not need to be public.

Adding project documentation

---

lib/project_types/node/commands/create.rb
lib/project_types/rails/commands/create.rb
test/project_types/node/commands/create_test.rb
test/project_types/rails/commands/create_test.rb

Fixes https://github.com/Shopify/shopify-app-cli/issues/534
In the Shopify ecosystem, we refer to "app name" when we talk about apps, not "title". The --title option used when creating an app project should therefore be --name instead. I kept --title around for backwards compatibility but no longer suggest it as a valid option.

Add --name flag for create

---

lib/project_types/node/commands/deploy/heroku.rb
lib/project_types/rails/commands/deploy/heroku.rb
lib/shopify-cli/heroku.rb
test/minitest_ext.rb
test/project_types/node/commands/deploy/heroku_test.rb
test/project_types/rails/commands/deploy/heroku_test.rb
test/shopify-cli/heroku_test.rb
test/test_helpers/heroku.rb

Fixes https://github.com/Shopify/shopify-app-cli/issues/495
The `shopify deploy heroku` command fails when creating a new app because we first call `heroku create` and then call `git remote add heroku new_remote`. If you run it a second time, it succeeds because the app is already created.
As per the Heroku docs: `If you run the create command from your app’s root directory, the empty Heroku Git repository is automatically set as a remote for your local repository.` So our `remote add` call always fails because it's already being done by Heroku automatically.
I'm removing this call and tidying up some tests that used it. I needed to remove some of the `spin_group.add/wait` logic and replaced it with `@ctx.puts` as there are some weird `spin_group/Prompt` interaction issues that write over …

Remove git remote add call for heroku deploy

---

lib/shopify-cli/api.rb
lib/shopify-cli/context/system.rb
lib/shopify-cli/core/monorail.rb
test/project_types/node/commands/create_test.rb
test/shopify-cli/api_test.rb
test/shopify-cli/context_test.rb

We need less system-dependent system calls. 
Removes calls to uname and replacing them with Ruby internals that are already available `RbConfig::Config['host']`

Removing calls to uname

---

Rakefile

Currently if the tmp directory already exists that the wiki repo was cloned into, it will not get the updates that have been made before the last update.
Changes the rake task to use ruby's tmpdir functionality so that it will start with a clean slate.

Cleaner Wiki Update

---

docs/_config.yml
docs/_includes/head.html
docs/_includes/sidebar_nav.html
docs/_layouts/default.html
docs/app/node/index.md
docs/app/rails/index.md
docs/index.md

In #550, I neglected to consider that the docs site is published in a directory (`http://shopify.github.io/shopify-app-cli/`), and GitHubPages/Jekyll don't deal with that gracefully.
This PR fixes all the links in the docs.

Fix relative paths for docs

---

docs/getting-started/index.md

Follow-on to #556, removes the curl version from install requirements, it's kind of meaningless

Remove curl version

---

README.md

This removes the bulk of the documentation content from the README, and replaces it with links to the [user-facing docs](https://shopify.github.io/shopify-app-cli/) and the [contributor guide](https://github.com/Shopify/shopify-app-cli/wiki)

Remove most content from README

---

docs/_config.yml
docs/_layouts/default.html
docs/app/node/index.md
docs/app/rails/index.md
docs/index.md

Changes the table of contents on each page of the user-facing docs to optional — it can be turned off by setting `toc: false` on the front matter YAML.
I've turned it off on the 3 pages where there's no good reason to have a table of contents.

Change ToC to optional via frontmatter, but default to on

---

lib/shopify-cli/oauth.rb
lib/shopify-cli/oauth/servlet.rb
test/project_types/node/commands/create_test.rb
test/project_types/rails/commands/create_test.rb
test/shopify-cli/oauth/servlet_test.rb
test/shopify-cli/oauth_test.rb
test/shopify-cli/task/create_api_client_test.rb
test/shopify-cli/task/ensure_loopback_url_test.rb

fixes #469
fixes #432
fixes #484
Currently there are a couple of problems with our Auth
- `app-cli-loopback.shopifyapps.com` has DNS issues
- `app-cli-loopback.shopifyapps.com` is often redirected to https in firefox which our local server can't handle
- `request bodies are longer than expected`
We previously were using a domain to avoid DNS rebinding with `localhost` but I don't *think* this should be an issue with 127. Also, 127 should not be redirected to https ever. 
- Changes the redirect URL to `http://127.0.0.1:3456` from `http://app-cli-loopback.shopifyapps.com:3456`
- Changes from TScocket to use Webrick to be more stable and make webrick parse requests for us.

Make oauth more battle worthy

---

lib/shopify-cli/commands.rb
lib/shopify-cli/commands/system.rb

Adding hidden `system` command to help with debugging/troubleshooting CLI issues
Adding registration of `system` command to `lib/shopify-cli/commands.rb`
Adding implementation of `system` command, `lib/shopify-cli/commands/system.rb`
**Output of `shopify help system`**
```
% shopify help system
Print details about the development system.
Usage: shopify system [all]
all: displays more details about development system and environment
%
```

Add system command to display system/env information

---

lib/shopify-cli/commands.rb
lib/shopify-cli/project_type.rb
test/shopify-cli/project_type_test.rb

If a project type attempts to register a command of the same name as a CLI core command (e.g., `help`, `logout`, `connect`, `load-dev`, etc.), the CLI will silent replace the current command with the projects command.  Now the CLI aborts when a project type attempts to re-register a CLI core command.
- Add reference list and `core_command?` method to `ShopifyCli::Commands`
- `register_command` method in `ShopifyCli::ProjectType` (and anything inheriting from it) checks if the command is a core command and aborts if it is.

Abort when a project type attempts to register a CLI core command

---

test/shopify-cli/admin_api/populate_resource_command_test.rb

These tests periodically fail if they are run before any other rails project type test. This is because the rails project type hasn't been loaded when we try to access it. Simply loading the project type will fix it.

Fix flaky tests in populate_resource_command_test.rb

---

lib/shopify-cli/commands.rb
lib/shopify-cli/project_type.rb

`ProjectType.register_command()` uses `add()` method of `Registry` directly, instead of using `Commands.register()` that hides command registry implementation.
- Add flag to `Command.register()` to indicate a core command (default to `false`, only `true` for calls within `lib/shopify-cli/commands.rb`)
- Use `Command.register()` instead of `Command::Registry.add()` in `ProjectType.register_command()`

Hide implementation of Command::Registry from ProjectType

---

lib/shopify-cli/context.rb

Fixes #519
Currently on first installation of cli, running the `serve` command will output a stack trace while installing ngrok. This is because it tries to remove an absolute path but the context actions are meant to be relative. 
reproduce 
- `rm ~/src/github.com/Shopify/shopify-app-cli/ngrok*`
- `shopify serve`
Added functionality to make the commands relative to the root unless the paths are absolute.

Fixing ngrok installation and context file operations

---

lib/shopify-cli/core/finalize.rb
test/shopify-cli/core/finalize_test.rb
test/test_helper.rb

In https://github.com/Shopify/shopify-app-cli/pull/44 the minitest reporter was changed. The SpecReporter emits a lot of output to the terminal which can cause us to miss useful output or warnings. It also means we need to scroll back a long way to grab the seed value for a particular run, for when we need to investigate an intermittent failure.
Here's how the output looks with this change:
```
............................................Not running with shell integration. Finalizers: cd:test-app
..........................................Not running with shell integration. Finalizers: cd:test-app
.Not running with shell integration. Finalizers: cd:test-app
...Not running with shell integration. Finalizers: cd:test-app
..Not running with shell integration. Finalizers: cd:test-app …
```

Use default minitest reporter

---

lib/shopify-cli/context.rb
lib/shopify-cli/oauth.rb
test/shopify-cli/context_test.rb

Fixes https://github.com/Shopify/shopify-app-cli/issues/509
When we call the OAuth code to authenticate with either Partners or Admin, we are auto-opening a browser window if on a Mac. Users find this a bit annoying as they may have certain sessions in certain browsers and would like a bit more control over where/when to open. 
Since we're only auto-opening on a Mac, I've removed this behaviour in favour of printing out the url to open for all OS. 
There was also an ask to identify the reason for authentication, but this is difficult as there are a variety of reasons we are querying Partners/Admin GraphQL. And since these are being called from all over the codebase, it would get a bit messy to pass strings with each query to say why a particular auth was being done. Especially since if …

Print auth url instead of auto-opening

---

lib/project_types/script/config/extension_points.yml

As part of https://github.com/Shopify/scripts-sdk-as/pull/26, we need to bump the versions used in the CLI. We also need to add payment filter since that was added in the temp CLI.
**This can't be deployed until https://github.com/Shopify/extension-points/pull/49 is deployed**
Fixes https://github.com/Shopify/script-service/issues/1061
Just bumping the versions in the yml file and adding the payment filter EP.

Bump scripts SDK and EP versions

---

lib/shopify-cli/commands/help.rb
test/shopify-cli/commands/help_test.rb

Fixes #557
We're partitioning the command list into two categories, core and local. Core commands are available everywhere, local commands are only available when inside a supported app's directory, i.e. Node or Rails currerently.
Before:
After:

Show current project context for help command

---

.travis.yml

As mentioned in #595, testing on Ruby 2.3 prevents us from upgrading RuboCop.
The further we fall behind, the more warnings that will be generated.
Sets the minimum version we test against as 2.4 in Travis CI.
Ruby 2.3 was EOL in March 2019. This change doesn't prevent running the tool on Ruby 2.3, but it does mean there's a small risk that we could introduce a regression on 2.3 that isn't caught by the tests.

Drop Ruby 2.3 for CI

---

lib/graphql/shop_script_delete.graphql
lib/graphql/shop_script_update_or_create.graphql
lib/project_types/script/cli.rb
lib/project_types/script/commands/disable.rb
lib/project_types/script/commands/enable.rb
lib/project_types/script/forms/enable.rb
lib/project_types/script/forms/script_form.rb
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/deploy_script.rb
lib/project_types/script/layers/application/disable_script.rb
lib/project_types/script/layers/application/enable_script.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/commands/disable_test.rb
test/project_types/script/commands/enable_test.rb
test/project_types/script/forms/deploy_test.rb
test/project_types/script/forms/enable_test.rb
test/project_types/script/forms/script_form_test.rb
test/project_types/script/layers/application/disable_script_test.rb
test/project_types/script/layers/application/enable_script_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

These commands allow users to activate (enable) or deactivate (disable) a script on your store.
- Adds an `enable` and a `disable` script project command.
- Finishes importing Scripts code 🎉

Add enable and disable script commands

---

lib/shopify-cli/commands/help.rb
lib/shopify-cli/project.rb
test/shopify-cli/commands/help_test.rb
test/shopify-cli/project_test.rb

Fixes #591 and #598
* Extracts out the `project_name` method.
* Changes the behaviour so that the correct project name is shown, even if run from within a nested directory.

Fix handling of project name when called from inside subdirectory

---

lib/project_types/script/config/extension_points.yml

The Scripts SDK has a new `Money` type and was bumped to version 4.0.0. Related EP versions were also bumped.
Related issue: https://github.com/Shopify/script-service/issues/1170
This PR updates the package versions so that new scripts have the latest version.

Bump scripts SDK + EP versions

---

lib/project_types/rails/commands/create.rb
lib/project_types/rails/messages/messages.rb
test/minitest_ext.rb
test/project_types/rails/commands/create_test.rb

- Fixes #312 
- Adds ability to customize Rails scaffolding more efficiently, as users may not wish to use the defaults when scaffolding
- Adds flags to `rails new` command:
- `--db=DB` changes the database being used
- `--rails_opts=RAILSOPTS` takes a string of other possible flags
- Removed `--api` flag added earlier as the CLI does not currently support API-only apps
- Adds help text for new flags
- Tests new flags
_Prompting for database choice will be done in a separate PR._

Add `rails new` flags

---

lib/project_types/script/commands/create.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/commands/create_test.rb

Corresponds to [this issue](https://github.com/Shopify/script-service/issues/1187)
Replaces hardcoded EP names for `discount` and `unit_limit_per_order` in the UI messages shown to the user.
**Original:**
and
**New:**
and

Remove hardcoded EP names in CLI

---

lib/shopify-cli/core/monorail.rb
test/shopify-cli/core/monorail_test.rb

Related to #627
currently the schema was expecting the api_client_id which is internal to the partners dashboard and we were expecting to pass along the ApiKey so the was a bit of a communication break down.
Todd is currently putting in a fix for this but while he is doing that I am putting this temporary fix in place so that we can get our data. When the schema is updated I will remove this "fix" and update the schema.

A Temporary fix for monorail

---

lib/shopify-cli/tunnel.rb
test/shopify-cli/tunnel_test.rb

Some future app types or some developer configurations may require a different port to work with the `ngrok` tunnel.
Introduces an optional `port` parameter to the `start` command of `Tunnel`. If no `port` is provided it functions exactly as before and opens the tunnel on port `8081`. If a different `port` is provided that `port` will be used instead.

Refactoring Tunnel to allow configurable port

---

lib/project_types/script/config/extension_points.yml

The discount EP version was updated and the CLI needs to reflect that.
Related issue: https://github.com/Shopify/script-service/issues/1232
Bumps the discount EP and SDK versions.

Bump discount EP version

---

lib/project_types/script/layers/infrastructure/assemblyscript_dependency_manager.rb

The latest version of the discount EP relies on a newer version of as-pect. 
This PR bumps the as-pect version for new script projects. I've tested that the new version doesn't break the other existing EPs.

Bump as-pect version

---

docs/help/start-app/index.md

This PR introduces a new "start app" help page, intended to replace the existing getting-started page. This complements and precedes #636, where I will update the code that directs people to this page, but the tests in that PR won't pass until this page is live. 🙂

Adds a new help page for helping you start your app server

---

lib/shopify-cli/js_deps.rb
lib/shopify-cli/js_system.rb
lib/shopify_cli.rb
test/shopify-cli/js_deps_test.rb
test/shopify-cli/js_system_test.rb

Currently, the `yarn?` command is hidden as private inside the `JsDeps` class. It felt that we could use two reusable concepts when dealing with `project_types` that are JavaScript based.
1. Use `yarn` or `npm`?
2. Conditional calls to `npm` or `yarn` dependant on what is available.
Creates the `JsSystem` class which handles the two above cases. `JsDeps` now reuses the `JsSystem` to handle it's conditional logic of `yarn` or `npm`
```ruby
JsSystem.yarn?(context)
@system = JsSystem.new(ctx: context)
@system.yarn?
```
```ruby
JsSystem.call(context,
yarn: 'install',
npm: 'install'
)
JsSystem.call(context,
yarn: ['install', '--silent'],
npm: ['install', '--no-audit', '--no-optional', '--silent']
)
yarn_lambda = -> { CLI::Kit::System.system('yarn', 'install') }
npm_lambda = -> { …
```

Adding JsSystem for making npm and yarn calls

---

lib/project_types/rails/commands/create.rb
lib/project_types/rails/commands/deploy/heroku.rb
lib/project_types/rails/forms/create.rb
lib/project_types/rails/messages/messages.rb
lib/shopify-cli/tasks/create_api_client.rb
lib/shopify_cli.rb
test/project_types/rails/commands/create_test.rb
test/project_types/rails/commands/deploy/heroku_test.rb
test/project_types/rails/forms/create_test.rb
test/test_helpers/heroku.rb

- Fixes #513 
- Rails default is SQLite database; however, Heroku does not support deployment using SQLite
- Stack traces can be removed, as error messages are being displayed to the user already
- Proper initialization of databases is needed to use models, and eventually, to deploy
- Adds prompting for user to choose desired database
- Enforces checking for database type prior to deployment
- Asks user to change database types if SQLite is being used
- Removes stack traces from spinner errors
- Fixes migrations in database types other than SQLite  
- Adds/changes tests for prompting

Add Rails DB Prompting

---

lib/project_types/rails/cli.rb
lib/project_types/script/cli.rb
lib/shopify-cli/messages/messages.rb

There were some typos. Also, the 'Authenticated Successfully' page claims the page will auto-close but that will never happen, so I updated the copy to let the user know they could close the page themselves. I didn't want to just say 'Authenticated Successfully' in case they thought they had to leave the page open for whatever reason.

Update Auth page copy and typos

---

.gitignore
.rubocop.yml
packaging/rpm/README.md
packaging/rpm/rubygem-shopify.spec
packaging/rpm/rubygem-shopify.spec.template

This applies the same logic as PR #646 to create an empty .rpm metapackage that installs the CLI gem, so that it can be installed in the same way for RPM-using Linux distros.
This creates a .rpm package spec that doesn't contain any code itself except for the gem install / uninstall commands, and adds some documentation on how to go about generating it.
What this does **NOT** do yet is consider the actual distribution of the packages we generate.

Add basic structure for .rpm package generation

---

lib/project_types/node/messages/messages.rb
lib/project_types/rails/messages/messages.rb
lib/shopify-cli/messages/messages.rb
test/fixtures/shopify_schema.json
test/task/ensure_test_shop_test.rb

This PR updates several messages that refer to "test shops" or "development shops", which doesn't comply with our standard terminology. This updates these instances to "development stores".
(Originally reported by @jenstanicak 🙏)

Terminology change: test shop > development store

---

.gitignore
lib/project_types/script/commands/enable.rb
lib/project_types/script/config/extension_points.yml
test/project_types/script/commands/enable_test.rb

The script SDK now defines a `Configuration` object rather than a script author defining their own `Configuration` object. Since it has an explicit structure (entries) now, the default can no longer be vague.
Additional context:
- https://github.com/Shopify/script-service/issues/719
- https://github.com/Shopify/script-service/issues/1319
- Changes the default configuration value from '{}' to '{ "entries": [] }'
- Updates the EP versions to those that expect `configuration` as a paramerter

Changed default configuration value when enabling script from '{}' to '{ "entries": [] }'

---

lib/graphql/api_versions.graphql

The GraphQL command for fetching the available Admin API versions started failing with this message:
```
`fetch_api_version': undefined method `[]' for nil:NilClass
```
Upon further investigation, we noticed that the API itself started returning a failure for that query:
```
"{\"errors\":[{\"message\":\"Parse error on \\\")\\\" (RPAREN) at [1, 28]\",\"locations\":[{\"line\":1,\"column\":28}]}]}"
```
While I didn't yet figure out why this started failing, the fix is quite clear as the query syntax is apparently wrong - as per the error message and trying it out in the GraphQL website validator.
This fix simply removes the parenthesis from the `publicApiVersions` object to make it syntactically valid again.

Fixing GraphQL syntax of the public API version query

---

lib/shopify-cli/js_system.rb
test/shopify-cli/js_system_test.rb

Currently when running `which yarn` to determine if `yarn` is available the output is being presented to the user. I don't believe this is the expected result of this check.
- Updated the `which yarn` call to use `capture2` instead of `system`
- Added some tests around `yarn?` since it had been untested previously
For some testing, I commented out all of the `node` create command so it just outputs `yarn` status.

Hide which yarn ouput when checking yarn version

---

lib/project_types/script/graphql/shop_script_delete.graphql
test/project_types/script/layers/infrastructure/script_service_test.rb

We don't use configuration after disabling a script right now, so we don't need it. There was a change to the server that makes configuration a ConfigurationInput rather than a string, so this is broken right now anyway.
Removes `configuration` field from our queries.

Remove configuration field from shop_script_delete query

---

lib/shopify-cli/js_deps.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/js_deps_test.rb

The current output for `JsDeps.install` does not handle all possible error cases. In some specific cases, it actually appears to be successful when the install actually failed. 
This PR updates the `JsDeps` class to be able to handle error cases and return that result to the caller.
- `install` now outputs an error case when install fails
- `install` now returns true/false dependant on if `install` is a success or fail
⬇️ 
⬇️ 
⬇️ 
⬇️

Updating JsDeps to improve install failure handling

---

lib/project_types/node/messages/messages.rb

- Terminal text remained green after running `shopify generate billing`.
- Add missing `}}` to appropriate message in `lib/project_types/node/messages/message.rb`

Add missing brackets to message

---

lib/project_types/rails/commands/create.rb
lib/project_types/rails/messages/messages.rb
test/project_types/rails/commands/create_test.rb

The latest gem install rails requires a ruby version of at least 2.5.
- Updating the expected ruby version from 2.4 to 2.5 in `lib/project_types/rails/commands/create.rb`
- Updating the corresponding output string in `lib/project_types/rails/messages/messages.rb`
- Updating the associated test cases.

Update expectation to ruby 2.5 for `create rails`

---

lib/project_types/script/layers/application/project_dependencies.rb
test/project_types/script/layers/application/project_dependencies_test.rb

If a script is pushed successfully, the frame that checks if dependencies need to be installed has a red bottom when none are required. It should use the default frame colour (cyan) when successful.
**Before:**
**After:**

Fix red frame on successful npm check

---

lib/project_types/script/cli.rb
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/errors.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/domain_package_test.rb
test/project_types/script/layers/infrastructure/fake_push_package_repository.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

Rename `shopify deploy` for scripts to `shopify push`. There was a script-service spot that wasn't changed in the last PR.

Rename deploy to push

---

lib/shopify-cli/core/entry_point.rb
lib/shopify-cli/messages/messages.rb
shopify.fish
shopify.sh

Once the CLI is only distributed as a package, we'll no longer want developers to be able to continue using the `master` branch checkout so we put out a unified experience. Therefore, this change intends to make it clear to the user that they should go through the migration process.
It is quite disruptive to simply force them to reinstall via a package / gem, but there are significant changes in how the CLI works without the shell shims and finalizer, so while things are likely to work, we can't guarantee it either.
The idea behind this is that whenever the user goes through the process of running the shell shim, we simply let them know that the CLI is no longer working. If they try and run any commands with a pre-set shim we'll also show a similar message to really drive the point home. …

Add reinstallation warning

---

lib/shopify-cli/js_deps.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/js_deps_test.rb

After completing https://github.com/Shopify/shopify-app-cli/pull/677 I noticed the UX flow of installation between `yarn` and `npm` was not aligned. You can go to that issue to see the misalignment.
Updates the flow so JS dependency install has an aligned UX no matter which package manager is being used.
- Split out common parts of `install`
- Reuse the install path for both `yarn` and `npm`

Align yarn and npm install UX

---

lib/project_types/script/layers/infrastructure/assemblyscript_dependency_manager.rb
test/project_types/script/layers/infrastructure/assemblyscript_dependency_manager_test.rb

Fixes https://github.com/Shopify/script-service/issues/1324
The original error message was quite noisy. Instead, we check the node version before running a NPM install. This way, we can display a better error message when needed.
Check node version manually, instead of letting NPM do it.

Better error message for not supported node version

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/assemblyscript_wasm_builder.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/domain_package_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_wasm_builder_test.rb
test/project_types/script/layers/infrastructure/fake_push_package_repository.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

Fixes https://github.com/Shopify/script-service/issues/1236.
This PR removes the schema generation from the CLI. It was already made optional yesterday, so sending it was no longer necessary. It was also made optional from the toolchain too [here](https://github.com/Shopify/scripts-toolchain-as/pull/2).
:burn: schema everywhere

Scripts: remove schema generation

---

lib/shopify-cli/commands/connect.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project.rb
lib/shopify-cli/resources/env_file.rb
test/shopify-cli/commands/connect_test.rb
test/shopify-cli/resources/env_file_test.rb

The `shopify connect` command isn't doing as much as it could. It should allow you to take a project that wasn't created by the CLI and 'hook it up' so that you can perform CLI commands on it. Right now it only creates a `.env` file, and if there's no `.shopify-cli.yml` file the whole command blows up.
I have updated the `connect` command to do the following:
- the help text is now more explicit
- it will prompt you to select the type of project (currently node/rails)
- it will still give you a warning if you run this command on a project that already has a `.shopify-cli.yml`, but it will still run through the flow (as it did before). An optional Production warning will show if the app is a node/rails app.
- it only writes the `.shopify-cli.yml` if one doesn't already exist
- the flow …

Connect command update

---

test/project_types/node/commands/deploy/heroku_test.rb
test/project_types/node/forms/create_test.rb
test/project_types/rails/commands/deploy/heroku_test.rb
test/project_types/rails/forms/create_test.rb
test/project_types/script/forms/create_test.rb
test/shopify-cli/commands/create_test.rb
test/shopify-cli/context_test.rb
test/shopify-cli/tunnel_test.rb
test/task/ensure_dev_store_test.rb

Inspired by Paulo's [comment](https://github.com/Shopify/shopify-app-cli/pull/656#discussion_r437396773) I went looking to see how many of our tests were using hardcoded strings rather than the `@context.message` translations. Turns out it's a bunch!
I've updated all those tests to now use translations so they are less likely to break with content changes.

Update tests to use translations

---

lib/project_types/extension/commands/create.rb
lib/project_types/extension/messages/messages.rb
test/project_types/extension/commands/create_test.rb

Currently, our cleanup is a bit aggressive and will try to `cleanup` a directory if it exists prior to running `shopify create extension` as seen in the demo below.
This PR short circuits create immediately if the planned directory already exists.
- Add a check right after filling out the form and abort if the directory exists

Fixing an issue with extension create cleanup

---

ext/shopify-cli/extconf.rb
lib/graphql/api_versions.graphql
lib/rubygems_plugin.rb
shopify-cli.gemspec

Locking the CLI to the version/instance of `ruby` that is used to install it, which will help reduce the variability of behaviour and bug reports due to a multi-ruby-installation development environment.
Adding `ext/shopify-cli/extconf.rb` to:
- dynamically create a script file that calls the CLI ruby script with a the ruby version used during CLI installation
- dynamically create a `Makefile` (expected by RubyGems extensions) that will create a symbolic link to the location of the dynamically created script file (above) from `/usr/local/bin/shopify-cli`
Adding `lib/rubygems_plugin.rb` to:
- add a post-uninstall hook that will:
- check if the gem being uninstalled is named `shopify-cli`
- if so, delete the symbolic link `/usr/local/bin/shopify-cli` (the target of the symbolic link will …

Lock CLI to ruby instance during installation

---

lib/shopify-cli/core/monorail.rb
lib/shopify-cli/project.rb
test/shopify-cli/core/monorail_test.rb
test/shopify-cli/project_test.rb

For better metrics on what commands are run, this PR splits out the command name from the arguments. 
Resolves command name and subcommand names then puts them in a separate field from the argument in the payload to monorail.

Updating monorail to log command names separately

---

lib/project_types/extension/commands/serve.rb
test/project_types/extension/commands/serve_test.rb

The `serve` command was written before `JsSystem`. This updates it to use `JsSystem` so it no longer needs to determine it's build command type on its own. This logic is encapsulated by the `JsSystem`.
- Remove custom yarn vs npm logic from serve
- Update build to use JsSystem

Updating extension serve command to use JsSystem

---

lib/project_types/extension/commands/build.rb
test/project_types/extension/commands/build_test.rb

The `build` command was written before `JsSystem`. This updates it to use `JsSystem` so it no longer needs to determine it's build command type on its own. This logic is encapsulated by the `JsSystem`.
- Remove custom yarn vs npm logic from build
- Update build to use JsSystem

Updating extension build command to use JsSystem

---

docs/core/index.md
lib/project_types/node/forms/create.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/forms/create.rb
lib/project_types/rails/messages/messages.rb
lib/project_types/script/forms/script_form.rb
lib/project_types/script/messages/messages.rb
lib/shopify-cli/commands/connect.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project.rb
test/project_types/node/forms/create_test.rb
test/project_types/rails/forms/create_test.rb
test/project_types/script/forms/script_form_test.rb
test/shopify-cli/commands/connect_test.rb

Resolves #661 
Updates references to "organization" to say "partner organization" in all the places where we reference that concept. This aligns better with how Shopify talks about this externally, since "organization" is mainly an internal concept.
Also I changed the way we display organizations to include the name _and_ ID to add clarity in case someone has more than one organization with the same name. (This was mentioned in #639, but this PR does not solve the main issue in that ticket).

"Organization" -> "Partner organization"

---

lib/rubygems_plugin.rb

If the end user has installed another instance of the CLI gem using another ruby version, then deleting the older one will inadvertently delete the symlink (which is now pointing to the 2nd installation).
Deletes the symbolic link if and only if
- the symlink exists, AND
- it does not point to a file (i.e., it's been left hanging as a result of the uninstall, as expected)

Fix delete of symlink

---

lib/shopify-cli/messages/messages.rb
shopify.fish
shopify.sh

Since we can't say for sure how long the update process will actually take for the user, we should make no mention of it in the warning messages.
Simply removing the unneeded text from the messages.

Remove mentions of the upgrade time from the warnings

---

packaging/debian/README.md

This just fixes a wrong instruction in the Debian packaging README, since we stopped using `postinst` in favour of `preinst` to fail the package installation on `gem install` failures too.

Minor fix to debian README file

---

Rakefile

It adds `gem_tasks` to Rakefile so we can release the CLI gem to rubygems.org.

Add gem_tasks to the Rakefile

---

lib/project_types/script/layers/infrastructure/assemblyscript_dependency_manager.rb

Not sure why this was working previously, since it was working perfectly fine on my machine last week. But today this was no longer working. Instead of assuming that the semantic versionning module is loaded properly, I'm lazy loading it only when I actually need it.
Fixes the following error:
```
This command ran with ID: 98181
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
7: from /Users/maximebedard/Github/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
6: from /Users/maximebedard/Github/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
5: from /Users/maximebedard/Github/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in …
```

Fix semantic versionning not being loaded

---

Rakefile
lib/shopify-cli/packager.rb
packaging/debian/control.base
packaging/rpm/shopify-cli.spec.base

Now that the gem is properly hosted on Rubygems, our packaging processes can start installing it directly from there. A few missing dependencies arose from that test, and this PR addresses those issues.
This fixes the following issues:
- Debian package requires `sudo` for installation
- RPM package requires `make` for installation
- It also requires sudo, but yum locks the `sudo` package so that it can't be uninstalled later on. That prevents it from deleting our package too. Under the assumption that most installs should have sudo in any case, the `shopify-cli` package was not updated to depend on it.
- Instead of building the gem locally, the Homebrew process now obtains the SHA-256 hash directly from RubyGems - we can't guarantee that the gem we'd create locally would match the one …

Finalize the packager to work with remote gems

---

packaging/debian/control.base

Make is a dependency for installing the gem, and it was not being added for Debian packages, so that may have blocked installing it in some instances.
Simply adding `make` to the dependency list for debian.

Add make as a dependency for installing the CLI on debian

---

shopify-cli.gemspec

Current CLI uses functionality that requires 2.4.0 at minimum (`report_on_exception=`); `shopify create rails` requires 2.5 minimum.
Updating the `required_ruby_version` to `>= 2.5`

Update required ruby to 2.5

---

lib/shopify-cli/git.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/git_test.rb

I noticed in the `Git`.`clone` command that the entire git output was being presented to the console. I do not believe this was the original intention so this is just trying to bring it back in line with what I felt was the original goal.
- Output git clone status as a progress bar
- No longer output full git output on success
- No longer output success if clone failed

Updating clone output

---

lib/shopify-cli/api.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/api_test.rb

Fixes https://github.com/Shopify/app-extension-libs/issues/687 
A failed `shopify push` command returns the HTML for the partners error page.
The actual issue was due to GCS work in Shopify Core which has been already fixed but we need to fix the CLI handling of these errors as well.
Handle the HTML output error on CLI and show it with an appropriate error message.

Fix HTML output error on cli

---

test/shopify-cli/core/monorail_test.rb

Looks like a flaky test was introduced when adding in scripts metadata for monorail. The monorail tests will fail when a test that alters the metadata runs before the monorail tests. Resetting the metadata in the setup method will fix this.
```
Finished in 5.397916s, 114.6739 runs/s, 301.0421 assertions/s.
1) Error:
ShopifyCli::Core::MonorailTest#test_log_event_contains_schema_and_payload_values:
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST https://monorail-edge.shopifycloud.com/v1/produce with body '{"schema_id":"app_cli_command/4.0","payload":{"project_type":"fake","command":"testcommand","args":"arg argtwo","time_start":1593443442639,"time_end":1593443442639,"total_time":0,"success":true,"error_message":null,"uname":"x86_64-apple-dar …
```

Fix flaky monorail test

---

RELEASING.md

We just did our first full release of the CLI (https://github.com/Shopify/shopify-app-cli/releases/tag/v0.9.1) following the instructions of the guidelines file to the letter, and a few minor points came up that could make things easier.
Tweaks to the releasing guidelines.

Tweaks to the releasing guidelines after real run

---

packaging/debian/control.base
packaging/rpm/shopify-cli.spec.base

So that the packages match the gem requirement for Ruby 2.5.
Simply updating the required version number.

Update Ruby dependency on packages to 2.5

---

lib/project_types/script/commands/create.rb
lib/project_types/script/errors.rb
lib/project_types/script/forms/create.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/forms/create_test.rb
test/project_types/script/ui/error_handler_test.rb

Closes https://github.com/Shopify/script-service/issues/1435
We need to validate the script name when passing an invalid name as an cli option. Otherwise, other pieces of code will fail.
Runs the same validations on option provided names as prompted names.

Validate script name when passed as option

---

lib/project_types/extension/cli.rb
lib/project_types/extension/forms/register.rb
lib/project_types/extension/graphql/get_app_by_api_key.graphql
lib/project_types/extension/tasks/converters/app_converter.rb
lib/project_types/extension/tasks/get_app.rb
lib/project_types/extension/tasks/get_apps.rb
test/project_types/extension/commands/register_test.rb
test/project_types/extension/extension_test_helpers.rb
test/project_types/extension/extension_test_helpers/fake_extension_project.rb
test/project_types/extension/extension_test_helpers/stubs/get_app.rb
test/project_types/extension/extension_test_helpers/temp_project_setup.rb
test/project_types/extension/forms/register_test.rb
test/project_types/extension/tasks/converters/app_converter_test.rb
test/project_types/extension/tasks/get_app_test.rb

Currently, the CLI will fetch a Partner's entire list of apps even if a specific API Key is provided. This PR updates the `register` call of extensions to only fetch a single app if an `api_key` flag is provided.
- Add `get_app_by_api_key` GraphQL call
- Add a task `GetApp` for fetching single apps
- Update `register` to not fetch all app is an `api_key` is provided
- Create an `AppConverter` that is used by both `GetApps` and `GetApp` tasks

Fetch a single app if api_key parameter is provided

---

lib/shopify-cli/core/finalize.rb

After the initial release of the installer-based version, we ran into an issue where the very first manual update command (though not auto-updates) would trigger a warning because after pulling the new code it tried to autoload the finalizer, which was gone by that point. This PR introduces a dummy version of that class back to prevent such errors.
Adding an empty Finalize class that implements an empty `deliver!` method to prevent warnings.

Add dummy Finalize class to avoid warnings

---

lib/shopify-cli/core/entry_point.rb

Fixes #740 and #742 
After the release of v1.0.0, we received some reports of the CLI failing to run under RVM because it throws an error when trying to load FD 9 (previously used by the shell shim). The RVM raises an ArgumentError in that case which prevents commands from going forward.
This PR adds a check for that particular error so that it cleanly skips this error. I've tested (using FD 3 since I couldn't reproduce this issue with 9) that if the FD exists before we go into Ruby we don't get the error - so we can say that if we got ArgumentError the FD did not exist before Ruby ran. See below:
```
$ irb
2.7.0 :001 > File.for_fd(3)
Traceback (most recent call last):
5: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
4: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in …
```

Gracefully ignore ArgumentError in the shim check

---

lib/project_types/script/config/extension_points.yml

The new EP versions add a `scope.yml` file that the script-service will be looking for once the change is merged.
Additional context: https://github.com/Shopify/script-service/pull/1424
Just updating the EP versions to the latest.

Updating EP versions to include the new scope files

---

lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_repository.rb
lib/project_types/script/script_project.rb
lib/shopify-cli/context.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_project_creator_test.rb
test/project_types/script/layers/infrastructure/script_repository_test.rb
test/project_types/script/script_project_test.rb

Use context to access File.exist?() in script files.
I'm looking for some thoughts on the name of the new context method because I could see easy confusion between this and `context.exist?()` which would fail in these situations since `Dir.exist?()` checks for directories.

Move File.exist? to use context in scripts repos

---

lib/shopify-cli/admin_api/schema.rb
test/shopify-cli/admin_api/schema_test.rb

Fixes #754 
Adds missing shop parameter to call of AdminAPI.query within Schema.get method + updated test.

Fix missing shop parameter to AdminAPI.query() call

---

lib/project_types/theme/cli.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/tasks/ensure_themekit_installed.rb
test/project_types/theme/tasks/ensure_themekit_installed_test.rb
test/project_types/theme/test_helper.rb

- Themekit commands can't be used in CLI commands without Themekit downloaded
- Is better to check and download as part of CLI processes rather than have users do so separately themselves
- Checks if Themekit is installed
- If not, installs to cache and makes executable
- Adds task to `cli.rb` for Theme project type
- Tests for task

Task to download Themekit if not installed

---

lib/shopify-cli/core.rb

During the process of migrating the CLI to be installer-based, we dropped the `update` command since it no longer made sense. @carmelal then noticed that we failed to remove the autoload reference to the command, even though the file doesn't exist any more.
Removing the autoload reference.

Remove autoload reference to extinct update command

---

lib/shopify-cli/commands/connect.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/commands/connect_test.rb

Fixes #751
We actually didn't handle the case where a developer may want to connect an app but not have any existing API clients in the dashboard.
I have actually added the creation of an ApiClient within the create action.

Allow creating an API Client while connecting

---

lib/project_types/extension/cli.rb
lib/project_types/extension/commands/build.rb
lib/project_types/rails/cli.rb
lib/project_types/script/cli.rb
lib/shopify-cli/command.rb
lib/shopify-cli/commands.rb
lib/shopify-cli/commands/config.rb
lib/shopify-cli/commands/create.rb
lib/shopify-cli/commands/help.rb
lib/shopify-cli/commands/system.rb
lib/shopify-cli/feature.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project_type.rb
lib/shopify_cli.rb
test/project_types/extension/commands/build_test.rb
test/shopify-cli/commands/config_test.rb
test/shopify-cli/feature_test.rb

fixes #620
`shopify config feature` is a hidden command that would allow us to disable some features by default, for instance, Shopify plus features that most developers do not have access to. It has the added benefit of allowing teams to enable their hidden projects and have the CLI operate like they are no longer hidden.
This will allow for checking if a feature is enabled `ShopifyCli::Feature.enabled?(:shopify_plus)` in code paths and will also conditionally show hidden project types and hidden commands if the correct features are enabled
**Example: enabling a debug feature set and it shows the load-dev, load-system, and feature commands**

Feature sets

---

lib/project_types/script/cli.rb

This PR allows script commands to be set as visible for the preview. It uses the recent [Feature Sets](https://github.com/Shopify/shopify-app-cli/pull/632) PR.
Use `shopify config feature script --enable` to unhide the create command, and `--disable` to hide it again.
**Disabled:**
**Enabled:**

Add enable/disable visibility to Scripts Commands

---

lib/project_types/script/commands/enable.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/commands/enable_test.rb

Related issue: https://github.com/Shopify/script-service/issues/1427
Right now it's not possible to provide configuration values when enabling scripts through the CLI, so this PR aims to add that functionality.
Adds two new options to the enable command: `--config_file` and `--config_props`. Follows the precedence order set out in this doc that requires `--config_props` to override `config_file` when both are present. The format for the configuration file is JSON:
```JSON
{
"key1": "value1",
"key2": "value2"
}
```
**EDIT 2020/07/14:** 
Using YAML instead:
```YAML
key1: "value1"
key2: "value2"
```

[Feature] Add --config_file and --config_props flags for scripts enable

---

lib/shopify-cli/messages/messages.rb
lib/shopify-cli/tasks/update_dashboard_urls.rb
lib/shopify-cli/tunnel.rb
test/fixtures/ngrok.log
test/shopify-cli/task/update_dashboard_urls_test.rb
test/shopify-cli/tunnel_test.rb

Fixes #767 
- `Tunnel.start` displays when the tunnel will timeout if there's no account associated with `ngrok`
- `Tunnel.start` prints a message suggesting to sign up if there's no account associated with `ngrok`
```
% shopify tunnel start
✓ ngrok tunnel running at https://bc662f568adc.ngrok.io
⭑ This tunnel will timeout in 7 hours 8 minutes
⭑ To avoid tunnels that timeout, it is recommended to signup for a free ngrok
account at https://ngrok.com/signup. After you signup, install your
personalized authorization token using shopify tunnel auth <token>.
%
```
- `Tunnel.start` determines if a currently running tunnel has timed out, and restarts it automatically
```
% shopify tunnel start        
✗ ngrok tunnel has timed out, restarting ...
✓ ngrok tunnel running at …
```

Add messaging about tunnel timeouts, add restarts for expired tunnels (Fix issue 767)

---

lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb

Ticket: https://github.com/Shopify/script-service/issues/592
* remove `--validate` as AS enables validation by default https://github.com/AssemblyScript/assemblyscript/pull/1258
* add `--use Date=` to get `Date` usage caught at AS compile time.
Before: no compilation errors with `Date.now()` usage
After:

Update script build option

---

lib/shopify-cli/partners_api/organizations.rb
test/shopify-cli/partners_api/organizations_test.rb

Fixes #779
fixes #732
Currently if there is an issue fetching organization data from the partners API, we throw an error before we are able to provide the user with helpful output. This PR just makes these API calls more safe by using `dig` instead of direct hash access so it is safer and will return nil if the data does not exist. Then I have wrapped this with a default empty array value so that the value is usable.

Ensure Stable Data from PartnersAPI::Organizations

---

lib/project_types/script/config/extension_points.yml

This merely updated to the latest shipping-filter ep
There was a bug in the TestHelper for the `Address` type. This fixes it

[scripts] shipping-filter version bump

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/templates/ts/as-pect.config.js

Ticket: https://github.com/Shopify/script-service/issues/948
After https://github.com/Shopify/extension-points/pull/120 gets deployed, we should make use of it in CLI. 
Update script related package versions to enable WASI support.

Update packages to enable WASI for script

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

This PR adds the appropriate error message for when enable/disable are called acting on another script project. We need to ensure that we are only acting upon the script project we are in.
For example, Script A is deployed on App and we are in the Script B context. `shopify enable` should fail for Script B if it contains `api_key=<API key for APP>` in its `.env` file, saying that Script B is not enabled on the App. Right now, whatever script is deployed to App would be enabled.

Add script validation on enable/disable

---

lib/project_types/script/commands/create.rb
test/project_types/script/commands/create_test.rb

In the case of a runtime error during `shopify create script`, the partially created directory is removed. This PR solves a bug in the case that a directory is created that has a name as one that already exists, because previously both would be deleted.
**This is what would happen before this fix** (I try to create a script called `erik2` when a directory with that name previously existed

Keep script dir if created with same name

---

lib/shopify-cli/admin_api/schema.rb

Fixes #792  
When we introduced the new `get_shop` method to schema.rb, we made it an instance method, but we only call it from a class method, so it failed to find the method.
Making `get_shop` a class method.

Make schema.get_shop a class method

---

lib/shopify-cli/commands/connect.rb

When showing the prompt to select one of multiple organizations in `connect`, we were failing to get the CLI message by using an invalid variable `ctx` (it should be `@ctx`).
Fixing the variable name in the call.

Fix message for the org prompt in connect

---

lib/project_types/script/commands/enable.rb
lib/project_types/script/errors.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/commands/enable_test.rb

When passing in a configuration file or configuration properties to `enable` that cannot be parsed, we let the errors bubble up which are currently not user friendly in the case of a missing configuration file or one with improper syntax.
There is one error for both of these cases and it looks like the image below:

Improve error handling when passing config file

---

lib/project_types/script/commands/create.rb
lib/project_types/script/commands/enable.rb
lib/project_types/script/commands/push.rb
lib/project_types/script/messages/messages.rb
lib/shopify-cli/commands/create.rb
test/project_types/extension/commands/create_test.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/commands/push_test.rb

Scripts seem to be inconsistent with other project types in the CLI because we aren’t displaying options in `shopify create --help` since scripts only displays them in extended help, whereas other project types seem to have them in help. We want to look consistent for the preview.
As per the related ticket, we are looking at removing all extended help in script commands for consistency and moving options back to help.
This ticket also changes the ordering in help (`[node|rails|script]`)
**This is what it looked like before this change:**
**This is what it looks like after this change:**

Show options in help for create command

---

lib/shopify-cli/commands/system.rb
lib/shopify-cli/core/entry_point.rb
lib/shopify-cli/db.rb
lib/shopify-cli/heroku.rb
lib/shopify-cli/process_supervision.rb
lib/shopify-cli/tunnel.rb
lib/shopify_cli.rb
test/minitest_ext.rb
test/shopify-cli/process_supervision_test.rb
test/shopify-cli/tunnel_test.rb
test/test_helpers/heroku.rb

This PR attempts to improve the CLI tests, which are failing intermittently when trying to touch the `.db.pstore` file. After the changes to run the CLI natively, we changed the db from `TMP_DIR` to `CACHE_DIR`, which means that the tests run on the same .db.pstore file that the production CLI runs on. We don't want that.
By moving the tests back to using `TMP_DIR`, we ensure they run on a clean(er) db file, since it only exists in the context of the current repo's test runs. Even though I can't explain exactly why this improves the test stability, it makes sense in any case to run it in a contained environment. Empirically, this change made 10/10 test runs pass whereas 7/10 (or less, based on manual runs where I got 4+ fails in a row) passed without it, so there does seem to be some …

Use tmp folder as cache for tests

---

.travis.yml
Gemfile
Gemfile.lock
lib/project_types/extension/tasks/create_extension.rb
lib/project_types/extension/tasks/get_app.rb
lib/project_types/extension/tasks/update_draft.rb
lib/shopify-cli/core/executor.rb
lib/shopify-cli/task.rb
test/project_types/extension/extension_test_helpers/stubs/create_extension.rb
test/project_types/extension/extension_test_helpers/stubs/update_draft.rb
test/project_types/script/commands/push_test.rb
test/project_types/script/layers/domain/domain_package_test.rb

After we released v1.0.0 of the CLI, we updated the Ruby dependency to >= 2.5, but our Travis builds still ran only 2.4 and 2.5, which don't necessarily cover the scenarios we would expect to see in real life any more.
Changing the Travis configs so we run the tests with Ruby 2.5, 2.6, 2.7.

Update Travis Ruby versions and fix Ruby 2.7 warnings

---

lib/shopify-cli/project_type.rb

When running the overall help command in the CLI, we recently (under #788) started sorting the project types before displaying their help, which works nicely. However, when running a plain `shopify help` command from within a project dir, we ran into an error because the types contained strings and symbols.
The 'default' project load (done in entry_point when inside a project dir) always loaded the type as a symbol, whereas the `ProjectType.load_all` method loaded them as strings. We've been lucky so far that this never caused any issues, but when sorting the project types the comparison function borks.
Always load the project types as symbols in `load_all` so our set of types is consistent throughout the code.

Load project types as symbols consistently

---

lib/project_types/node/commands/deploy/heroku.rb
lib/project_types/node/commands/generate/billing.rb
lib/project_types/node/commands/generate/page.rb
lib/project_types/node/commands/generate/webhook.rb
lib/project_types/node/messages/messages.rb
lib/shopify-cli/heroku.rb
lib/shopify-cli/js_deps.rb
lib/shopify-cli/process_supervision.rb
lib/shopify-cli/tunnel.rb
test/project_types/node/commands/generate/billing_test.rb
test/project_types/node/commands/generate/page_test.rb
test/project_types/node/commands/generate/webhook_test.rb
test/shopify-cli/process_supervision_test.rb
test/shopify-cli/tunnel_test.rb

These are the same changes from #764, with the addition of a fix so that `tunnel start / stop` work on Windows as well. This PR means to enable us to run supervised commands on Windows, so that we can continue to work on the features that depend on it (node / rails serve, etc.).
* Replace `fork` with `Process.spawn` which is more cross-platform
* Kill the supervised process before deleting its stderr / stdout file, which is a requirement on Windows
* Adapt the Tunnel so that it works both OS

Fix tunnel and process supervision on Windows

---

lib/shopify-cli/command.rb
lib/shopify-cli/core/executor.rb
lib/shopify-cli/project_type.rb
lib/shopify-cli/sub_command.rb
lib/shopify-cli/tasks.rb
test/shopify-cli/core/executor_test.rb

During a pair programming meeting with @carmelal we realized that tasks do not work on sub-commands and project types. It specifically does not work on project types because there is a load order issue of registering the task and declaring the task to be autoloaded in the project type
- `Changes ProjectType.register_task` to use `ShopifyCli::Tasks.register` to unify the functionality
- `ShopifyCli::Tasks.register.register` to wrap the const_get in a proc to act as a closure so that the Class will be lazy loaded when the task is needed.
- `ShopifyCli::Tasks::Registry[]` to resolve a class or proc
- call `run_prerequisites` on commands and subcommands *just* before calling `call` so that they are only run when needed and not before help.
- added a `task_registry` to the command class so …

Fixing prerequisite tasks for subcommands and project types

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/create.rb
lib/project_types/theme/forms/create.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/tasks/ensure_themekit_installed.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/create_test.rb
test/project_types/theme/forms/create_test.rb
test/project_types/theme/tasks/ensure_themekit_installed_test.rb
test/project_types/theme/themekit_test.rb

- If we want to use Themekit on CLI, we must be able to create a new Theme
- Adapter class makes connection between Themekit and CLI much cleaner
- Introduces `create theme` command to create new theme
- Checks for Themekit executable before attempting to create new theme
- Shows output from Themekit
- Creates and uses `themekit.rb` adapter class
- Moves and renames `Theme::Tasks::EnsureThemekitInstalled::FILENAME` constant to `Theme::Themekit::THEMEKIT`
- Tests for command, task, and adapter class

Command to create Theme

---

lib/shopify-cli/core/monorail.rb
test/shopify-cli/core/monorail_test.rb

Right now our opt-in metrics are broken because it is being provided an invalid version value. This value was forgotten during the migration, so this updates that.
Switching from `ShopifyCli::Git.sha(dir: ShopifyCli::ROOT)` to `ShopifyCli::VERSION` to provide to monorial.

Update monorail cli version

---

lib/shopify-cli/commands/system.rb

This fixes an issue where `system` claims that ngrok is not installed, because it's not looking for the right file.
Changing the check for Windows so that it looks for `ngrok.exe` rather than `ngrok`.

Fix system command ngrok check on Windows

---

ext/shopify-cli/extconf.rb
lib/rubygems_plugin.rb
shopify-cli.gemspec

With the CLI now working natively on Windows, we needed a way for users to install it.
Essentially forking the OS-specific behaviour of the gemspec files so that it works on Windows and UNIX platforms.
Since the Windows PATH env var is limited to 1024 chars (but only when setting it from the command line), using that for our path was not reliable as we could seriously damage

Prepare the gem for Windows installation

---

lib/shopify-cli/tunnel.rb
test/shopify-cli/tunnel_test.rb

- some stuff missed in recent rebase from `master`
- added `-inspect=false` to `ngrok` command
- `tar -xf` doesn't recognize `zip` files on Linux, so added conditional to call `unzip -u` on Linux and `tar -xf` on everything else.

Fixes to tunnel

---

bin/shopify

Our code to prevent loading gems on the CLI is running into a bit of trouble on Windows: when the `readline` gem is loaded, it tries to load a `readline.so` file which is not there.
However, the gem itself is loaded just fine and works as expected, it is only used when prompting for project names or such other open inputs. Those work, so the error itself appears to be harmless, possibly an oversight in the gem code to ignore that file.
Ignore errors when attempting to load a missing `readline.so` file on Windows only.

Ignore readline.so error on Windows

---

lib/shopify-cli/admin_api/populate_resource_command.rb

Ruby 2.7 mandates that keyword args are always passed in with `**`, and this call didn't do that.
Pass in `**kwargs` rather than `kwargs` so Ruby doesn't complain.

Fix Ruby 2.7 kwargs warning

---

lib/shopify-cli/commands/connect.rb
lib/shopify-cli/project.rb

Currently, if a project has neither `.env` nor `.shopify-cli.yml` (a reasonable expectation for previously non-CLI projects), the `connect` command will write `.env` but fail to write `.shopify-cli.yml` claiming we're not currently in a project dir.
This happened because we store the state of `Project.current` after the first attempt to load it, which would be false in that case. Thus when we checked whether we're in a project before writing the YAML file we failed because the previous state was that no `.env` existed.
Forcing a reload of the project state after we write the `.env` and `.shopify-cli.yml` files. The YAML file is only written if the project wasn't a Shopify app before we connected it to an app.

Fix connect command to write .shopify-cli.yml

---

lib/shopify-cli/tunnel.rb

It seems that our log parsing was not able to properly detect ngrok tunnel accounts: with my account, `AccountName` in the logs were my email address and therefore did not match the `\w\s` regex we were using - because of that, we somehow ended up thinking that a tunnel was already up and tried to stop it, which failed.
Allowing some email address characters (`.`, `@`, `_`, `-` and digits) to be part of the regex. I didn't make the regex enforce proper email format because the previous code seems to indicate that it's possible that `AccountName` is an actual name (letters and spaces).

Make ngrok account regex more lenient

---

lib/project_types/rails/commands/serve.rb
lib/project_types/rails/gem.rb
test/project_types/rails/gem_test.rb

Fixes #809
If `GEM_HOME` isn't set in the environment, we (internally, for the CLI during execution) set it to `$HOME/.gem/ruby/x.y.z`, where `x.y.z` is the full version of the ruby used to run the CLI.
Typically this isn't a problem, as `chruby` and `rvm` environments will set the `GEM_HOME` (and `GEM_PATH`) for the user.  Likewise, if a user exclusively uses the CLI to install the required gems, the CLI will find them where it installed them.  
However, in `rbenv` environments, `GEM_HOME` and `GEM_PATH` are NOT set by `rbenv`, and what we choose as the default is typically not on the expected path for `ruby` or `gem`.  For example:
```
$ gem environment home
/home/vagrant/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
$ gem environment path …
```

apply_gem_home uses output from 'gem env home'

---

lib/project_types/script/config/extension_points.yml

Bump EP packages, which should include the following changes:
* [Set default value and add tests to all builders](https://github.com/Shopify/extension-points/pull/139)
* [Updating EP API docs](https://github.com/Shopify/extension-points/pull/137)
* [Update AS to 0.14.0](https://github.com/Shopify/extension-points/pull/140)

Bump EP packages*

---

lib/shopify-cli/messages/messages.rb
lib/shopify-cli/tunnel.rb

Fixes #425 
Checks to see if `curl`, for downloading `ngrok`, and either `unzip` on Linux or `tar` on macOS/Windows (for decompressing the downloaded file) are present on the system before attempting install of `ngrok`
Tophatted on macOS Catalina, Ubuntu 20.04, Windows 10

Added checks for curl, unzip/tar before install of ngrok

---

packaging/homebrew/shopify-cli.base.rb

This PR fixes #814 for future generated releases of CLI.
PR [#180](https://github.com/Shopify/homebrew-shopify/pull/180) on the `Shopify/homebrew-shopify` repo fixes it for the current release.
While `tar -xzf` works on macOS even if the given file is not compressed, on Linux it will complain and abort.
Since the `.gem` file is really an uncompressed tarball, `tar -xf` will work on both macOS and Linux as the first command of the install formula.
🎩 Tophatted on macOS Catalina and Ubuntu 20.04

Remove 'z' flag from initial tar command

---

lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

If you copy and paste the URL for the shop from a browser it will have a trailing slash (at least in Chrome). This causes an error to be thrown where the domain can't be found.
The screenshot below is a before and after for this change when the .env file has a shop domain with a trailing slash.

Fix trailing slash in shop domain

---

lib/project_types/node/commands/generate/billing.rb
lib/project_types/node/commands/generate/page.rb
lib/project_types/node/commands/generate/webhook.rb
lib/shopify-cli/heroku.rb
lib/shopify-cli/tunnel.rb
test/project_types/node/commands/generate/billing_test.rb
test/project_types/node/commands/generate/page_test.rb
test/project_types/node/commands/generate/webhook_test.rb
test/shopify-cli/tunnel_test.rb

Fixes #849 
In some instances, the CLI failed to run external commands on Windows if the current user name has spaces in it. This was due to the commands not being escaped properly.
Quoting the external commands that fail if there is a space in the path.

Quote commands to handle usernames with spaces

---

.github/CONTRIBUTING.md

The link to the `code of conduct README` was not correctly linked in the `CONTRIBUTING.md` file.
This change correctly links the `code of conduct README`.

Fix broken code of conduct link in CONTRIBUTING.md

---

lib/project_types/script/messages/messages.rb

Because you can install your app (that contains scripts) on a non-development store, I removed references to "development" in instances of "development store". 
Also adjusted the error text for `Script not pushed` as suggested by @ow 
Replacing "development store" with "store" in messages
For example:

Scripts-Clean up UX content  - replaced development store with development

---

test/project_types/theme/commands/create_test.rb

- Was previously using `call` from `ShopifyCli::Subcommand`, which is not the correct method
- Adds `.new` to the call in `create` test so a new instance of the class is created

Make new instance of `create` when testing

---

lib/shopify-cli/context.rb
lib/shopify-cli/core/entry_point.rb
lib/shopify-cli/messages/messages.rb
test/minitest_ext.rb
test/shopify-cli/context_test.rb

Fixes #860
Provides a message to the user that a new version of the CLI is available. If there's a new version available, message only appears once every 24 hours.
```
$ shopify
⭑ A new version of the Shopify App CLI is available! You have version 1.1.0 and the latest version is 1.1.1.
To upgrade, follow the instructions for the package manager you’re using:
https://shopify.github.io/shopify-app-cli/getting-started/upgrade/
Use shopify help <command> to display detailed information about a specific command.
Available core commands:
connect: Connect (or re-connect) an existing project to a Shopify partner organization and/or a store. Creates or updates the .env file, and creates the .shopify-cli.yml file.
Usage: shopify connect
create: Create a new project.
Usage: shopify create [ node | …
```

Add message to user if new version available

---

lib/shopify-cli/git.rb

Issue #821 shows that we are not properly reporting git errors when it fails to clone the App repository. The code was previously catching the stderr object rather than its output to show as the error message, which led to the very confusing message displayed in the issue. This PR addresses that by showing the entire Git stderr contents when the command fails.
This PR stores each stderr line we fetch in our failure message so we don't miss any of them.

Catch entire git stderr when cloning

---

lib/project_types/node/commands/serve.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/commands/serve.rb
lib/project_types/rails/messages/messages.rb
test/project_types/node/commands/serve_test.rb
test/project_types/rails/commands/serve_test.rb

Fixes #769 
Currently, the `serve` command only prints out the login URL for the app when the developer presses `Ctrl-T`. However, that approach has two main flaws:
* Not all OSs support Ctrl-T (SIGINFO)
* In the case of rails, the URL is printed along with the stack trace for all of the Puma threads, which makes it very hard to find
In order to make it easier for the developer to find the login URL (aside from running `open` in a different window), this PR prints out the URL prior to starting the server. Since that doesn't depend on any signals, it also does this on any OS.
CC @attaboy @gfscott 
Before:
After:

Remove Ctrl-T from serve and always print URLs

---

lib/project_types/rails/commands/create.rb
lib/project_types/rails/messages/messages.rb
test/project_types/rails/commands/create_test.rb

Fixes #800 
If one attempts to create a new rails project with the CLI, and the project dir already exists, `rails new` won't fail, but will instead try to update the project files. We should avoid that situation by making sure we don't overwrite an existing dir with a new project.
This PR makes sure that the `create` command fails if the project dir already exists by looking for the dir before running any actual commands.

Check for dir before creating rails projects

---

lib/project_types/extension/cli.rb
lib/project_types/extension/features/argo_config.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/types/checkout_post_purchase.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project.rb
test/project_types/extension/features/argo_config_test.rb
test/project_types/extension/models/types/checkout_post_purchase_test.rb

Reverts Shopify/shopify-app-cli#874
Basically https://github.com/Shopify/shopify-app-cli/pull/857 which I merged to soon and had to revert.
This needs to wait for the counterpart in core to be live.

Revert "Revert "read and push post purchase config""

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/push_test.rb
test/project_types/theme/themekit_test.rb

- Need to be able to push theme to Shopify once changed
- Would be good to have a way of deleting theme files
- Uses `theme deploy` command to replace theme files on shop
- `--remove` flag to remove files instead of replacing them (`theme remove`)
- Tests for command and adapter class

Command to push Theme files to Shopify

---

lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb

To provide a more useful suggestion for what to do when the outdated package check fails.
`npm update` respects semver so running that doesn't actually update the
package enough for the outdated check to pass. Installing the latest
version of the package will.
Changes the suggestion message to instruct the user to install the latest EP NPM package.

Fix outdated packages suggestion message

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/deploy.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/create_test.rb
test/project_types/theme/commands/deploy_test.rb
test/project_types/theme/themekit_test.rb

* Efficient to be able to change the live theme from command line
* Combines `push` command from previous PR and `theme publish` to push all changes and then set theme as live theme
* Tests for command and `themekit.rb` method

Add command to deploy Theme

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/forms/pull.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
lib/shopify-cli/admin_api.rb
lib/shopify-cli/api.rb
lib/shopify-cli/messages/messages.rb
test/project_types/theme/commands/pull_test.rb
test/project_types/theme/forms/pull_test.rb
test/project_types/theme/themekit_test.rb
test/shopify-cli/admin_api_test.rb

- There may be a theme already on a shop that a user wants to edit using CLI
- Better to connect to an existing theme than create a new duplicate theme
- Prompt for store, password, theme ID
- Use AdminAPI for theme ID selection
- Theme Kit `get` command to connect CLI to existing theme in store
- Create folder with same name as theme to hold all the files
- Tests for command, form, `rest_request` method in AdminAPI

Command to connect CLI to existing Theme

---

lib/project_types/theme/commands/create.rb
lib/project_types/theme/commands/deploy.rb
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/commands/serve.rb
lib/project_types/theme/forms/create.rb
lib/project_types/theme/forms/pull.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/create_test.rb
test/project_types/theme/commands/deploy_test.rb
test/project_types/theme/commands/pull_test.rb
test/project_types/theme/commands/push_test.rb
test/project_types/theme/commands/serve_test.rb
test/project_types/theme/forms/create_test.rb
test/project_types/theme/forms/pull_test.rb
test/project_types/theme/themekit_test.rb

- User may want changes only apply to a certain env
- Adds `--env` flag support to every command + adapter class method + form
- Changes adapter class command building to private method
- Fixes all related tests

Add `--env` flag support for commands

---

lib/shopify-cli/tunnel.rb

@saulecabrera and I were debugging a strange issue he was getting, where his `serve` command was failing to start. It turns out that we were incorrectly parsing the ngrok logs, and we were failing to detect the account name because of the accent in his name.
We now accept anything as account names, which should ensure that we pick up on all of them. Since we have context both before and after the account name, we can rely on the other markers in the log line and just do a greedy search for the account, which should make this a lot more robust.

Allow any characters in ngrok account names

---

lib/project_types/extension/models/types/product_subscription.rb
test/project_types/extension/models/types/product_subscription_test.rb

Fixes https://github.com/Shopify/app-extension-libs/issues/1012
This PR fixes argo admin identifier. Argo-Admin-Template is using `PRODUCT_SUBSCRIPTION` type https://github.com/Shopify/argo-admin-template/blob/master/README.md#from-github
Change to correct identifier and fix test. 
- Checkout this PR
- Run 
```
./bin/shopify create extension
```
- Verify that PRODUCT_SUBSCRIPTION extension is created successfully.
- Go to the extension folder that you just create.
- Try to register and push it
```
../bin/shopify register
../bin/shopify push
```
- Verify the extension is pushed successfully. 
- Go to app in partner dash and try to publish it. 
Note: 
- Make sure your test app has `product_subscription_extension` beta flag.

[Fix] Fix argo admin identifier

---

lib/project_types/script/config/extension_points.yml

Closes https://github.com/Shopify/script-service/issues/2082
Bumps the Scripts extension point and SDK package version numbers.

Bump Scripts EP and SDK versions

---

test/shopify-cli/git_test.rb

I was commonly have this intermittent failure on my local machine:
```
1) Error:
ShopifyCli::GitTest#test_head_sha:
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /var/folders/jp/nw1k8h_n7ygcf_9mw8l_yql80000gn/T/d20201016-11244-1ddcghg
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1459:in `rmdir'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1459:in `block in remove_dir1'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1470:in `platform_support'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1458:in `remove_dir1'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1451:in `remove'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:780:in `block in remove_entry'
/opt/rubies/2.7.1/lib/ruby/2.7.0/fileutils.rb:1508:in `ensure in postorder_traverse' …
```

Ignore git template in tests

---

Gemfile
Gemfile.lock

Originally added in https://github.com/Shopify/shopify-app-cli/pull/3 but currently unused.

Remove unused session gem dependency

---

test/project_types/extension/features/argo_config_test.rb

Prevent this warning when running tests:
```
/Users/andyw8/.gem/ruby/2.5.1/gems/mocha-1.7.0/lib/mocha/mock.rb:351: warning: undefining `initialize' may cause serious problems
/Users/andyw8/.gem/ruby/2.5.1/gems/mocha-1.7.0/lib/mocha/any_instance_method.rb:44: warning: removing `initialize' may cause serious problems
```

Fix test warnings

---

.rubocop.yml
lib/shopify-cli/api.rb
lib/shopify-cli/http_request.rb
test/fixtures/api/mutation.json
test/shopify-cli/api_test.rb
test/shopify-cli/http_request_test.rb

I'm planning to add some new behaviour to support Employee Authentication and ran into a couple of issues for `api.rb`:
- the current tests were awkward as they stub the HTTP request at a fairly low level, even though those details are mostly incidental to what's being tested
- the `request` method is quite long but has two distinct responsibilities - building the HTTP request and parsing the response.
The request building seems like a cohesive boundary, so I have extracted that out into a new HttpRequest class.
The means the tests can now be simplified, and some duplication removed, as we only need to assert that they send the correct message to `HttpClient.`, rather than using Webmock.
I also found that the single-line `mutation.json` fixture is not needed, as we already have it …

Extract HttpRequest

---

test/shopify-cli/api_test.rb

Since we now lazy-load in the implementation, this test was passing as part
of the whole suite but failing when run in isolation.

Require `HttpRequest` in test

---

lib/shopify-cli/api.rb
lib/shopify-cli/messages/messages.rb
test/shopify-cli/api_test.rb

Adds information for #900 
When our API requests hit an error on the actual Shopify API, we don't really log any useful information that can help debug our requests, which it makes it hard to discover where certain issues come from.
It adds a DEBUG message containing the exception details (in this case, the response code and body) when we hit HTTP 500 / unexpected errors.

Debug error responses from the API

---

RELEASING.md

The release instructions contain the right steps, but they miss a few crucial points (mostly making sure one is at master@HEAD before publishing things). This update aims at plugging those holes.

Improve release instructions

---

.github/PULL_REQUEST_TEMPLATE.md

This PR simply adds a checklist to the PR template as a reminder for contributors to update the CHANGELOG with the changes they're making, so we don't need to come up with messages at realize time and can expedite the release process.

Adding CHANGELOG notice to PR template

---

test/shopify-cli/feature_test.rb

Prevent the real `~/config/shopify/config` being modified during tests.
Closes #915

Use FakeFS for Feature test

---

test/test_helper.rb

This was added in #3 when the tests were first set up, but isn't needed.

Remove unnecessary load path manipulation in tests

---

lib/shopify-cli/core/monorail.rb
lib/shopify-cli/tasks/create_api_client.rb
lib/shopify-cli/tasks/select_org_and_shop.rb
test/shopify-cli/core/monorail_test.rb
test/shopify-cli/tasks/create_api_client_test.rb
test/shopify-cli/tasks/select_org_and_shop_test.rb

To be able to track which apps are created with the CLI, this adds the api key data into the original creation payload. This will allow us to track the process from start to completion
- Change `SelectOrgAndShop` to set partner id metadata
- Change `CreateApiClient` to set api key metadata.

Add APIClient and OrgID to monorail in create actions

---

test/shopify-cli/shopifolk_test.rb

Since we deal with a number of different config paths, I found it a little confusing to keep track of each while reading the tests. I've replaced the references to constants with literals. Although this might seem like a form of duplication, in general we should aim for tests that are easy to read and understand.
Update:
I've also updated the test to use `FakeFS`. This will prevent the same problem as in #930, and also prevents state leaking between tests.

Refactor shopifolk test

---

test/shopify-cli/commands/config_test.rb

This prevent the config test altering the actual `~/.config/shopify/config` by using `FakeFS`. I found it was necessary to stub out the logging to get the tests stable.

Don't write local config during tests

---

test/test_helpers/fake_fs.rb

Once #942 is merged and this is rebased, it should help prevent similar occurrences in future.

[tests] Protect against missing `super` for FakeFS setup

---

.travis.yml

This is to protect against adding tests which hit the real filesystem and modify a developer's `.config/shopify/config`, e.g. 
#942

Prevent new tests from modifying the real Shopify config file

---

lib/project_types/script/config/extension_points.yml

Bump payment-filter package to 0.6.0 to use the new schema, which is updated in https://github.com/Shopify/extension-points/pull/167
I don't see any script related changes in CHANGELOG. I guess it's fine to ignore it.

[script] Bump payment-filter package to 0.6.0

---

test/minitest_ext.rb
test/project_types/rails/gem_test.rb
test/project_types/script/commands/push_test.rb
test/project_types/script/script_project_test.rb
test/shopify-cli/core/monorail_test.rb
test/shopify-cli/js_deps_test.rb
test/shopify-cli/js_system_test.rb
test/shopify-cli/project_test.rb
test/shopify-cli/tasks/create_api_client_test.rb
test/shopify-cli/tasks/select_org_and_shop_test.rb

This can lead to intermittent failures depending on the order tests are run in.

[tests] Add missing calls to `super` in `setup` and `teardown` methods

---

lib/project_types/theme/themekit.rb
test/project_types/theme/themekit_test.rb

Done in conjunction with @carmelal 
When we wanted to use `system`, it was raising an error. This was because some values that were being put into the `command` array (specifically, files and flags) were sometimes nil, and the splat operator could not change nil into a string. All nil values from the `command` array need to be removed.
To remove nil values, we first add files and flags to the `command` array, and then use `.compact` to remove any nil values from the array. Then, we `.flatten` the array to ensure it isn't multidimensional. 🥳

Remove nil values from `command` array

---

.travis.yml
test/minitest_ext.rb
test/shopify-cli/core/monorail_test.rb

Similar to #939 but this will also work when running the tests locally. Should help to prevent introducing unstable tests.

Detect modifications to local config during tests

---

lib/project_types/script/commands/enable.rb
lib/project_types/script/errors.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/commands/enable_test.rb
test/project_types/script/ui/error_handler_test.rb

Closes https://github.com/Shopify/script-service/issues/1757
Enabling a script with specific `config_props` currently has a couple of bugs:
1. `key1:a, key2:b` is parsed as `{"key1": "a", " key2": "b"}` (`key2` has an extra space in the key).
2. `key1:a:invalid_action` raises an ugly error
Fixes the two bugs above by validating the config_props. If invalid, it raises the following error:
@kwringe please let me know if you have a better error message 🙂

Fix config prop parsing in Script::Commands::Enable

---

.github/PULL_REQUEST_TEMPLATE.md

Using a draft PR better conveys the intention of something being a work in progress, and protects against accidental merges.

Use draft PR instead of WIP indicator

---

CHANGELOG.md
lib/shopify-cli/js_deps.rb
test/shopify-cli/js_deps_test.rb

Fixes https://github.com/Shopify/app-extension-libs/issues/1112
This PR fixes `shopify serve` issue when running Argo extension. `chokidar ` is an optional dependency that webpack uses for Argo. Considering Shopify cli is for development, it makes sense to not use `--no-optional` option.
- Remove `--no-optional` and fix test.
- Do 
```
dev cd shopify-app-cli
./bin/shopify create extension
```
- Follow the steps to create new Argo Admin Extension
- Go to new extension directory and point to correct local shopify-app-cli
```
../bin/shopify-app-cli/bin/shopify serve
```
- Verify that extension is served correctly without having to do `npm install` again.

[Fix] Remove --no-optional when running npm

---

lib/shopify-cli/project.rb
test/shopify-cli/project_test.rb

When creating a new project, a Shopify employee will be prompted whether they want to act on behalf of the Shopify organization or not. If they do, we want to persist that in the project's configuration. This will then be read by project commands to determine whether to send the Shopify employee HTTP header or not.

Add Shopify org indicator for new project config

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/connect.rb
lib/project_types/theme/forms/connect.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/connect_test.rb
test/project_types/theme/forms/connect_test.rb
test/project_types/theme/themekit_test.rb

* Currently the `pull` command can't be used outside a project, but can't be used inside a project either
* Makes `pull` into `connect theme`, a subcommand from `connect`, by renaming and moving files

Command to connect Theme

---

lib/project_types/theme/messages/messages.rb
lib/project_types/theme/tasks/ensure_themekit_installed.rb
lib/project_types/theme/themekit.rb
lib/shopify-cli/feature.rb
test/project_types/theme/tasks/ensure_themekit_installed_test.rb
test/project_types/theme/themekit_test.rb

* Having most up-to-date Theme Kit version is good but not always desirable
* If Theme Kit has an update it will prompt the user to type `theme update`, which will not work
* When downloading Theme Kit, prompts for autoupdate
* Checks if it has been a week since the last update
* If so, runs `theme update`

Automatically update Theme Kit weekly

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/generate.rb
lib/project_types/theme/commands/generate/env.rb
lib/project_types/theme/forms/connect.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/generate/env_test.rb
test/project_types/theme/commands/generate_test.rb
test/project_types/theme/forms/connect_test.rb
test/project_types/theme/themekit_test.rb

* Harder to mess up `config.yml` if generating envs rather than typing them yourself
* Different envs for more flexibility on each theme
* Adds `generate` command and `env` subcommand
* Moves `query_themes` to adapter class
* Get store and password for user from existing config file as default

Command to generate new envs

---

test/shopify-cli/admin_api_test.rb
test/shopify-cli/core/entry_point_test.rb
test/shopify-cli/oauth/servlet_test.rb
test/shopify-cli/oauth_test.rb
test/shopify-cli/partners_api_test.rb
test/shopify-cli/tunnel_test.rb
test/test_helper.rb

Mocha has a couple of configuration options to detect stubbing on `nil` or of non-existing methods.

Enable mocha checks

---

lib/project_types/theme/cli.rb
lib/project_types/theme/commands/connect.rb
lib/project_types/theme/commands/create.rb
lib/project_types/theme/commands/deploy.rb
lib/project_types/theme/commands/generate.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/commands/serve.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/tasks/ensure_themekit_installed.rb
lib/project_types/theme/themekit.rb
lib/shopify-cli/project_type.rb
test/project_types/theme/commands/connect_test.rb
test/project_types/theme/commands/create_test.rb
test/project_types/theme/commands/deploy_test.rb
test/project_types/theme/commands/push_test.rb
test/project_types/theme/commands/serve_test.rb
test/project_types/theme/tasks/ensure_themekit_installed_test.rb
test/project_types/theme/themekit_test.rb

- Need run task before every command so is better to use prerequisite task than explicitly running each time
- Better not to open frame is nothing happening
- Refactor task so only opens frames if running task
- Make into prereq task

Make EnsureThemekitInstalled a prerequisite task

---

CHANGELOG.md
lib/project_types/extension/cli.rb
lib/project_types/node/cli.rb
lib/project_types/node/commands/connect.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/cli.rb
lib/project_types/rails/commands/connect.rb
lib/project_types/rails/messages/messages.rb
lib/project_types/script/cli.rb
lib/shopify-cli/commands/connect.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/project_type.rb
test/project_types/node/commands/connect_test.rb
test/project_types/rails/commands/connect_test.rb
test/shopify-cli/commands/connect_test.rb

* "Fixes" #614 
* Allows for greater flexibility depending on behaviour of project types
* Splits `connect` command into subcommands for each project type (similar to `create`)
* Default fallback behaviour if `connect` not implemented for that project type

Reorganize `connect` command

---

Gemfile
Gemfile.lock
lib/project_types/node/commands/create.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/commands/create.rb
lib/project_types/rails/messages/messages.rb
lib/shopify-cli/api.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/partners_api.rb
lib/shopify-cli/task.rb
lib/shopify-cli/tasks/create_api_client.rb
lib/shopify-cli/tasks/ensure_env.rb
lib/shopify-cli/tasks/select_org_and_shop.rb
test/minitest_ext.rb
test/project_types/extension/extension_project_test.rb
test/project_types/node/forms/create_test.rb
test/project_types/rails/forms/create_test.rb
test/shopify-cli/api_test.rb
test/shopify-cli/core/monorail_test.rb
test/shopify-cli/project_test.rb
test/shopify-cli/tasks/create_api_client_test.rb
test/shopify-cli/tasks/ensure_env_test.rb
test/shopify-cli/tasks/select_org_and_shop_test.rb
test/test_helpers/partners.rb

* We previously added behaviour to detect if someone is a Shopify employee. Now, for certain tasks, they will be prompted `Are you working on a 1P (1st Party) app?`. If they reply yes, this sends an additional header in the request which alters the behaviour in the partner app (that PR is currently in review).
* Not essential to the PR, but I've also added [minitest-fail-fast](https://github.com/teoljungberg/minitest-fail-fast) – it was useful when working to troubleshooting some kinds of noisy failures (it's inactive by default).
* See GitHub comments for further notes.

Send Shopify header for employees

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/domain/extension_point.rb
lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
test/project_types/script/layers/domain/extension_point_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_project_creator_test.rb
test/project_types/script/layers/infrastructure/extension_point_repository_test.rb

Closes https://github.com/Shopify/script-service/issues/1249
To be merged after https://github.com/Shopify/shopify-app-cli/pull/979
This pull request ensures that at script creation time, the latest stable release of each extension point is used. This change will remove some friction for the extension point authoring process, from this point on, no updates to the CLI will be needed. An update to the CLI will be needed only when new extension points are introduced.

Use latest stable extension points

---

lib/project_types/script/layers/infrastructure/errors.rb

https://github.com/Shopify/shopify-app-cli/pull/995 changed cop rules that https://github.com/Shopify/shopify-app-cli/pull/979 violates, but https://github.com/Shopify/shopify-app-cli/pull/979 was merged before https://github.com/Shopify/shopify-app-cli/pull/995
Appeases rubocop failures

Fix Layout/EmptyLineBetweenDefs rubocop violation

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

Fixes https://github.com/Shopify/script-service/issues/1845
If theres a server error in one of our APIs, the API class will print a failure message and return nil. We don't currently check if it is nil which means we run into a messy stacktrace later on that is unhelpful to debug.
Checks if the response is nil, and raises an exception & print a helpful error if it is. 
Settled on the following content with @kwringe the other day:

Fix unhandled empty response error in script_service.rb

---

lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb

Fixes https://github.com/Shopify/script-service/issues/1795
Previously, we had multiple locations that checks the current node version. The version they required were different and led to different behaviour. 
Uses a single `MIN_NODE_VERSION` constant that each place can reference to check what version we need to use.

[scripts] Fix inconsistent node version warning

---

lib/project_types/theme/commands/deploy.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/commands/serve.rb
lib/project_types/theme/themekit.rb
test/project_types/theme/commands/deploy_test.rb
test/project_types/theme/commands/push_test.rb
test/project_types/theme/commands/serve_test.rb
test/project_types/theme/themekit_test.rb
test/shopify-cli/admin_api_test.rb

- Certain commands require flags to function (`--allow-live`)
- Some commonly used flags in Theme Kit should also be in CLI
- Add support for:
- `--allow-live`
- `--notify`

Support important flags

---

lib/project_types/script/config/extension_points.yml

There's a new Scripts tax extension point that needs to be integrated with the CLI.
Related issue: https://github.com/Shopify/script-service/issues/2268
This PR updates the available extension points so that users can create tax and payment filter scripts.

Add tax filter EP

---

.github/CODEOWNERS

The `scripts` team has split into subteams and `scripts-experience` will primarily be the ones owning the CLI changes. 
Changes the codeowners of the script project type from `scripts` to `scripts-experience`.

Change script project codeowners from scripts to scripts-experience

---

lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/infrastructure/script_repository.rb
test/project_types/script/layers/infrastructure/script_repository_test.rb

We no longer need to create a temporary build context when building the script. When building, we should have the exact same side effects as running `npm run build` directly.
Removes the `get_temp_build_context` method from the ScriptRepository.

[Scripts] Remove ScriptRepository#with_temp_build_context

---

lib/shopify-cli/commands/config.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/shopifolk.rb
test/shopify-cli/commands/config_test.rb
test/shopify-cli/shopifolk_test.rb

This will allow Shopify employees to opt-in to the Employee Authentication beta by running:
`shopify config shopifolk-beta --enable`

Add beta setting for Employee authentication

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/messages/messages.rb

Will introduce code in the future to instruct script developers to
migrate their projects to the new toolchain when we start using the
metadata.
We want to have newly created scripts producing metadata like which version of a schema they are relying on as one of their build artifacts. This involves using a new version of the build toolchain and a new argument flag. We also want error messages providing a suggested build command to include the metadata flag.
I also found a mistake in the existing suggested build command and what appears to be a typo with a missing space which I fixed while I was making these changes.
- Update the version of the toolchain new scripts projects are scaffolded with to one that supports producing metadata as a build artifact
- Add the metadata argument flag as …

New scripts use new toolchain and generate metadata

---

lib/shopify-cli/shopifolk.rb
test/shopify-cli/shopifolk_test.rb

'shopifolk' is treated as a feature, but `shopifolk-beta` is considered to be separate setting.
I had changed this previously but missed a couple of places.

Fix shopifolk-beta flag location

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/forms/create.rb
lib/project_types/script/layers/application/extension_points.rb
lib/project_types/script/layers/domain/extension_point.rb
lib/project_types/script/layers/infrastructure/extension_point_repository.rb
test/project_types/script/forms/create_test.rb
test/project_types/script/layers/application/extension_points_test.rb
test/project_types/script/layers/domain/extension_point_test.rb
test/project_types/script/layers/infrastructure/extension_point_repository_test.rb
test/project_types/script/layers/infrastructure/fake_extension_point_repository.rb

Issue: https://github.com/Shopify/script-service/issues/2440
We're deprecating use of the Discounts EP. We should discourage the further creation of Discount scripts on the CLI.
I'm using a fairly casual deprecation method since this isn't being used in production. It doesn't prevent the usage of `discounts` scripts, it just hides them from the list during the initial creation. This should help steer away script authors from creating new `discounts` scripts.
The change was larger in size then anticipated because previously the list of types was being derived directly from yaml. I've added an intermediary layer  which transforms the yaml configs into domain objects, which then allows us to filter by deprecated status.
In future PRs, I'd like to add simple deprecation warnings to the other …

Deprecate Discounts EP

---

lib/project_types/script/messages/messages.rb

This commit improves error messages when building (pushing) scripts. The intention of this improvement is to make the messages more explicit.
Build command not found
<details>
</details>
Invalid build command
<details>
</details>

fix: Improve build script error messages

---

lib/project_types/script/errors.rb
lib/project_types/script/layers/application/extension_points.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/script_project.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/extension_points_test.rb
test/project_types/script/script_project_test.rb

Issue: https://github.com/Shopify/script-service/issues/2440
The C0 Discounts EP is being deprecated. In a previous PR, we prevented Discounts from being shown as an option in the EP list when creating a script. However, users with Discount scripts are still able to push their scripts to Script Service and those commands will succeed, but not work in production
When attempting to initialize a Script Project, an error is raised which informs you that the EP your script uses is deprecated. Since this EP isn't officially released, there's no particular need to provide recourse for the developer.
This doesn't truly prevent anyone from publishing Discount Scripts, that update will come to Script Service soon.
I haven't added a changelog entry since this isn't public.

Prevent commands from succeeded for deprecated EPs

---

CHANGELOG.md
lib/project_types/rails/commands/create.rb
lib/shopify-cli/context.rb
test/project_types/rails/commands/create_test.rb

As seen in #1026, if running a Rails generator command fails, an error is outputted but the script still continues. This can lead to the command appearing to succeed even though a broken/incomplete app was generated.
I've also opened https://github.com/Shopify/cli-kit/pull/123 to fix some some incorrect documentation.
Check the process status of system calls and abort if it fails.

Abort on failed system call

---

CHANGELOG.md
lib/project_types/rails/commands/create.rb
test/project_types/rails/commands/create_test.rb

When the app is generated we pass `--skip-spring` so there should be no
need to ever call `spring stop`.

Remove unnecessary call to `spring stop`

---

Rakefile
lib/shopify-cli/result.rb
lib/shopify_cli.rb
test/shopify-cli/result_test.rb

This PR introduces a result monad to simplify working with method objects. Method objects while not yet formalized are in quite a few places in the Shopify CLI. Introducing a result monad will allows us to standardize return values of these objects and furthermore simplify chaining multiple method objects in a pipeline.
It introduces two containers for wrapping the result of an action. One for signifying the successful execution of an action and one for signifying a failure. Both containers implement the same API, which has been designed to simplify transforming a result through a series of steps and centralize the error handling in one place. The implementation is heavily inspired by a concept known as result monads in other languages. Consider the following example that uses lambda …

Add Result Monad

---

CHANGELOG.md
lib/project_types/script/cli.rb
lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/errors.rb
lib/project_types/script/layers/domain/metadata.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/domain_package_test.rb
test/project_types/script/layers/domain/metadata_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/fake_push_package_repository.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

Supersedes https://github.com/Shopify/shopify-app-cli/pull/1040
This PR propagates the version of the extension point schema used by the script to script-service when pushing.
Script-service needs to know what version of a schema is in use by a script to validate the version is valid and to correctly format payloads for the script.
This starts sending the schema version as a parameter to script-service. It also raises errors if the metadata file is missing or is invalid (though we can change to use a more tolerant approach should we choose to).

Scripts schema version push

---

Rakefile
lib/shopify-cli/method_object.rb
lib/shopify_cli.rb
test/shopify-cli/method_object_test.rb

Simplify the creation of method objects.
It introduces the `MethodObject` mixin that can be included in any class that implements `call` to ensure that
* `call` will always yield a `ShopifyCli::Result` by prepending a module that takes care of the result wrapping and
* a `to_proc` method that allows instances of this class to be passed as a block.
For convenience, this mixin also adds the corresponding class methods: `call` and `to_proc`. Method and result objects pair nicely as they greatly simplify the creation of complex processing chains:
```ruby
class Serialize
include MethodObject
def call(attrs)
attrs.to_json
end
end
class Deserialize
include MethodObject
def call(json)
JSON.parse(json)
end
end
Serialize
.call(firstname: "John", lastname: "Doe")
.then(&Deserialize)
.map { |attrs| …
```

MethodObject

---

lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/domain/metadata.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/domain_package_test.rb
test/project_types/script/layers/domain/metadata_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

This PR adds a `use_msgpack` boolean field to the `app_script_update_or_create` call. PRs to produce this field into `build/metadata.json` at script build time, and to consume this field on the backend are already open in their respective repositories.
_Note that this field is temporary, and will be removed once the msgpack migration completes._

[Scripts] Add 'use_msgpack' field to the script push operation

---

lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb

Closes https://github.com/Shopify/script-service/issues/2404
Managing script projects does not currently work with the newer versions of npm/node because they now treat unsatisfied peer dependencies as errors instead of warnings.
Dependencies in the AS projects have a peer dependency on AS which is currently 0.X.Y versioned. This makes it tough to satisfy peer deps because 3p packages like as-pect specify their own peer dependency (currently `^0.12.0`) and shopify tooling has its own (`^0.16.1`). As-pect does not release a new version for each new version of AS so we can't just update that whenever we update our version of AS.
Adds the `--legacy-peer-deps` flag to the `npm install` call which will treat peer dependency errors as warnings like npm v<7. When we bump an AS/tooling/as-pect …

[scripts] Run npm install with legacy-peer-deps flag for AssemblyScript projects

---

dev.yml

To prevent failures such as:
```
/Users/andyw8/.gem/ruby/2.5.1/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated rake 13.0.3, but your Gemfile requires rake 13.0.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

Use bundle exec for dev

---

lib/project_types/script/commands/create.rb
lib/project_types/script/forms/create.rb
lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/script_project.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/forms/create_test.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/layers/infrastructure/fake_push_package_repository.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/test_helpers/fake_script_project.rb

Fixes https://github.com/Shopify/script-service/issues/2487
Depends on https://github.com/Shopify/script-service/pull/2537
We want a script developer to define a description of a script project.
This PR:
- Allows the user to specify a description during creation with `shopify create script --description=something` or through a prompt if no flag is passed
- Sends that description along with the PushPackage when creating or updating the app script

[scripts] Support defining script description

---

lib/project_types/script/layers/domain/push_package.rb

The build was passing in https://github.com/Shopify/shopify-app-cli/pull/1072 but there were some rubocop violations when I merged 🤷 
Fixes the rubocop violations.

Fix rubocop violations

---

lib/project_types/rails/commands/create.rb
test/project_types/rails/commands/create_test.rb

Shopify/shopify_app#1191 has changed the shopify_app gem to prompt the user before adding a potentially breaking migration. Since the CLI captures the output of the generate:shopify_app command, the prompt never shows up when creating a new rails project and appears to hang, even though it's just waiting for user input.
To allow the CLI to go around the prompt, a force_access_scopes_migration flag has been added to the generator to allow the app to be created without user input. We just need to start passing in this flag when creating new rails projects

Add flag to force rails migration to add access scopes

---

lib/project_types/rails/commands/create.rb
lib/project_types/rails/gem.rb
test/project_types/rails/commands/create_test.rb

Fixes #1057 
Limits `rails` installation to `<6.1` (due to https://github.com/Shopify/shopify_app/pull/1134)
Limits `shopify_app` installation to `>=17.0.3` (due to https://github.com/Shopify/shopify_app/pull/1097)
Correction to version checking as `rails` doesn't follow Semantic Versioning format.

Add version constraints to 'create rails'

---

lib/project_types/script/commands/push.rb
lib/project_types/script/messages/messages.rb

Updates some script error messages as requested by @kwringe. 
- Removes `Please` from messages as its redundant.
- Tells the user what app we weren't able to push to.

[scripts] update script error messages

---

Rakefile
lib/project_types/extension/cli.rb
lib/project_types/extension/commands/extension_command.rb
lib/project_types/extension/models/lazy_specification_handler.rb
lib/shopify-cli/lazy_delegator.rb
lib/shopify_cli.rb
test/project_types/extension/commands/extension_command_test.rb
test/project_types/extension/models/lazy_specification_handler_test.rb
test/shopify-cli/lazy_delegator_test.rb

In future, we will have to defer costly network calls when fetching specifications from the Partner Dashboard API until the call is absolutely necessary.
This PR introduces a generic mechanism for constructing delegators that defer delegates resolution until it becomes necessary.
`LazyDelegator` defers initialization of its underlying delegatee until the latter is accessed for the first time due to a method call that the delegator cannot handle itself:
```ruby
result = LazyDelegator.new do
end
result      # referencing the object itself does not result in Proc evaluation
result.to_h # however, calling a method on it will result in Proc evaluation
```
LazyDelegator lends itself to being subclassed in scenarios where some facts are known and others are costly to compute:
```ruby
class …
```

LazyDelegator & LazySpecificationHandler

---

lib/shopify-cli/lazy_delegator.rb

Fixes a missing dependency
Depending on file load order, it is possible to run into an issue that can be traced back from a dependency not being loaded in time. This change ensures that `delegate` is being loaded before it is used by the `LazyDelegator` class.

Lazy Delegator require delegate stdlib

---

lib/shopify-cli/result.rb
test/shopify-cli/result_test.rb

To ensure that `ShopifyCli::Result` properly handles wrapping and unwrapping of `nil`.
Changes the guard clause in `Result.wrap` and `Result::Failure#unwrap` to ensure that `nil` is considered a valid argument. Wrapping `nil` results in a `ShopifyCli::Result::Failure`.

Result.wrap(nil) and Result#unwrap(nil) support

---

lib/project_types/script/commands/push.rb
lib/project_types/script/errors.rb
lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/script_project.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/layers/infrastructure/fake_push_package_repository.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/script_project_test.rb
test/project_types/script/test_helpers/fake_script_project.rb
test/project_types/script/ui/error_handler_test.rb

Closes https://github.com/Shopify/script-service/issues/2521
We want a script developer to define a ui via a yaml configuration and include that file in the script's deploy package on push.
- Allows a developer to specify a configuration ui definition. The flow of doing this will be improved in another PR that creates an empty file by default. But to manually test it, a dev can:
- create a configuration file with an appropriate definition
- set the value of the `configuration_ui_file` field in a script project's `.shopify-cli.yml` to the filename of the configuration file.
Currently, YAML validation errors from Script Service are not shown. This is because the base PR (https://github.com/Shopify/script-service/pull/2597) is getting big and I want to merge it before adding custom error …

[scripts] Send configuration ui definition when pushing script

---

lib/shopify-cli/method_object.rb
lib/shopify-cli/result.rb

There are a few typos/errors in documentation of `MethodObject` and `Result` class
Fixing typos and errors in documentation.
~~- [ ] I've added a CHANGELOG entry for this PR (if the change is public-facing)~~
~~- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows).~~

Fixing typos and errors in documentation

---

lib/project_types/script/layers/infrastructure/script_service.rb

When running through the end to end guide for the Scripts Platform on fresh installs of every service, I didn't find a way to get a script installed onto `shop1` without database manipulation or going through the process of installing an app.
Ideally we don't need to rely on Partners for our E2E
We used to use a flag `BYPASS_PARTNERS_PROXY` which allowed us to call Script Service directly when pushing and enabling Scripts. Somewhere along the line, this flag broke and now we always send a `0` as our `shop_id` due to this line `shop_id: shop_domain&.to_i`. I'm updating that line to send a 1, rather than trying to convert the shop domain string into an integer.
This should only effect local development. If there's a purpose to this line that I missed please let me know

Fix partner proxy bypass

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb

This PR bumps the toolchain and SDK versions required by EPs. In addition, I've disabled the dependency check on `create` and `push`.

[scripts] Bump EP versions and use shopify_main

---

lib/project_types/script/commands/create.rb
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/layers/application/create_script_test.rb

Fixes https://github.com/Shopify/script-service/issues/2566
- During normal script project creation, a config ui yaml file will be created for the user by default at `ui-config.yml`.
- If the script developer does not want their script to be configurable in the admin, then during create they can use the `--no-config-ui` flag.

[scripts] Create a default config ui file during project creation

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/ui/error_handler_test.rb

Depends on https://github.com/Shopify/script-service/pull/2672
Part of https://github.com/Shopify/script-service/issues/2645
The server will tell us what is wrong with a user's config ui file if it prevents a push from succeeding. This PR catches those errors and displays a relevant message to the user. 
Final error messages is TBD.

[scripts] Display config ui errors after a failed push

---

lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

The `config_ui` entity will be nil if a script project is configured not to use it. So we need to safely navigate accessing its values during the script push.
- [] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [] I've considered possible cross-platform impacts (Mac, Linux, Windows).

[scripts] Check if config-ui is nil during script-service push

---

lib/project_types/extension/commands/create.rb

Just removing some stray quotes that make the help output look strange.

Remove trailing quotes in help text

---

CHANGELOG.md
lib/project_types/node/forms/create.rb
lib/project_types/node/messages/messages.rb
lib/project_types/rails/forms/create.rb
lib/project_types/rails/messages/messages.rb
test/project_types/node/forms/create_test.rb
test/project_types/rails/forms/create_test.rb

**Paired with @carmelal 🥳**
Fixes #1004 for Rails as well as Node (issue only mentions Rails). 
When generating a Rails or Node app, and specifying a name that includes 'shopify' (e.g. 'my-shopify-app'), a lot of app generation is done before the application name is checked and the generation is aborted.
This pull request checks the application name and, if needed, aborts the app generation (with an error message) immediately after the app name is specified by the user. This saves time for the user and prevents the generation of an invalid app.

Abort app generation if name contains Shopify

---

lib/project_types/extension/commands/serve.rb
lib/project_types/extension/extension_project.rb
lib/project_types/extension/messages/messages.rb
lib/shopify-cli/tasks/ensure_dev_store.rb
test/project_types/extension/commands/serve_test.rb
test/shopify-cli/tasks/ensure_dev_store_test.rb

Fixes https://github.com/Shopify/argo-admin-private/issues/1404
This PR adds validation to fix cases that shop or apiKey are invalid. Ex: empty string, partner account doesn't have any shops, shop doesn't have any apps. 
- Add check for shop and api_key when running serve (under argo-admin-beta flag)

[Fix] Add validation when serving argo-admin

---

lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb

Removes the temporary change added in https://github.com/Shopify/shopify-app-cli/pull/876 that checks that a developer is using the most recent major version of an EP. We shouldn't do this permanently because it defeats the purpose of semver. 
Removes the temporary change added in https://github.com/Shopify/shopify-app-cli/pull/876

[scripts] Remove temporary check that EP packages are up to date

---

lib/project_types/extension/cli.rb
test/project_types/extension/commands/extension_command_test.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/extension_test_helpers/test_extension_setup.rb
test/project_types/extension/models/specification_handlers/default_test.rb

Cleanup production code that is no longer in use.
Specifications are now managed by the ExtensionCommand and AskType. The CLI no longer requires shared state to manage specifications. This commit therefore removes
* `Extensions.specifications`,
* `Extension.specifications=`, and
* all related calls in the test suite.

Remove Extension.specification accessor

---

lib/project_types/script/layers/application/create_script.rb
test/project_types/script/layers/application/create_script_test.rb

Part of https://github.com/Shopify/script-service/issues/2706
Adds a title field to a scripts default config ui file.

[scripts] Add title field to a default config ui file

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/domain/extension_point.rb
lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
test/project_types/script/layers/domain/extension_point_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_project_creator_test.rb

This PR adds support for shipping and payment methods extension points. These extension points are bounded to the checkout domain.
The main changes in this PR are
- Adding a `domain` attribute to the extension point object
- Using that attribute to determine how to bootstrap and build a script
An ideal 🎩 list:
- Ensure that "legacy" scripts work correctly (bootstrap, test, build)
- Ensure that domain scripts work correctly (bootstrap, test, build)

[scripts] Add shipping and payment methods extension points

---

lib/project_types/extension/commands/extension_command.rb
lib/project_types/extension/commands/push.rb
lib/project_types/extension/commands/register.rb
lib/project_types/extension/commands/serve.rb
lib/project_types/extension/extension_project.rb
lib/project_types/extension/extension_project_keys.rb
lib/project_types/extension/messages/message_loading.rb
test/project_types/extension/commands/extension_command_test.rb
test/project_types/extension/extension_project_test.rb
test/project_types/extension/extension_test_helpers/fake_extension_project.rb

Improve code readability.
Pure refactoring. Behaviour should not be changed. I just replaced `extension_type_identifier` and `extension_type` with our new nomenclature.

Cleanup - Follow new Specification Nomenclature

---

lib/project_types/script/commands/push.rb
test/project_types/script/commands/push_test.rb

If `EnsureEnv` fails (for example, if a request to Partners fails), then the `env` won't be created and `Project.current.env = nil` so `Project.current.env.api_key` raises. 
Safely access `api_key` in this case.

[scripts] Safe access api_key from project env during script push

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/forms/create.rb
lib/project_types/script/layers/application/extension_points.rb
lib/project_types/script/layers/domain/extension_point.rb
test/project_types/script/forms/create_test.rb
test/project_types/script/layers/application/extension_points_test.rb
test/project_types/script/layers/infrastructure/fake_extension_point_repository.rb

Fixes https://github.com/Shopify/script-service/issues/2793
We want to be able to hide certain script EPs that are still in development from the user by default. To do this, we'll follow the same `beta` pattern that we have for EP language implementations.
- supports specifying an EP as `beta` within the `extension-points.yml` file.
- by default, we only display non-beta EPs during project creation
- you can enable beta EPs by running `shopify config feature scripts_beta_extension_points --enable` 
- sets `unit_limit_per_order` and `tax_filter` EPs as beta
Only shows Non-Beta EPs.
<details>
</details>
Shows Beta + Non-Beta EPs.
<details>
</details>

[scripts] support specifying beta extension points

---

lib/project_types/script/layers/domain/metadata.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/domain/metadata_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

Part of https://github.com/Shopify/script-service/issues/2623
Our error messages tend to suggest that the user `Ensures the 'shopify/scripts-toolchain-as' package is up to date` for many errors that are unrelated. This is because the current generalized error messages were updated. Instead, we should only tell the user to update the toolchain package when they need to, and fallback to the existing general error case.
- Checks the GraphQL error tag to only display invalid metadata errors when relevant.
- Improves the verbosity of the general error case by propagating the GraphQL error to the user. 
- No content has changed here. This error message will only be shown for errors relating to invalid schema metadata
<details>
</details>
- This uses the existing general GraphQL error case that …

[scripts] Only display extension metadata errors when relevant

---

CHANGELOG.md
lib/project_types/node/commands/generate.rb

Fixes #1176 
- Remove `subcommand` calls from `generate.rb` under `node`

Remove subcommand calls from generate.rb under node

---

lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/rust_task_runner.rb
lib/shopify-cli/context.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/rust_task_runner_test.rb
test/shopify-cli/context_test.rb
test/test_helpers/fake_fs.rb

Part of https://github.com/Shopify/script-service/issues/1723
For windows, binary files need to be read/written using `File.binread` and `File.binwrite` instead of `File.read` and `File.write` as a `\x1A` sequence would indicate a file closure.
- Adds `binread` and `binwrite` methods to `Context`, which is how we handle manipulating the filesystem
- Reads and writes all wasm files using these new methods

[scripts] read and write wasm files using binread/binwrite

---

lib/graphql/extension_create.graphql
lib/project_types/extension/commands/register.rb
lib/project_types/extension/extension_project.rb
lib/project_types/extension/extension_project_keys.rb
lib/project_types/extension/features/argo_renderer_package.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/models/registration.rb
lib/project_types/extension/tasks/converters/registration_converter.rb
test/project_types/extension/commands/register_test.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/extension_project_test.rb
test/project_types/extension/extension_test_helpers/fake_extension_project.rb
test/project_types/extension/extension_test_helpers/stubs/create_extension.rb
test/project_types/extension/extension_test_helpers/temp_project_setup.rb
test/project_types/extension/features/argo_renderer_package_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/tasks/converters/registration_converter_test.rb

Closes https://github.com/Shopify/argo-admin-private/issues/1306
`argo-admin-cli` requires a `uuid` to be passed as a command line argument. This `uuid` needs to be the `registration_id`. However, `registration_id` is not always available, so we need a temporary uuid until the `registration_id` is available.
* Adds `--uuid` as a command line argument to ArgoServe command.
* Using the `registration_uuid` instead of `registration_id` so we do not have to create a temporary `extension_creation_id` field, and so we don't mess with the `registration_id`
* If no `registration_uuid` is available, a temporary on is created at registration `create`. This is later updated when the extension is registered on the `register` command.
- ~[ ] I've added a CHANGELOG entry for this PR (if the change is …

Feature: Add extension_creation_id to ExtensionProject, pass uuid to ArgoServe command

---

lib/project_types/script/layers/infrastructure/script_project_repository.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb

Some of the configuration UI definition fields for Scripts are being changed. The only relevant field in CLI is the top-level `type` field, which is being renamed to `inputMode`.
Backend PR: https://github.com/Shopify/script-service/pull/2939
Related issue: https://github.com/Shopify/script-service/issues/2860
**This PR depends on the Script Service PR: https://github.com/Shopify/script-service/pull/2939**
This PR updates the `type` field to `inputMode`

Rename Scripts Configuration UI Definition Fields

---

lib/project_types/script/graphql/app_script_update_or_create.graphql
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/domain/script_project.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/test_helpers/fake_push_package_repository.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb

Closes https://github.com/Shopify/script-service/issues/2904
We want to uniquely identify scripts. On initial push, the server gives us a `uuid` which we'll store in the `.env`. This `uuid` will now be the thing we use to identify a script.
Note that this change doesn't fully support multiple scripts per extension point and app. There are still some waiting server side tasks for that.
- Stores `uuid` in the `.env` after a successful push
- If present in the `.env`, send the `uuid` in the package during `push`

[scripts] Identify scripts through uuid

---

lib/project_types/script/layers/domain/script_project.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb

The UUID is currently stored as downcase in the env, but other keys are stored as UPCASE.
Stores the uuid in the `.env` file like `UUID=fi8db-...` instead of `uuid=fi8db-...` to be consistent.

[scripts] upcase uuid key in .env

---

CHANGELOG.md
lib/project_types/extension/cli.rb
lib/project_types/extension/features/argo.rb
lib/project_types/extension/features/argo_renderer_package.rb
lib/project_types/extension/messages/messages.rb
lib/shopify-cli/js_system.rb
test/project_types/extension/commands/push_test.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/extension_test_helpers/dummy_argo.rb
test/project_types/extension/features/argo_renderer_package_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/features/argo_test.rb
test/shopify-cli/js_system_test.rb

Fixes https://github.com/Shopify/argo-private/issues/1503
Fixes https://github.com/Shopify/argo-private/issues/1504
Determines the renderer package dynamically instead of inferring it from the extension specification.

Determine Argo Renderer Dynamically

---

CHANGELOG.md
lib/shopify-cli/version.rb

App Extension development is broken in 1.9.0
Releasing 1.9.1 which inclues
* [1201](https://github.com/Shopify/shopify-app-cli/pull/1201) Determine Argo Renderer Dynamically. This fixes `shopify serve` and `shopify push` for extensions.

Release v1.9.1

---

lib/project_types/script/config/extension_points.yml

We only want `payment_methods` and `shipping_methods` EPs to be displayed by default. 
- hides payment_filter and shipping_filter EPs by default

[scripts] Deprecate payment_filter and shipping_filter eps to beta

---

lib/project_types/script/cli.rb
lib/project_types/script/commands/push.rb
lib/project_types/script/graphql/get_app_scripts.graphql
lib/project_types/script/layers/domain/script_project.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/commands/push_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/tasks/ensure_env_test.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb

Closes https://github.com/Shopify/script-service/issues/2951
Closes https://github.com/Shopify/script-service/issues/2422
We want to be able to connect to an existing script that has been pushed to Shopify. 
- Adds a custom task to ensure the `.env` file filled with all required keys
- This task only prompts for the fields needed (`org` and `app`) instead of all fields (`shop`) like we used to prompt for.
- Adds a method to `ScriptService` infra service to fetch all scripts on a given app and extension point
- When prompting for `.env` values during push, all existing scripts for an api_key and extension point will be fetched. The user will be asked if they want to connect to one of these existing scripts, instead of creating a new one.

[scripts] Prompt user during push if they want to connect to an existing script

---

lib/shopify_cli.rb

There is an autoload for `ShopifyCli::Log`, but no such file `"shopify-cli/log"`. Nobody never uses the constant, so the autoload is never observed to fail.
Removing the broken and unused autoload.

Remove autoload for non-existent ShopifyCli::Log

---

lib/project_types/extension/cli.rb
lib/project_types/extension/commands/serve.rb
lib/project_types/extension/features/argo_renderer_package.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/features/argo_serve_options.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/specification_handlers/default.rb
lib/project_types/extension/tasks/choose_next_available_port.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/features/argo_test.rb
test/project_types/extension/tasks/argo_serve_options_test.rb
test/project_types/extension/tasks/choose_next_available_port_test.rb

⚠️ We're not going to release this change as is as it breaks backwards compatibility. Instead, this branch is going to be merged into `project/extension-serve` and followed up with PR that will introduce guards that probe whether the currently installed version of Argo Admin CLI already supports the new API, a.k.a provides support for `--port` and `--publicURL`.
---
Closes: https://github.com/Shopify/shopify-app-cli/issues/1174
* Moving argo serve options to its own class, as this logic continues to grow. This should make options more scalable and configurable.
* Adding a `tunnel` flag to `serve` command, passing down the flag to `argo_serve`
* If tunnel is true, a tunnel is created on either the argo default port, or the next available port if the default port is taken
* The tunnel URL …

feature: add tunnel option to ArgoServe

---

lib/project_types/extension/cli.rb
lib/project_types/extension/models/npm_package.rb
lib/project_types/extension/tasks/find_npm_packages.rb
test/project_types/extension/models/npm_package_test.rb
test/project_types/extension/tasks/find_npm_packages_test.rb

To simplify comparing NPM Packages.
Extracts `Extension::Tasks::FindNpmPackages::Package` into `Extension::Models::NpmPackage` and implements the [`Comparable`](https://docs.ruby-lang.org/en/2.5.0/Comparable.html) interface.

Models::NpmPackage

---

CHANGELOG.md
lib/project_types/extension/commands/tunnel.rb
test/project_types/extension/commands/tunnel_test.rb

While using `shopify tunnel` for the first time to test out a local shopify extension over HTTPS via an ngrok tunnel, I noticed an interesting difference in the output of the following commands:
* `shopify tunnel start` outputs an HTTPS URL
* `shopify tunnel status` outputs an HTTP URL
IMO, to offer a more secure user experience by default, we should always be outputting an HTTPS URL instead of HTTP whenever possible.
Before, the `shopify tunnel status` command would get all URLs for the ngrok tunnel and just return the first one. As of writing, ngrok returns the HTTP URL before the HTTPS one, so the HTTP URL would return first.
Now, I am using `Enumerable#find` to return the very first HTTPS URL. If none exists, then I fallback to existing behaviour (return the first available URL and …

Prioritizes returning an https url over http with 'shopify tunnel status'

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/ui/error_handler_test.rb

This PR updates the `ScriptRepushError` message to be more reflective of the multi-script changes.
Closes https://github.com/Shopify/script-service/issues/3053
This PR updates the text content shown to the user as well as the `ScriptRepushError` to take in a UUID instead of app key.

Update ScriptRepushError message

---

lib/project_types/script/layers/infrastructure/assemblyscript_project_creator.rb
lib/project_types/script/layers/infrastructure/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/rust_task_runner.rb
test/project_types/script/layers/infrastructure/assemblyscript_project_creator_test.rb
test/project_types/script/layers/infrastructure/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/rust_task_runner_test.rb

Closes https://github.com/Shopify/script-service/issues/3054
The filename of the generated WASM depends on the title of the script. In AS, this filename is hardcoded in the npm `build` script. So if a user changes the title of a script, everything blows up.
- Renames the wasm file to `script.wasm` instead of `<script-title>.wasm`
- Supports legacy naming so existing scripts that have the existing title hardcoded into npm `build` command will still function properly

[scripts] Update filename of generated wasm

---

CHANGELOG.md
lib/project_types/php/cli.rb
lib/project_types/php/commands/create.rb
lib/project_types/php/forms/create.rb
lib/project_types/php/messages/messages.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/php_deps.rb
lib/shopify_cli.rb
test/project_types/php/commands/create_test.rb
test/project_types/php/forms/create_test.rb
test/project_types/php/test_helper.rb

The first step in creating a new PHP app is actually cloning the repo. This PR adds the `create` command which is essentially the same as the node / rails ones, which clones the example repo and installs the composer dependencies so the app can run.
Adding a `create` command, that looks more or less like so:

Add php create command

---

lib/project_types/extension/commands/serve.rb
lib/project_types/extension/features/argo.rb
lib/project_types/extension/messages/messages.rb
lib/shopify-cli/tunnel.rb
test/project_types/extension/commands/serve_test.rb
test/shopify-cli/tunnel_test.rb

Part of https://github.com/Shopify/shopify-app-cli/pull/1191
`Extensions::Commands::Serve` needs to be able to start a tunnel from the serve command, and pass the URL the tunnel is running on to the underlying extension CLI.
~In order for us to be able to do this, we need to make sure there isn't a tunnel already running on the same port.~
If there is another tunnel already running, but on a different port, we should abort and let the user know, so the user can decide how they want to handle (stop the other tunnel if they choose).
This PR introduces a helper for `ShopifyCli::Tunnel` to check if there is already a tunnel running on a specific port.
Usage: `ShopifyCli::Tunnel.running_on?(8000)`. This returns a boolean value whether a tunnel is running on the given port.
PR also incorporates …

add running_on?(port) helper to ShopifyCli::Tunnel

---

CHANGELOG.md
lib/project_types/extension/models/specification_handlers/checkout_argo_extension.rb
test/project_types/extension/models/specification_handlers/checkout_argo_extension_test.rb

Fixes https://github.com/Shopify/checkout-web/issues/5087
For Unite, we need to allow Checkout Argo Extensions to specify metafields in their config file so that we can fetch them on the backend to return the proper metafields. For this reason, this PR is adding a new specification handle for Checkout Argo Extensions such that we merge the attributes they provided in their config file with the normal argo extensions configuration attributes. 
Adding a specification handler for `CheckoutArgoExtension` such that we can persist configuration attributes from the `extension.config.yml` when the extension is pushed. We currently accept two attributes for this file, namely:
- Extension points:
This will allow us to know which extension points an extension has chosen to extend
- Metafields: …

[Extensions] Add CheckoutArgoExtension specification handler

---

Gemfile.lock

Trying to fix issues with our deployment pipeline
Update bundler to 2.1.4 which is the default for Ruby 2.7

Bundler 2.1.4

---

CHANGELOG.md
lib/project_types/php/cli.rb
lib/project_types/php/commands/serve.rb
lib/project_types/php/messages/messages.rb
lib/shopify-cli/messages/messages.rb
lib/shopify-cli/process_supervision.rb
test/fixtures/app_types/php/.env
test/fixtures/app_types/php/.shopify-cli.yml
test/project_types/php/commands/serve_test.rb

Once PHP apps are created, we need to be able to serve them. This command needs to run both `npm run watch` and `php artisan serve`, once the ngrok tunnel is set up.
Adding a `serve` command for PHP projects which does all of the above.

Add PHP serve command

---

CHANGELOG.md
lib/project_types/php/cli.rb
lib/project_types/php/commands/connect.rb
lib/project_types/php/messages/messages.rb
test/project_types/php/commands/connect_test.rb

Adding a `Connector` for the PHP project type, which just runs the default connect command.

Add PHP connect command

---

CHANGELOG.md
lib/project_types/php/cli.rb
lib/project_types/php/commands/open.rb
lib/project_types/php/messages/messages.rb
test/project_types/php/commands/open_test.rb

Adding the `open` command for PHP apps, which just prints out the URL to access the local app while it's running with `serve`.

Add php open command

---

CHANGELOG.md
lib/project_types/php/cli.rb
lib/project_types/php/commands/deploy.rb
lib/project_types/php/commands/deploy/heroku.rb
lib/project_types/php/messages/messages.rb
lib/shopify-cli/heroku.rb
lib/shopify-cli/messages/messages.rb
test/project_types/php/commands/deploy/heroku_test.rb
test/project_types/php/commands/deploy_test.rb
test/project_types/php/commands/open_test.rb
test/test_helpers/heroku.rb

This PR adds a `deploy` command for PHP apps, and implements a `heroku` deploy target, which successfully deploys an app after it is modified to work around the PHP library not being public yet.

Add deploy command for PHP apps

---

.github/workflows/release.yml

The create_release workflow has been failing for a while. The latest round of failures come from the version of bundler having been updated to `2.1.4` but that version not being installed.
Adding a line to install the specific version of bundler being used.
**If there's a better way to do this, I'm open to it!**

fix: release workflow needs to update bundler version

---

lib/project_types/script/layers/infrastructure/errors.rb
test/project_types/script/layers/infrastructure/command_runner_test.rb

Closes https://github.com/Shopify/script-service/issues/3156
Some error messages within the build frame were being smothered instead of printing the relevant error.
Ensures that `SystemCallFailureError`s have a defined `message`. The build frame will try to print the error message, but since that class didn't have one defined, the class name was printed instead.
I double checked that other build errors did not have this problem.

[scripts] print script build error in frame

---

lib/project_types/extension/features/argo_runtime.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/models/specification_handlers/default.rb
test/project_types/extension/features/argo_runtime_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/tasks/argo_serve_options_test.rb

In preparation for GA of the new extension developer experience.
Removes the argo_admin_beta flag protection in ArgoServe.

Extensions/Serve: Remove ArgoAdminBeta Flag Protection

---

CHANGELOG.md
lib/project_types/extension/features/argo_runtime.rb
lib/project_types/extension/features/argo_serve_options.rb
test/project_types/extension/features/argo_runtime_test.rb
test/project_types/extension/tasks/argo_serve_options_test.rb

Closes https://github.com/Shopify/argo-private/issues/1575
`--name` needs to be passed along to `argo-admin-cli` when running `shopify serve` in an extension project.
BEFORE
AFTER
🎩 Tophatting
* `cd` into a product subscription extension project
* run `shopify serve`
* observe `--name` is being passed as an argument to the `argo-admin-cli` command
* `cd` into a checkout extension project
* run `shopify serve`
* observe the `--name` argument is not being passed to the `argo-run` command

fix: include name in list of args in extension serve

---

lib/project_types/script/commands/push.rb
lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/commands/push_test.rb
test/project_types/script/tasks/ensure_env_test.rb

Fixes https://github.com/Shopify/script-service/issues/3022
When a script is being connected to an app, we check if there are existing scripts on that app and if the user wants to overwrite any of them. If they select 'YES', but the push command was run without the --force flag, then the command fails. Since the user explicitly consented to overwriting, the --force flag should not be required.
Note that this is basically a temporary solution. Once the CLI DX changes are finalized, the app connection step will occur in another command and the `push` command will always require force. 
- Checks if the `EnsureEnv` task created a new env, and force the script push if it did. 
- If a valid env exists, this task will return false.
- If no env exists yet, then the user gets prompted. If scripts …

[scripts] do not require a force push if the the overwrite script prompt was answered

---

CHANGELOG.md
lib/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator_test.rb

If an extension point doesn't require the Scripts SDK, the CLI populates the package.json for new projects with an invalid value for the SDK dependency. Instead, the CLI should not include the SDK altogether if an extension point doesn't require it.
This PR conditionally includes the SDK in the built package.json file when creating a new script project.

[Fix] Include the Scripts SDK only if required for the extension point

---

CHANGELOG.md
lib/project_types/theme/commands/serve.rb
lib/shopify-cli/theme/dev_server.rb
test/shopify-cli/theme/dev_server/integration_test.rb

Issue reported by a partner:
```
Traceback (most recent call last):
[...]
3: from /Users/harryfrancis/.rvm/gems/ruby-2.7.2/gems/shopify-cli-2.0.0/lib/project_types/theme/commands/serve.rb:13:in `call'
2: from /Users/harryfrancis/.rvm/gems/ruby-2.7.2/gems/shopify-cli-2.0.0/lib/shopify-cli/theme/dev_server.rb:43:in `start'
1: from /Users/harryfrancis/.rvm/gems/ruby-2.7.2/gems/shopify-cli-2.0.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
/Users/harryfrancis/.rvm/gems/ruby-2.7.2/gems/shopify-cli-2.0.0/lib/shopify-cli/theme/dev_server.rb:49:in `block in start': undefined method `upload_theme_with_progress_bar!' for #<ShopifyCli::Theme::Syncer:0x00007fa3cd2f2b78> (NoMethodError)
```
Updating to the new API for using the upload progress bar.

Fix call to undefined method when running `theme serve`

---

CHANGELOG.md
lib/shopify-cli/api.rb

When running commands that make API calls, intermittent `uninitialized constant Net::WriteTimeout` errors occur. (Ruby version: `ruby 2.6.3p62`).
`Timeout::Error` is a parent of `Net::WriteTimeout` and `Net::ReadTimeout`, so just catching `Timeout::Error` instead of all its children fixes the issue for me.
If there's a better approach, I'm open to it! :)

only rescue Timeout::Error

---

CHANGELOG.md
lib/graphql/api_versions.graphql
lib/shopify-cli/admin_api.rb
lib/shopify-cli/api.rb
test/fixtures/api/versions.json
test/shopify-cli/api_test.rb

Fixes #1308
Previously, the latest API version was determined by looking for the displayName that had "Latest" in it - this only works when Partner account preferred language is English.
Now it's determined by reverse sorting the list of handles (ignoring "unstable") and picking the second on the list (the first will be the proposed version).

Change how latest api version is determined, fixes 1308

---

CHANGELOG.md
lib/shopify-cli/theme/dev_server/local_assets.rb
lib/shopify-cli/theme/syncer.rb
lib/shopify-cli/theme/theme.rb
test/shopify-cli/theme/syncer_test.rb
test/shopify-cli/theme/theme_test.rb

Theme files that have no checksums returned by the API were not pulled.
Remove the check that required a checksum to be present.
Also fix duplicated theme files being pull or pushed.

Fix `theme pull` no pulling files that have no remote checksum

---

lib/project_types/script/graphql/app_script_update_or_create.graphql

Fixes https://github.com/Shopify/script-service/issues/3380
`appScriptUpdateOrCreate` query fields `configurationDefinition`, `scriptJsonVersion` and `configurationUi` should not be nullable anymore.

changed graphql parameter field type to non-nullable

---

lib/shopify-cli/core/monorail.rb

Since theme projects do not use `.shopify-cli.yml` file, some monorail data is missing. This PR adds `project_type` and `partner_id` in.
What the monorail payload looks like now for theme commands:

Manually populate monorail data for theme commmands

---

README.md

Added link to [theme kit migration guide](THEMEKIT_MIGRATION.md) to `README.md`

Added link to theme kit migration guide

---

CHANGELOG.md
Gemfile.lock
lib/project_types/extension/cli.rb
lib/project_types/extension/commands/check.rb
lib/project_types/extension/messages/messages.rb
shopify-cli.gemspec

Allows theme app extension developers to run theme-check against their extension code by running `shopify extension check` in their project directory.
Fixes https://github.com/Shopify/shopify/issues/294975
Bumps the version of theme-check we need to 1.1.0, which includes support for Theme App Extensions
The check command checks for a few things:
* Does a .theme-check.yml file exist?
* Has the user specified a -C parameter on the command line?
If neither of these is true, then we add `-C :theme_app_extension` to the options we pass to theme check, so that the default behaviour is to use the built-in theme app extension configuration.
Initially I wanted to have this behaviour specified within the theme_app_extension specification handler. I couldn't figure out how to do this easily, since …

Add `extension check` command for checking theme app extensions

---

lib/project_types/extension/extension_project.rb
test/project_types/extension/extension_project_test.rb

Closes https://github.com/Shopify/shopify-cli/issues/1302
* Show an error to the end user letting them know they need to create an `.env` file by running `shopify extension connect` for commands that require env values.
* Create a new extension with `shopify extension create`
* `cd` into the project
* remove the env file with `rm .env`
* try running any extension command
* you should see the error alerting you to run `shopify extension connect`

handle missing env error

---

lib/project_types/extension/cli.rb
lib/project_types/extension/features/argo_runtime.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/features/runtimes/admin.rb
lib/project_types/extension/features/runtimes/base.rb
lib/project_types/extension/features/runtimes/checkout_post_purchase.rb
lib/project_types/extension/features/runtimes/checkout_ui_extension.rb
lib/project_types/extension/models/specification_handlers/default.rb
lib/project_types/extension/tasks/configure_features.rb
test/project_types/extension/features/argo_runtime_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/features/runtimes/admin_test.rb
test/project_types/extension/features/runtimes/checkout_post_purchase_test.rb
test/project_types/extension/features/runtimes/checkout_ui_extension_test.rb

Part of https://github.com/Shopify/ui-extensions-private/issues/1618
We need to pass the `--store` flag to the `checkout-extensions-ui-run` node process, but only for Checkout UI extensions, not for Post Purchase extensions.
In order to achieve the desired functionality, we have introduced various extension-specific runtimes:
* Admin
* CheckoutUiExtension
* CheckoutPostPurchase
as each one of these has very specific needs.
This PR introduces the extension-specific runtimes, and also adds the `shop` flag to extensions of type `CHECKOUT_UI_EXTENSION`.
* `cd` into a `PRODUCT_SUBSCRIPTION` extension
* run `shopify extension serve`
* observe serve behavior is unchanged
* `cd` into a `CHECKOUT_UI_EXTENSION` or `CHECKOUT_ARGO_EXTENSION` project
* run `shopify extension serve`
* observe behavior …

introduce extension runtimes

---

lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/features/runtimes/checkout_ui_extension.rb
test/project_types/extension/features/runtimes/checkout_ui_extension_test.rb

Part of https://github.com/Shopify/ui-extensions-private/issues/1618
* Adds the `--resourceUrl` flag to `ArgoServe` options if it is present.
🚨 NOTE 🚨 
A separate PR will dynamically pull this info for the end-user: https://github.com/Shopify/shopify-cli/pull/1377
In the meantime, an end-user could add `EXTENSION_RESOURCE_URL` to their extension `.env` file and the resource URL flag would be passed down to the node runtime.
We agreed to release this before the dynamically populated resource URL as an MVP.
* `cd` into a `CHECKOUT_UI_EXTENSION` project
* Open your `.env` file
* Add `EXTENSION_RESOURCE_URL` and add a variant id in this format: `cart/%VARIANT_ID%:1`. If you just want to test the flag, you can simply add `EXTENSION_RESOURCE_URL=/cart/1:1`
* You can find a variant ID by running …

adds resouce_url to argo_serve options

---

lib/project_types/extension/cli.rb
lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb

~We have to migrate existing early access partners using `CHECKOUT_ARGO_EXTENSION` before merging this PR.~
Fixes https://github.com/Shopify/argo-private/issues/1581
Now that the `checkout_argo_extension` type is not used anymore by partners and all early access partners have been migrated to the new `checkout_ui_extension` type, this PR is removing all references to the legacy type.
Cleaning up references to `checkout_argo_extension`.

[Checkout Extensibility] Cleanup checkout_argo_extension extension type

---

CHANGELOG.md
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/specification_handlers/theme_app_extension.rb

Theme app extensions don't yet support `extension serve`. Trying to run `shopify extension serve` in an theme app extension project outputs a stack trace and then errors out.
Fixes #1339
Output a better error when a user tries to run `shopify extension serve` for a theme app extension project.

Theme app extensions don't support the serve command

---

lib/project_types/theme/forms/select.rb

Fix the default colour for formatting the CLI output when the theme.role is not one of the common set.

[Fix] format colour selector when pushing to a theme

---

lib/graphql/get_variant_id.graphql
lib/project_types/extension/cli.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/product.rb
lib/project_types/extension/tasks/converters/product_converter.rb
lib/project_types/extension/tasks/get_product.rb
test/project_types/extension/tasks/converters/product_converter_test.rb
test/project_types/extension/tasks/get_product_test.rb

Closes: https://github.com/Shopify/ui-extensions-private/issues/1619
* Add task get_product to fetch products for a given shop from the Admin API
* Add Product model (`Product.new(variant_id, quantity)`)
* Add ProductConverter
```
{
"data" => {
"products" => {
"edges" => [
{
"node" => {
"id" => "gid://shopify/Product/SOME_PRODUCT_ID",
"variants" => {
"edges" => [
{
"node" => {
"id" => "gid://shopify/ProductVariant/SOME_VARIANT_ID",
},
},
],
},
},
},
],
},
},
}
```
1. Ensure you are authenticated to the CLI with a store. `shopify login --store=YOUR_SHOP_DOMAIN_HERE`
2. If you don't have any products in your dev shop, run `shopify populate products`. If this call fails, you are not authenticated to the CLI correctly, and you will not be able to run the call. See _Known Issues_ for possible …

add get_product task and ProductConverter

---

CHANGELOG.md
lib/shopify-cli/core/monorail.rb
test/shopify-cli/core/monorail_test.rb

Allows for Shopify CLI to be used within GitHub actions and other CI systems without prompting the user for consent.
Checking if it's in a CI environment and bypassing analytics and the prompt.

Remove analytics prompt when used in CI

---

CHANGELOG.md
lib/project_types/extension/extension_project.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb
lib/project_types/extension/models/specification_handlers/default.rb
lib/project_types/extension/tasks/configure_features.rb
test/project_types/extension/extension_project_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/models/specification_handlers/checkout_ui_extension_test.rb

When running `shopify extension serve` in a Checkout UI Extensions context, the CLI will now automatically configure the `EXTENSION_RESOURCE_URL` variable and pass its value as `--resourceURL` to the Node.js runtime.
Closes #1634
- Expands the SpecificationHandler API: `SpecificationHandlers::Default#build_resource_url`
- Implements automatic resource URL generation for checkout UI extensions
- Adds `ExtensionProject.update_env_file` for updating individual environment variables
- Persists generated resource URLs in the .env file to avoid future API requests

Auto configure resource URL for Checkout Extensions

---

CHANGELOG.md
lib/project_types/extension/commands/serve.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/features/runtimes/admin.rb
lib/project_types/extension/models/specification_handlers/default.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/features/runtimes/admin_test.rb

Closes https://github.com/Shopify/ui-extensions-private/issues/1625
Admin UI Extensions have always supported a `--resourceUrl` to be passed to the node runtime.
This PR adds the ability for a user to provide a `--resourceUrl` via the `shopify extension serve` command.
**For Admin extensions**
* If `--resourceUrl` is provided, it is passed to the node runtime. If not, nothing is passed.
* `EXTENSION_RESOURCE_URL` is not persisted in the .env file
**For Checkout UI extensions**
* If `--resourceUrl` is provided, it is passed to the node runtime. If not, the `EXTENSION_RESOURCE_URL` in the `.env` file is used, if one is available
* `EXTENSION_RESOURCE_URL` is not overwritten by the user provided `--resourceUrl`
**For Post Purchase extensions**
* `--resourceUrl` is ignored if provided, as it …

add resource_url flag to extension serve

---

CHANGELOG.md
lib/project_types/extension/commands/push.rb
lib/project_types/extension/features/argo.rb
lib/project_types/extension/models/specification_handlers/checkout_post_purchase.rb

Fixes an issue that prevents partners from pushing their extension.
Changes the way we determine the renderer package version. Before, `Argo` would try to guess the appropriate renderer package but fail if an extension is using more than one package, which is the case for Post Purchase extension. However, specification handlers already state their renderer package. This PR removes guessing the renderer package name and uses the information from the specification handler as source of truth.
I've 🎩 the changes and everything is working well now.

New method for determining renderer package name

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

Post Purchase extensions are broken in 2.2.0
Prepares a new version that includes the fix.

Release v2.2.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

Introduces new client-side upload for uploading Scripts to GCS.
Related PR: https://github.com/Shopify/shopify-cli/pull/1382
Bumping the version to 2.2.2.

Packaging for release v2.2.2

---

lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb
test/project_types/extension/models/specification_handlers/checkout_ui_extension_test.rb

Fixes https://github.com/Shopify/checkout-web/issues/6020
We want to allow partners to provide us with a merchant facing name for their extension that will be surfaced in the editor and used by the merchant to identify the extension. Right now, we are using a default one through the template if partners don't change it, but we are thinking an iteration of that would be to prompt partners on the CLI to specify one so it does not confuse merchants and enforcing the name as the same time.
Simply adding `name` as a configuration field for the extension.

[Checkout UI Extensions] Accept extension name in config file 

---

CHANGELOG.md
lib/shopify-cli/theme/file.rb
lib/shopify-cli/theme/syncer.rb
test/shopify-cli/theme/theme_test.rb

Binary files where not opened in binary mode when read. This broke encoding under Windows. But worked fine under *nix.
Fixes #1401 
Ensure all non-text (binary) theme files are opened in binary mode (`b`) before writing or reading.
Tested under Windows.

Fix uploading of binary theme files under Windows

---

CHANGELOG.md
lib/shopify-cli/theme/dev_server/header_hash.rb
lib/shopify-cli/theme/dev_server/proxy.rb
test/shopify-cli/theme/dev_server/proxy_test.rb

Fixes https://community.shopify.com/c/Online-Store-2-0/Unable-to-log-into-customer-account-when-using-shopify-theme/m-p/1289042
`theme serve` didn't work on /account pages because logging in as a customer created a new _secure_session_id cookie, and we didn't updated it in `Proxy`. Only when it expired.
Renew our `_secure_session_id` cookie when getting a new one from a proxy response during `theme serve`.

Renew `_secure_session_id` cookie on proxy response during `theme serve`

---

CHANGELOG.md
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/commands/push.rb
lib/shopify-cli/theme/ignore_filter.rb
test/project_types/theme/commands/pull_test.rb
test/project_types/theme/commands/push_test.rb
test/shopify-cli/theme/ignore_filter_test.rb

It's impossible to ignore some theme files per command. A common pattern is to ignore config/ files.
Fixes #1430 
Add an `--ignore` (shorthand `-x`) option to `shopify theme push` and `shopify theme pull` to add patterns to ignore. Same format as https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli.
Ex.:
```
shopify theme push --ignore "config/*.json"
```
The ignore option is merged with any pattern defined in `.shopifyignore`

Add `theme push` & `pull` option to ignore files

---

CHANGELOG.md
Gemfile.lock
lib/shopify-cli/version.rb

I'm releasing a new version of the `shopify-cli`, 2.3.0.

Release 2.3.0

---

lib/project_types/script/cli.rb
lib/project_types/script/layers/infrastructure/api_clients.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/infrastructure/script_service_test.rb

Continuing refactors from https://github.com/Shopify/shopify-cli/pull/1471. Separates the API related code from `ScriptService` to focus `ScriptService` purely on querying the backend script-service.
Moved both `PartnersProxyAPI` and `ScriptServiceAPI` into a new class: `ApiClients`. This will expose a single method for returning the "default" API client, making this decision opaque to `ScriptService`.

Moved PartnersProxyAPI and ScriptServiceAPI out of ScriptService and into ApiClients

---

lib/project_types/script/cli.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/layers/infrastructure/script_uploader.rb
lib/project_types/script/tasks/ensure_env.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/layers/infrastructure/script_uploader_test.rb
test/project_types/script/tasks/ensure_env_test.rb

Continues https://github.com/Shopify/shopify-cli/pull/1499.
Further clean up `ScriptService`, focusing it just on interacting with the backend script-service.
Moved `UploadScript` out of `ScriptService` and into `ScriptUploader`. `MakeRequest` has been dissolved into `ScriptService` and a new `generate_module_upload_url` was added for `ScriptUploader` to use instead of relying on `MakeRequest`.
`ScriptService#push` was changed to `ScriptService#set_app_script` to better reflect the web API it was built against. All of the upload and script set orchestration was moved to `PushScript` (this includes removing the delegated call to `ScriptService` in `PushPackage`).

Pulled UploadScript out of ScriptService with additional cleanup

---

.github/workflows/shopify.yml
Dockerfile
Rakefile
dev.yml
lib/project_types/extension/tasks/choose_next_available_port.rb
lib/shopify-cli/git.rb
test/shopify-cli/git_test.rb
test/shopify-cli/theme/dev_server/integration_test.rb
test/test_helper.rb

I noticed there's some room for improvement in our CI pipeline so here's a PR improving the things listed in the section below.
- I separated the `rake test` and `rake rubocop` commands. That way we can see the results independently on GitHub's UI.
- I configured Rubocop's step to only run in an os because the step is OS-agnostic.
- Extended the test job to run on macOS 11 and Ubuntu 16.04, 18.04, and 20.04
- Replaced Ruby 3.0.0 with 3.0.2.
- Set it up to cancel previous runs when new commits are pushed.
- Adjusted `on` to run on pushes only when the branch is `main`.

CI pipeline improvements

---

lib/project_types/script/layers/application/push_script.rb

…
Parameter was never removed from call site when signature changed.
Making it not 💥

Removed extraneous parameter from call to set_app_script from push_script

---

lib/project_types/extension/cli.rb
lib/project_types/extension/models/server_config/base.rb
lib/project_types/extension/models/server_config/development.rb
lib/project_types/extension/models/server_config/development_entries.rb
lib/project_types/extension/models/server_config/development_renderer.rb
lib/project_types/extension/models/server_config/extension.rb
lib/project_types/extension/models/server_config/root.rb
lib/project_types/extension/models/server_config/user.rb
test/project_types/extension/models/server_config/development_entries_test.rb
test/project_types/extension/models/server_config/development_renderer_test.rb
test/project_types/extension/models/server_config/development_test.rb
test/project_types/extension/models/server_config/extension_test.rb
test/project_types/extension/models/server_config/root_test.rb
test/project_types/extension/models/server_config/user_test.rb

Part of: https://github.com/Shopify/shopify-cli-extensions/issues/4
* Adds `Shopifile` model, which holds the configuration necessary for the new extensions development server
* Adds other models necessary to assemble the data the new extension server needs:
* Config::Extension
* Config::User
* Config::Development
* Config::DevelopmentSettings::Renderer
* Config::DevelopmentSettings::Entries 
This will generate YAML on the fly, which we can pass to the extensions server binary. YAML output:
```
port: 39351
extensions:
uuid: 00000000-0000-0000-0000-000000000000
type: checkout-ui-extension
user:
metafields: []
development:
build_dir: test
root_dir: test
template: javascript
renderer:
name: "@shopify/checkout-ui-extensions"
entries:
main: src/index.js
```
- ~[ ] I've added a CHANGELOG entry …

add ServerConfig module, classes

---

lib/project_types/extension/models/development_server.rb

Part of https://github.com/Shopify/shopify-cli-extensions/issues/4
* Introduce a wrapper for interfacing with the Go Development Server (ES6 extensions server)

add development server

---

lib/project_types/rails/commands/create.rb
lib/project_types/script/layers/infrastructure/api_clients.rb
lib/shopify-cli/constants.rb
lib/shopify-cli/environment.rb
lib/shopify-cli/identity_auth.rb
test/shopify-cli/environment_test.rb

Adding configurations so that script service and login work properly with spin
Fixes #(https://github.com/Shopify/script-service/issues/3593)
We are expanding the spin constellation for script service to include partners and identity so that we have a full end to end environment for quicker and easier testing and closer to production feel. This will eliminate a number of the stubbed services within the script service constellation.
The change add configurations to enable spin communication with the CLI. Similar to the communication for the local environment. It also uses some environment variables to configure a users spin URL and derivces services based off of these configurations.
The ENV variables are as follows:
SHOPIFY_APP_CLI_SPIN_PARTNERS: used to enable spin partner communication, …

Adding configurations so that script service and login work with spin

---

lib/project_types/script/layers/infrastructure/api_clients.rb

Makes the abstraction within `Scripts::Layers::Infrastructure::ApiClients` more obvious, and differentiating their names from other API classes.
Renames `ScriptServiceAPI` to `ScriptServiceApiClient` and `PartnersProxyAPI` to `PartnersProxyApiClient`.
`ScriptServiceApiClient` no longer inherits from `ShopifyCli::API`, but instead instantiates it and delegates to it. This means the contract no longer has to conform to `ShopifyCli::API`'s.

Make ScriptServiceAPI and PartnersProxyAPI more consistent

---

lib/project_types/script/ui/error_handler.rb
test/project_types/script/ui/error_handler_test.rb

If a user tries to create a script with an invalid api (like running `shopify script create --extension-point=invalid`), then we would print an error showing the APIs they can use, even if they are deprecated or not. This shouldn't happen, we should only show them the APIs that are fully supported right now.
Only prints the fully supported API types a user can use.

Stop showing deprecated and beta script apis in help messages

---

lib/shopify-cli/theme/dev_server/hot_reload.rb
test/shopify-cli/theme/dev_server/hot_reload_test.rb

Fixes: https://github.com/Shopify/shopify-cli/issues/1526
As reported [here](https://github.com/Shopify/shopify-cli/issues/1526), hot-reloading of themes caused errors on the Javascript console when an ignored file was modified.
It turns out the logic on the Javascript side assumed the notifications always contained a file. I modified the logic on the Ruby side to not notify when the list of files is empty (after filtering out the ignored files).

Don't notify when the list of files is empty

---

lib/project_types/extension/cli.rb
lib/project_types/extension/commands/build.rb
lib/project_types/extension/commands/create.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/development_server.rb
lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/server_config/development.rb
lib/project_types/extension/tasks/run_extension_command.rb
test/project_types/extension/commands/build_test.rb

Closes https://github.com/Shopify/shopify-cli-extensions/issues/80
Part of https://github.com/Shopify/shopify-cli-extensions/issues/4
* Introduce new build flow into `extension build` command:
* if `extension_server_beta` is enabled, user will be taken to new flow, which uses the go development server to run the build command
* else user is directed to existing flow
Added:
* `DevelopmentServerRequirements` model to centralize this check
* Fixed path to `shopify-extension` executable
* Made `template`, `root_dir`, and `entries` optional fields in `ServerConfig::Development` to allow us to run the `build` command without a persisted "shopifile".
🎩 Tophatting:
* clone the `shopify-cli-extensions` repo
* cd into `shopify-cli-extensions` if you're not already there
* run `make build`, this …

new extension build flow

---

lib/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator_test.rb

If `npm` gives a warning or a notice for whatever reason (like there is a new version available), an error will be raised when fetching the API version because we run `npm show` and JSON parse the output, but the `npm` notice makes the output invalid JSON.
Instead of running `npm show ...`, run `npm -s show` which will run the command in silent mode.

Silence npm warnings when determining the version of a script API

---

lib/project_types/script/layers/infrastructure/api_clients.rb

The `api_key` no longer needs to be passed into the `ShopifyCli::API` constructor as `ScriptServiceApiClient` is no longer inheriting from that class.
Removed `api_key` from the parameter list when creating `ShopifyCli::API`

Removed api_key when instantiating ShopifyCli::API

---

dev.yml

To run rubocop, you currently have to run the command every time. It would save a small amount of time if we could just run `dev style`.
Adds a `style` command to `dev.yml` that runs rubocop.

Add dev style command

---

.github/workflows/shopify.yml

Followup to: https://github.com/Shopify/shopify-cli/pull/1554

remove `ubuntu-16.04` from acceptance tests

---

lib/project_types/extension/commands/create.rb
lib/project_types/extension/features/argo_serve.rb
lib/project_types/extension/models/development_server.rb
lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/specification_handlers/default.rb
lib/project_types/extension/tasks/run_extension_command.rb
test/project_types/extension/commands/build_test.rb
test/project_types/extension/models/development_server_test.rb

Part of https://github.com/Shopify/shopify-cli-extensions/issues/4
Closes: https://github.com/Shopify/shopify-cli-extensions/issues/89
* Modifies `shopify extension create` for new extensions built with the new development server so that an `.env` file is created. An `.env` file is needed to check for `shop` and some other values needed to run `serve`.
* Adds `serve` support to `Extension::Tasks::RunExtensionCommand`
* Adds `serve` support to `Models::DevelopmentServer`
* opens threads to keep track of changes
* clone the shopify-cli-extensions repo
* cd into shopify-cli-extensions if you're not already there
* run make build, this will create an executable for you
* run cp shopify-extensions /Users/%YOUR_USER%/src/github.com/Shopify/shopify-cli/ext/shopify-extensions/shopify-extensions …

integrate shopify-extensions serve into argo-serve

---

CHANGELOG.md
lib/project_types/extension/features/argo.rb
lib/project_types/extension/tasks/find_npm_packages.rb
test/project_types/extension/tasks/find_npm_packages_test.rb

Fixes issue with multiple package versions being returned in npm list | yarn list when different versions of the same package are installed:
```ruby
[#<struct Extension::Models::NpmPackage name="@shopify/post-purchase-ui-extensions", version="0.10.1">,
#<struct Extension::Models::NpmPackage name="@shopify/post-purchase-ui-extensions", version="0.11.0">]
```
Instead of using `depth=1` to list dependencies, we will use `depth=0` so we don't return dev dependencies.

use depth 0 for list commands

---

packaging/homebrew/shopify-cli.base.rb

The recent typo fix on `ShopifyCli` broke the Homebrew formula that we generate because Homebrew expects the name to be `ShopifyCli`. 
This PR fixes the template that we use for generating the formula.

Fix the Homebrew formula name

---

Gemfile.lock

`bundle install` was crashing with:
> Downloading theme-check-1.7.2 revealed dependencies not in the API or the lockfile (parser (~> 3)).
> Either installing with `--full-index` or running `bundle update theme-check` should fix the problem
I ran `bundle update theme-check` which updated Gemfile.lock.

Fix `bundle install` crashing

---

lib/shopify_cli/method_object.rb

Fixes warnings in the test suite such as:
test/shopify-cli/transform_data_structure_test.rb:94: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
lib/shopify_cli/method_object.rb:55: warning: The called method `call' is defined here
This is the suggested way as per this news entry on Ruby's website:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation
Applying `ruby2_keywords` patch as-is broke Ruby 2.6: we ended up
calling methods with an extra argument. Not exactly sure I get the
subtleties, but Ruby 2.6 kwargs is misbehaving:
```ruby
#! /opt/rubies/2.6.6/bin/ruby
def one_argument(arg1)
end
def delegate(*args, &block)
one_argument(*args, &block)
end
kwargs …
```

Fix ruby 2 keywords delegation warning

---

CHANGELOG.md
bin/shopify

Hide unnecessary load error on loading ${RUBY_MAJOR}/ffi_c. Partially fix #1405

Hide LoadError for 2.7/ffi_c

---

README.md

To initialize a new theme, the correct command is `shopify theme init`

(README.md) shopify theme init, not create

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a hotfix version to include [this fix](https://github.com/Shopify/shopify-cli/pull/1608). Otherwise, we won't get errors reported in 2.6.0

Release 2.6.1

---

Gemfile.lock
shopify-cli.gemspec

I was looking at the `.gemspec` and I realized that we are explicitly avoiding pinning a version of `theme-check`. This is not ideal because two users installing the CLI might get different versions of `theme-check` and thus non-deterministic results that might confuse them and make our debugging experience more cumbersome. 
With the goal of ensuring a **deterministic** experience for users, and **easing the debugging of bugs** on our side, I'm binding the version of the CLI to a version of theme-check. I'm aware this means theme-check updates need to adhere to the [CLI](https://development-lifecycle.docs.shopify.io/releasing) schedule, which should be frequent enough (bi-weekly) for users to get improvements. If there's a serious bug on theme-check that requires an off-schedule release, …

Pin the exact theme-check version

---

CHANGELOG.md
Gemfile
Gemfile.lock
Rakefile
features/reporting.feature
features/step_definitions/commands/reporting.rb
features/step_definitions/commands/script.rb
features/step_definitions/commands/theme.rb
features/step_definitions/commands/version.rb
features/step_definitions/shared/docker.rb
features/support/process.rb
lib/shopify_cli.rb
lib/shopify_cli/commands.rb
lib/shopify_cli/commands/reporting.rb
lib/shopify_cli/core/monorail.rb
lib/shopify_cli/environment.rb
lib/shopify_cli/exception_reporter.rb
lib/shopify_cli/messages/messages.rb
lib/shopify_cli/reporting_configuration_controller.rb
lib/shopify_cli/services.rb
lib/shopify_cli/services/base_service.rb
lib/shopify_cli/services/reporting_service.rb
test/shopify-cli/core/monorail_test.rb
test/shopify-cli/reporting_configuration_controller_test.rb
test/shopify-cli/services/reporting_service_test.rb
utilities/docker.rb
utilities/docker/container.rb

Fixes https://github.com/Shopify/shopify-cli-planning/issues/56
As agreed [in this issue](https://github.com/Shopify/shopify-cli-planning/issues/56), we'd like to give users an interface to enable/disable usage reporting. @MeredithCastile suggested introducing a new command, `reporting on/off` for that.
- Add `reporting off/on` command.
- Add a unit tests that test the command's business logic in isolation.
- Add an acceptance test that tests the command e2e ensuring the right data is persisted.
1. Delete `~/.config/shopify/config`.
2. Run `bin/shopify reporting on`
3. The content of the file should be `~/.config/shopify/config`:
```
[analytics]
enabled = true
```
4. Fake an error from whoami by adding `raise "error"`
5. Run `bin/shopify whoami`.
6. The CLI shouldn't prompt you on what to …

Add "reporting on/off" command to enable/disable automatic usage reporting

---

lib/project_types/script/messages/messages.rb

Script enabling/disabling has been removed, but some messages were
left behind. This commit fixes that.
Fixes Shopify/script-service#3836

Cleanup unreferenced messages

---

lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb

Fixes https://github.com/Shopify/script-service/issues/3852
It appears that sometimes, `npm list --json` returns a non-zero status code, even though the parts of the command that we care about are returned. This PR makes it so that we handle this case.
https://github.com/Shopify/shopify-cli/blob/9e51e44dfcb9dbc4c43b0cb6a060974e70533569/lib/project_types/script/layers/infrastructure/command_runner.rb#L13-L13
You can reproduce this error by editing the above command runner line to either:
- change nothing: works as expected
- comment out the `unless success` end of line: effectively reproduces the issue in https://github.com/Shopify/script-service/issues/3852
- change `out: out.chomp` to any other value: this should catch other errors where the values we seek were not actually returned. I …

Handle `npm list` non-zero exit status

---

lib/project_types/extension/commands/create.rb
lib/project_types/extension/forms/create.rb
lib/project_types/extension/forms/questions/ask_template.rb
test/project_types/extension/forms/create_test.rb
test/project_types/extension/forms/questions/ask_template_test.rb

Closes: https://github.com/Shopify/shopify-cli-extensions/issues/86
Adding support for `--template` flag for new extensions using the new go executable. The go executable needs to know which template to use when creating a new extension. 
Currently we show a list to the end-user to select an option, but we would like to support passing in a `--template` flag as well.
1. Enable extension server beta: `shopify config feature extension_server_beta --enable`
2. `dev clone shopify-cli-extensions`
3. Run `make build` to generate a build
4. Copy the generated binary into the correct folder in your local shopify-cli repo: `shopify-cli/ext/shopify-extensions`
5. In a separate terminal / directory, now run `shopify create extension --type=CHECKOUT_UI_EXTENSION --template=javascript`
* other …

[new extensions only] add template flag to extension create

---

CHANGELOG.md
lib/project_types/extension/cli.rb
lib/project_types/extension/features/argo.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/tasks/find_package_from_json.rb
test/project_types/extension/features/argo_serve_test.rb
test/project_types/extension/features/argo_test.rb
test/project_types/extension/tasks/find_package_from_json_test.rb

Fixes https://github.com/Shopify/shopify-cli/issues/1683
Instead of running `npm | yarn list` to find the `renderer_package` version that is needed for the extension to run, parse the `package.json` file and get the version from there.
Pros: 
* This reduces code complexity as we no longer have to make a JS call to find the renderer version
* Reduces issues when there are multiple versions of a dependency when running `npm | yarn list`
* There is a known bug with the `list` command on earlier versions of Node, and not having to run the command would eliminate said bug
* Run `shopify extension serve`, `shopify extension register` and `shopify extension push` on a `PRODUCT_SUBSCRIPTION` extension
**Product Subscription**
**Checkout UI**
**Post Purchase**
N/A

parse package.json instead of running npm|yarn list

---

lib/project_types/extension/commands/create.rb
lib/project_types/extension/forms/questions/ask_template.rb
lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/server_config/development_renderer.rb
lib/project_types/extension/tasks/run_extension_command.rb
test/project_types/extension/models/server_config/extension_test.rb

Closes https://github.com/Shopify/shopify-cli-extensions/issues/140
Adds support of new extensions development server for `CHECKOUT_POST_PURCHASE` and `PRODUCT_SUBSCRIPTION` extensions.
* within the `shopify-cli` repo, run `rake extensions:install`
* give yourself the required beta flag: `shopify config feature extension_server_beta --enable`
**Product Subscription extensions:**
* run `shopify extension create --type=PRODUCT_SUBSCRIPTION`
* cd into your new extension
* run `yarn install`
* run `shopify extension build`
* run `shopify extension serve`
You should see this output
**Post Purchase extensions:**
* run `shopify extension create --type=CHECKOUT_POST_PURCHASE`
* cd into your new extension
* run `yarn install`
* run `shopify extension build`
* run `shopify extension serve`
You …

dev server support all argo extension types

---

lib/project_types/extension/cli.rb
lib/project_types/extension/models/server_config/app.rb
lib/project_types/extension/models/server_config/development.rb
lib/project_types/extension/models/server_config/extension.rb
lib/project_types/extension/models/server_config/root.rb
lib/project_types/extension/tasks/converters/server_config_converter.rb
lib/project_types/extension/tasks/merge_server_config.rb
lib/project_types/extension/tasks/run_extension_command.rb
test/project_types/extension/tasks/converters/server_config_converter_test.rb

Fixes #0000 
* Adds `ServerConfig::App`
* Adds `version` to `ServerConfig::Extension`
* Parses api key from .env and version from renderer package, and merges that into the `ServerConfig`
* within the shopify-cli repo, run rake extensions:install
* give yourself the required beta flag: shopify config feature extension_server_beta --enable
* cd into an extension project
* [CHECKOUT_UI_EXTENSIONS only] run echo "EXTENSION_RESOURCE_URL=/cart/1:1" >> .env in the extension project (this bypasses the call to the AdminAPI to fetch product data to build the resource_url, as this call is intermittently failing for some users)
* run shopify extension serve
You should see similar output to this:
~- [ ] I've added a CHANGELOG entry for this PR (if the change is public-facing)~ not user facing yet

add api_key and version to extensions server_config

---

CHANGELOG.md
lib/project_types/theme/commands/serve.rb
lib/project_types/theme/messages/messages.rb
lib/shopify_cli/theme/dev_server.rb
test/project_types/theme/commands/serve_test.rb

Related: https://github.com/Shopify/shopify-cli/pull/1609
I'm doing some follow-up work after @tyler-eon's [contribution ](https://github.com/Shopify/shopify-cli/pull/1609).
- Rename the argument from `--bind` to `--http-bind`.
- Added some logic to detect the error and suggest the user to use the `--http-bind` option.
Testing this is a bit tricky because it requires having a network interface that doesn't support binding to 127.0.0.1. For example, a Docker environment that contains a theme project with the CLI in it.

"theme serve --http-bind" follow-up work

---

.github/DESIGN.md

Fix a typo in the `.github/DESIGN.md` document.
To fix a typo in the `.github/DESIGN.md` document.
Replacing "requre" with "require"
Check the `.github/DESIGN.md` document.
None.

Fix typo 'requre' ~> 'require' (`.github/DESIGN.md`)

---

lib/project_types/extension/commands/build.rb
lib/project_types/extension/tasks/convert_server_config.rb
lib/project_types/extension/tasks/run_extension_command.rb
test/project_types/extension/commands/build_test.rb
test/project_types/extension/tasks/run_extension_command_test.rb

Ensure extensions can be build using the new extension development server.
Make RunExtensionCommand#context a required property to ensure that the context is allways passed down the stack.;
Build an extension with the new extension development server and see it succeed (as opposed to fail before)

Ensure RunExtensionCommand receives context

---

lib/project_types/script/cli.rb
lib/project_types/script/commands/javy.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/commands/javy_test.rb

Part of https://github.com/Shopify/script-service/issues/3718
Adds a `script javy` command to support wrapping the Javy executable. This will be a hidden command, so it won't be visible in the help (there is currently a bug in the core code though, so I'll open another PR to fix that). 
1. Ensure you have Javy installed by running `rake scripts:javy:install` in the CLI root.
2. Create a typescript project
2. Compile your TS to JS
3. run  `shopify script javy --in build/index.js --out build/index.wasm`. A new file should be created at `build/index.wasm`.

Add javy command

---

.gitignore
ext/javy/javy.rb
test/ext/javy/javy_test.rb

Part of Shopify/script-service#3718
We want Javy to be installed automatically at some point, but not at CLI installation because they might not use it.
Before the `shopify script javy` command is run, we perform an automatic check that Javy is installed. If the version is up to date, we do nothing. If it is out of date or not installed, we install the binary. 
To check the version of javy, I opted to store the version in the executable filename. This way, we can easily see if the version is out of date. 
- Create a typescript script
1. Check that Javy is installed by default
- Delete your javy installation at `shopify-cli/ext/javy/bin/*`
- Run `shopify script javy --in build/index.js --out build/index.wasm` inside your script project. The command should succeed and a new javy executable …

install javy binary on build

---

lib/project_types/script/commands/javy.rb

This PR https://github.com/Shopify/shopify-cli/pull/1650 moved the `SubCommand` class under `Command::SubCommand`. The PRs adding the Javy command https://github.com/Shopify/shopify-cli/pull/1675 did not have this change, so CI started to fail when the PR merged 💥 
Updates the reference of `SubCommand` to `Command::SubCommand`.
Run `dev test`

Backport SubCommand nesting change to javy command

---

CHANGELOG.md
lib/project_types/theme/messages/messages.rb
lib/shopify_cli/theme/dev_server.rb
test/shopify-cli/theme/dev_server/integration_test.rb

Fix the `theme serve` service by rescuing the `Errno::EADDRINUSE` and showing a more friendly message for users (issue: https://github.com/Shopify/shopify-cli/issues/1620).
Before this change, `Errno::EADDRINUSE` was not being handled and the standard error was appearing for users.
Now, this PR handles the `Errno::EADDRINUSE` error, and shows a more friendly message for users.
1. Run `shopify theme serve` service
2. Open another Terminal window
3. Run the `shopify theme serve` again
Here's the previous behavior:
Here's how it actual behavior (with this PR applied):
None.

Fix `theme serve` failing when the port is already being used

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

It includes the next fixes:
* [#1722](https://github.com/Shopify/shopify-cli/pull/1722): Fix `theme serve` failing when the port is already being used
* [#1751](https://github.com/Shopify/shopify-cli/pull/1751): A bug in the app creation flow that caused the CLI to abort when the form validation failed.
* [#1750](https://github.com/Shopify/shopify-cli/pull/1750): Runtime errors in Windows' environments when the `PATHEXT` environment variable is not defined. 
* [#1758](https://github.com/Shopify/shopify-cli/pull/1758): Fix tunnel creation for expired anonymous tunnels

Release 2.7.1

---

lib/project_types/extension/commands/build.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/development_server.rb
test/project_types/extension/models/development_server_test.rb

To provide more information during `shopify extension build`. Instead of using generic messages to report the build status, we now output the messages returned from ESBuild.
The new error and success messages look as follows.
**Error case**
**Success case**
1. Enable the development server beta
```
shopify config feature extension_server_beta --enable
```
2. Create a new extension
```
shopify extension create
```
3. Run extension build and observe the new output
```
shopify extension build
```

Improved extension build output

---

CHANGELOG.md
lib/shopify_cli/services/app/serve/node_service.rb
lib/shopify_cli/services/app/serve/rails_service.rb
lib/shopify_cli/version.rb
test/shopify-cli/services/app/serve/node_service_test.rb
test/shopify-cli/services/app/serve/php_service_test.rb
test/shopify-cli/services/app/serve/rails_service_test.rb

After version 2.7.0, we no longer can use a custom port for `ngrok` tunnel. Seem like there was a missing parameter in the `node_service.rb`
Add the `port` parameter to the tunnel start function.
For Node.js project, assume you want to tunnel the `localhost:3000`. 
This command should work: `shopify app serve --PORT 3000`

Fix: Tunnel --PORT parameter not working in Node.js app.

---

CHANGELOG.md
lib/project_types/theme/commands/serve.rb
lib/shopify_cli/theme/dev_server.rb
test/project_types/theme/commands/serve_test.rb

Fix `theme serve` failing with the `--host` property (https://github.com/Shopify/shopify-cli/issues/1765) by renaming the parameters from `http_bind` to `host`.
This was failing because we were calling `DevServer#start` in the `theme/commands/serve.rb` file with the `**flags` and the names were different.
This PR renames parameters from `http_bind` to `host`.
```
shopify theme serve --host=0.0.0.0
```
Here's the previous behavior:
Here's how it actual behavior (with this PR applied):

Fix `theme serve` failing with the `--host` property

---

CHANGELOG.md
lib/shopify_cli/context.rb
lib/shopify_cli/theme/syncer/error_reporter.rb
test/shopify-cli/context_test.rb
test/shopify-cli/theme/syncer/error_reporter_test.rb
test/shopify-cli/theme/syncer_test.rb

This PR is the second (and final) part of the https://github.com/Shopify/shopify-cli/issues/1353 fix.
When users perform a `theme push --development --json` operation and get errors, only the JSON should be outputted to STDOUT, and the errors should be outputted to STDERR. Thus, users can build scripts on top of `theme push` operations.
These changes improve the `ShopifyCLI::Theme::Syncer::ErrorReporter` to output the errors at the STDERR level.
This PR introduces the `ShopifyCLI::Context#error` method, a wrapper around `$stderr.puts`. Which is similar to the `ShopifyCLI::Context#puts` that wraps `Kernel#puts`/`$stdout.puts`.
The `ShopifyCLI::Theme::Syncer::ErrorReporter` uses that to report errors at the STDERR level.
Run the following command to get the `preview_url`:
```
shopify theme …
```

Fix `theme push --development --json` to output errors in the STDERR

---

CHANGELOG.md
lib/shopify_cli/tunnel.rb

Fixes #1776
After installing ngrok, the CLI is checking if the executable is present, but since [this change](https://github.com/Shopify/shopify-cli/pull/1758) released with the version 2.7.1, on Windows it's looking for a `ngrok` file instead of `ngrok.exe`, causing the installation to fail.
Fix the executable name for Windows environments.
`shopify app serve` on Windows

Fix ngrok installation check on Windows

---

lib/project_types/script/config/extension_points.yml
test/project_types/script/ui/error_handler_test.rb

The extension points YAML file should be cleaned up to not allow creating/working with deprecated Script APIs anymore.
Related to https://github.com/Shopify/script-service/issues/3869
Before 
After
Removes APIs from .yml file. 
`shopify-dev config feature scripts_beta_extension_points --enable`
`shopify-dev script create`
This should enable the beta extension points and show a list of the updated APIs.

Remove Deprecated Script APIs

---

lib/project_types/extension/messages/messages.rb
test/project_types/extension/messages/message_loading_test.rb

I've noticed the following warning message in the test suite:
```
DEPRECATED: Use assert_nil if expecting nil from /Users/karreiro/src/github.com/Shopify/shopify-
cli/test/project_types/extension/messages/message_loading_test.rb:54. This will fail in Minitest 6.
```
It started happening when we removed the `"build.build_failure_message"`. However, we still use it in production (`Extension::Command::Build`) and on tests (`Extension::Messages::MessageLoadingTest`).
This PR brings the `"build.build_failure_message"` message back.
Run `rake test` or check one of the following CI jobs:
- `Tests with Ruby 3.0.2 on macos-11`
- `Tests with Ruby 3.0.2 on ubuntu-20.04`
- `Tests with Ruby 2.6.6 on macos-10.15`
- `Tests with Ruby 2.6.6 on ubuntu-20.04`
- `Tests with Ruby 2.6.6 on ubuntu-18.04`
- …

Fix "DEPRECATED: Use assert_nil if expecting nil" message

---

lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb

Currently, we check the format of the npm build script command before allowing the script to be built. This is problematic because this prevents us from changing this command in the future, or prevents partners from having the flexibility to change their dev environment to suit their own needs.
As discussed on slack, we will remove this check on the format of the npm build script and the associated error class. 
1. Create a new script. 
2. Change the `build` script command in your new package.json file. If you're using TS, you can change this to be `shopify script javy ...` instead of `javy ...`. 
3. Run `shopify script push`. The script should build and push successfully.

Stop checking the format of a script project's build script command

---

CHANGELOG.md
lib/project_types/theme/commands/push.rb
test/project_types/theme/commands/push_test.rb

We reconsidered [this change](https://github.com/Shopify/shopify-cli/pull/1798#discussion_r758367619) considering [@ADTC feedback](https://github.com/Shopify/shopify-cli/issues/1647#issuecomment-982674668).
Now, the `--live` parameter does not imply `--allow-live` in the `theme push` command anymore.
Run `shopify theme push --live` and see the confirmation message:

Fix `--live` parameter, it should not imply `--allow-live` in the `theme push` command

---

lib/project_types/rails/commands/create.rb
lib/shopify_cli/services/app/create/rails_service.rb
test/shopify-cli/services/app/create/rails_service_test.rb

Spring is no longer bundled by default in Rails 7. Creating an app
with `rails new --skip-spring app_name` will create a `--skip-spring`
directory.
For context, Spring was removed in this commit:
https://github.com/rails/rails/commit/21c9732fae9ce0fff7adf0da610d26eeedfc3076
This commit fixes that by putting the app name first. In my testing,
`rails new` ignores the extra flag it doesn't understand, so it should
work on both Rails 6 and Rails 7.
```
gem instal rails --pre
shopify app create rails
```

Fix `rails new` command for Rails 7

---

CHANGELOG.md
lib/shopify_cli/git.rb
test/shopify-cli/git_test.rb

This solves a number of issues of the form of https://github.com/Shopify/shopify-cli/issues/1782
Sometimes git is necessary; other times it's just a nice-to-have. When we make API calls, we use git to [check the CLI sha](https://github.com/Shopify/shopify-cli/blob/bb3f891f3a035c439555621ecaf2cbfa80ac1789/lib/shopify_cli/api.rb#L111). While it would be nice to have, we can live without it when it's unavailable; it's not worth the DX impact. Hence, we already introduced the `ShopifyCLI::Git::available?` method.
However, this method doesn't check properly, as the underlying `Open3::capture2e` will raise an error if the underlying executable isn't available at all. (For other errors, it will actually return output and a process status as expected.) This has resulted in cryptic errors when git …

Indicate git is unavailable; don't error out

---

CHANGELOG.md
lib/shopify_cli/theme/dev_server.rb
lib/shopify_cli/theme/dev_server/cdn_fonts.rb
test/shopify-cli/theme/dev_server/cdn_fonts_test.rb

Fonts were not loading because the Shopify fonts CDN expects a valid HTTP referer header.
This PR introduces changes in the `ShopifyCLI::Theme::DevServer` to request fonts from the CDN with the expected headers and serve them locally.
1. Run `shopify theme serve` service
2. Open the http://127.0.0.1:9292
3. Check the fonts are now loading as expected
Before this PR:
After this PR:
None.

Fix Shopify hosted fonts to load via the local preview URL

---

.github/CODEOWNERS

The scripts-experience team in GitHub has been renamed to scripts-platform. 
Updates the codeowners file to use scripts-platform.

Rename shopify/scripts-experience team to shopify/scripts-platform in codeowners

---

CHANGELOG.md
lib/shopify_cli/theme/dev_server/hot-reload.js

Some users rely on tools over their theme (like Webpack) to update multiple files in a very short period of time.
The `message.date.modified`  list may contain multiple files in that kind of scenario. However, if the first file of the list doesn't require refreshing the entire page, while the second file does, the changes from the second file are not covered by the hot reload mechanism.
This pull request introduces changes in the `hot-reload.js` module to analyze all modified files instead of considering only the first one (inspired by https://github.com/Shopify/shopify-cli/pull/1458).
Download the `reproducer_remove_me.rb` [here](https://gist.github.com/karreiro/319bae3a086331b25df1b341572da248).
```bash
$ shopify-dev theme init my_theme
$ cd my_theme
$ pwd
/Users/karreiro/theme # ← Keep …
```

Fix hot reload when users update many files "simultaneously"

---

lib/project_types/script/config/extension_points.yml

The beta script API (extension point) `discount_types` has been split into `merchandise_discount_types` and `delivery_discount_types`. This change needs to be reflected in the CLI so that it doesn't fail validations when we try to push scripts.
I removed `discount_types` as an API and added `merchandise_discount_types` and `delivery_discount_types`.
Any existing script using `discount_types` as an API will no longer function. This API was in an early development stage and so only core developers should have scripts with this extension point. Script Service no longer recognizes this API, so the push would fail regardless of CLI validation.

Split discount types into two types

---

CHANGELOG.md
lib/shopify_cli/theme/dev_server/cdn_fonts.rb
test/shopify-cli/theme/dev_server/cdn_fonts_test.rb

The https://github.com/Shopify/shopify-cli/pull/1821 PR fixes the font issue for the **Assistant** font, but other fonts were failing because of the `ShopifyCLI::Theme::DevServer::CdnFonts` regex as miss including the `/assistant` suffix.
Now, the regex does not include the **Assistant** font suffix anymore.
1. Go to the theme directory
2. Update the `config/settings_data.json` file with a different font (e.g., `fira_sans_n9`)
3. Run `shopify theme serve` service
4. Open the http://127.0.0.1:9292
5. Check the fonts are now loading as expected
None.

Fix `ShopifyCLI::Theme::DevServer::CdnFonts` class to support any font

---

lib/project_types/script/config/extension_points.yml

During a previous PR this beta API was given the wrong api package name, causing issues when we tried to extract the package version.
This pull request is correcting that error with the correct package name.
I've verified that it now can extract the version number.el free to remove this section.

Fix typo in package name

---

CHANGELOG.md
lib/project_types/script/cli.rb
lib/project_types/script/graphql/app_script_set.graphql
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/errors.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/domain/script_config.rb
lib/project_types/script/layers/domain/script_project.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/layers/domain/script_config_test.rb
test/project_types/script/layers/domain/script_project_test.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/test_helpers/fake_push_package_repository.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb
test/project_types/script/ui/error_handler_test.rb

Closes https://github.com/Shopify/script-service/issues/3729
As explained in the issue, we want to more closely align with other teams like UI Extensions.
Adds support for using a `script.config.yml` file for encoding Script configuration. If the `script.config.yml` is not present but a `script.json` is, we will use that.
1. Create a new script with `shopify script create` and select `shipping-methods` API and TypeScript language
2. See that `script.json` has the right title (what you entered as the name of the script)
3. Update the `script.json` to have some fields
4. Push the script with `shopify script push`
5. See the configuration fields when trying to enable the customization on your shop in the shipping settings
1. Create a new script with `shopify script create …

[Scripts] Support using `script.config.yml` file for script configuration

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing version 2.7.3 of the CLI with the following changelog:
* [#1826](https://github.com/Shopify/shopify-cli/pull/1826): Support using `script.config.yml` file for script configuration
* [#1811](https://github.com/Shopify/shopify-cli/pull/1811): Update theme-check to 1.9.0
* [#1831](https://github.com/Shopify/shopify-cli/pull/1831): Ensure correct `ngrok` version is downloaded for Apple M1
* [#1823](https://github.com/Shopify/shopify-cli/pull/1823): Indicate git is unavailable; don't error out
* [#1807](https://github.com/Shopify/shopify-cli/pull/1807): Fix `--live` parameter, it should not imply `--allow-live` in the `theme push` command
* [#1812](https://github.com/Shopify/shopify-cli/pull/1812): App creation with Rails 7
* …

Release v2.7.3

---

CHANGELOG.md
ext/javy/javy.rb
test/ext/javy/javy_test.rb

Mac machines come preinstalled with a universal distribution of Ruby created by Apple that includes both arm64 and x86 binaries, and will use the appropriate one depending on the cpu of the machine. There is a bug (or a confusing feature?) in the distribution with the use of `RbConfig`. No matter what CPU you're on (intel or M1) the `RbConfig` sets the `host_cpu` field to `x86`. The current approach to installing Javy checks this variable and downloads the appropriate binary, but if you're on an M1 machine, that means we download the binary for Intel machines. When you install a new version of ruby with chruby/vrm/brew, then this problem disappears. However, Javy should work out of the box. 
Instead of using `RbConfig::CONFIG`, use `RUBY_PLATFORM` constant. This constant reports the host …

[scripts] use RUBY_PLATFORM instead of RbConfig to check platform details for Javy installation

---

CHANGELOG.md
lib/project_types/theme/commands/push.rb
lib/project_types/theme/messages/messages.rb
test/project_types/theme/commands/push_test.rb

When users execute `shopify theme push --live`, they do not know which theme is being used as live (https://github.com/Shopify/shopify-cli/pull/1807#issuecomment-982857030, https://github.com/Shopify/shopify-cli/issues/1809).
Now, when users push a theme with the `--live` parameter, the confirmation message shows the live theme name and ID.
Run `shopify theme push --live` and noticed the current live theme name and ID appears:
None.

Improve `shopify theme push --live` confirmation message to show current live theme

---

dev.yml

While investigating M1-related issues running `dev up`, I realize there are more recent versions of the Homebrew packages we depend on for bundling the CLI for distribution.
I'm updating them to the latest available version.
1. Check out the branch.
2. Run `dev up`.
3. Run `bundle exec rake package`

Update dpkg and rpm

---

lib/shopify_cli/command.rb
lib/shopify_cli/messages/messages.rb
vendor/deps/cli-kit/lib/cli/kit/error_handler.rb

[Error 1](https://app.bugsnag.com/shopify/shopify-cli/errors/615df2bca7796200085185bc?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in]=2.7.0)
[Error 2](https://app.bugsnag.com/shopify/shopify-cli/errors/615c602b14a5fc000787762e?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in]=2.7.0)
[Error 3](https://app.bugsnag.com/shopify/shopify-cli/errors/615e23e3d8331a0008df58b0?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in]=2.7.0)
Errors parsing the CLI arguments should not be reported to Bugsnag because they are not bugs.
I'm rescuing from them and raising them as aborts that are formatted and output to the user consistently.
Try to run the CLI with an invalid argument: `shopify app create --invalid argument`

Abort from OptionParser errors

---

CHANGELOG.md
lib/project_types/extension/cli.rb
test/project_types/extension/commands/create_test.rb

The `extension` commands appear in the [shopify.dev](https://shopify.dev/apps/online-store/theme-app-extensions/getting-started#step-2-scaffold-and-register-a-theme-app-extension) website. However, users cannot access the help for these commands in the `shopify --help`.
This PR removes the `hidden_feature` call from the `Extension::Command`, and now users are able to see the `extension` commands when they execute `shopify --help`.
Run `shopify-dev --help` and check new `extension` entry:
None.

Fix `shopify --help` to include `extension` commands

---

lib/project_types/script/layers/infrastructure/script_project_repository.rb

Follow up to Fix https://github.com/Shopify/shopify-cli/pull/1795
The linked PR added some properties and made them required.
However, these values are only really required for the `script create` command.
The PR therefore fails on other steps, such as `script push` and `script connect`.
In order to fix quickly, this PR makes these properties not-required.
We can revisit this later if we feel these fields should instead be required, but have a sensible default.
`shopify script create`
`shopify script push`
`shopify script connect`

fix: make new properties in ScriptProjectRepository not required

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing version 2.7.4 of the CLI with the following changelog:
* [#1825](https://github.com/Shopify/shopify-cli/pull/1825): Support passing the connection information through arguments
* [#1852](https://github.com/Shopify/shopify-cli/pull/1852): Fix `shopify --help` to include `extension` commands
* [#1853](https://github.com/Shopify/shopify-cli/pull/1853): Fix javy installation failures from MacOS universal ruby installations
* [#1851](https://github.com/Shopify/shopify-cli/pull/1851): Improve `shopify theme push --live` confirmation message to show current live theme
* [#1850](https://github.com/Shopify/shopify-cli/pull/1850): Fix `shopify extension` commands timeout when organization has too many apps
* [#1860](https://github.com/Shopify/shopify-cli/pull/1860): Fix `theme serve` …

Release v2.7.4

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the Shopify CLI, 2.8.0, with the following changelog:
* [#1879](https://github.com/Shopify/shopify-cli/pull/1879): Disambiguate -s as store option

Packaging for release v2.8.0

---

lib/project_types/script/commands/connect.rb
lib/project_types/script/layers/application/connect_app.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/commands/connect_test.rb

When running `script connect`, an error is raised if the user answers 'no' to the ` Do you want to replace any of the existing scripts on the app with this script?` prompt. We can't have that right now, because that is the only way we can create scripts at the moment. The user should be able to answer `no` and create a new script.
Removes the strict option that requires that a script is selected during connect.
- create a script
- run `shopify script connect`
- run `shopify script push` and verify it works
- check the .env file to ensure a new UUID was created and saved

[scripts] Remove strict option in ConnectApp

---

ext/javy/javy.rb

Closes https://github.com/Shopify/script-service/issues/4157
The previous location javy was stored was in the `shopify-cli/ext/javy/bin` directory. This created a problem when using the gem installed version of the CLI as the executable is within a directory that a default user does not have write permissions for.
Change the javy installation directory to the CLI's cache directory (`~/.cache/shopify/` by default on unix), so the new binary is located at `~/.cache/shopify/javy/bin/javy-v0.1.0`. I chose to use the cache directory as it is already used to store binaries like ngrok used for `shopify app serve` or heroku CLI. 
- Check that Javy is installed by default
- Run `shopify script javy --in build/index.js --out build/index.wasm` inside your script project. The command should succeed …

[scripts] move javy binary location to cli cache directory

---

CHANGELOG.md
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/messages/messages.rb
lib/shopify_cli/theme/theme.rb
test/shopify-cli/theme/theme_test.rb

This fixes #1878: Users can't pull the changes from the current development theme to save them after making modification on the local theme customiser.
This saves so much time, and might prevent pulling a different theme especially in stores with 100 themes. 
This PR introduces a new flag representing the development theme `-d/--development`. So, now users can perform operations like `shopify theme pull --development` to retrieve the settings made in local theme customiser without being prompt to select/choose the development theme (works just like the `--live` flag)
To test the changes run the following commands after lunching the development server
```shell
shopify theme pull --development
or 
shopify theme pull -d
```
Update documentation with the new -d/--development flag at …

Add `-d/--development` flag to Shopify theme pull command.

---

CHANGELOG.md
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/messages/messages.rb
lib/shopify_cli/theme/theme.rb
test/project_types/theme/commands/pull_test.rb
test/project_types/theme/commands/push_test.rb
test/shopify-cli/theme/theme_test.rb

Users can't set the theme name when running commands like `shopify theme push -u` (https://github.com/Shopify/shopify-cli/issues/1431).
This PR introduces a new parameter representing the theme name `-t`/`--theme=NAME_OR_ID`. So, now users can perform operations `shopify theme push -u -t my_theme`.
For consistency, this PR also:
- Adds the `-t`/`--theme=NAME_OR_ID` to `theme pull`
- Adds the `-t`/`--theme=NAME_OR_ID` to `theme push` (globally, even without the`--unpublished` parameter)
Thus, now users may rely on the `-t <NAME_OR_ID>` to `push`/`pull` a theme, instead of only relying on `-i <ID>`.
Run the following commands for checking the impact of the new parameter on `theme push`:
```bash
shopify theme push --live
shopify-dev theme push --theme abc
shopify-dev theme push -t abc …
```

Add theme (`-t`/`--theme=NAME_OR_ID`) parameter to `theme push`/`theme pull` commands

---

CHANGELOG.md
lib/project_types/script/config/extension_points.yml

Reverts https://github.com/Shopify/shopify-cli/pull/1896
As per Mitch's update, we will not be releasing TS support for payment/shipping APIs yet so I am adding the beta flag back in. A new release hasn't been made yet, so we can just remove it from the unreleased changelog.

revert "Remove beta flag from payment and shipping APIs"

---

lib/project_types/extension/models/development_server.rb

To avoid printing superflous debug messages when running extension serve
Use `context.debug` instead of `context.puts` for debug messages and remove some unnecessary messages.
1. Make sure you have the extension server beta unabled by running `shopify-local config feature extension_server_beta --enable`
2. Create an extension with `shopify extension create`
3. Run `DEBUG shopify extension serve` and verify that the output includes
```
DEBUG Sending configuration data to extension development server …
DEBUG Starting message relaying threads to capture output produced by the extension development server …
```
Secondly, run `shopify extension serve` and verify that above output is omitted.
No further action is required. This can simply be included in the next release. The code path is …

Mark extension debug messages as such

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the CLI, 2.9.0, with the following changelog:
* [#1922](https://github.com/Shopify/shopify-cli/pull/1922): Respect RUBY_BINDIR from Homebrew for installing gem
* [#1906](https://github.com/Shopify/shopify-cli/pull/1906): Fix Ngrok incompatibility with some Apple ARM environments
* [#1873](https://github.com/Shopify/shopify-cli/pull/1873): Fix partners ability to login to external shops.
* [#1909](https://github.com/Shopify/shopify-cli/pull/1909): Fix `theme serve` on Safari
* [#1900](https://github.com/Shopify/shopify-cli/pull/1900): Add `-d`/`--development` flag to Shopify theme pull command
* [#1896](https://github.com/Shopify/shopify-cli/pull/1896): Release Typescript options for payment_methods and shipping_methods scripts
* …

Packaging for release v2.9.0

---

lib/shopify_cli/constants.rb
lib/shopify_cli/environment.rb
lib/shopify_cli/identity_auth.rb
test/shopify-cli/environment_test.rb

Setting up the CLI to use spin is currently a manual process in which you need to find and enter in your current spin namespace and workspace. We should be able to point at the active spin workspace with a single flag.
- Consolidate the two sets of spin variables into a single `SPIN` variable. If you're using Spin, everything you're calling should be in Spin.
- Add a `INFER_SPIN` env variable which tells the CLI to try pulling the workspace/namespace from spin by parsing the output of the `spin info fqdn` command.
Unset SPIN_WORKSPACE and SPIN_NAMESPACE
Run commands with `SPIN=1 INFER_SPIN=1` and check that it uses your active spin workspace.

Consolidate spin vars and allow inference

---

CHANGELOG.md
lib/shopify_cli/theme/file.rb
test/shopify-cli/theme/file_test.rb

In some scenarios, the `theme pull` adds new empty lines for Windows users.
When users set the end of line sequence on VSCode to CRLF, Ruby IO#read (`[...]theme/file.rb`) produces CRCRLF sequences, adding empty lines.
With the issue living either on the Ruby IO side or on VSCode, we have to abstract that from partners. So, this PR relies on the `universal_newline` decorator for normalizing end of line sequences as LF (this PR proposes this alternative).
These steps require two systems to proceed, a Unix and a Windows.
- [On Unix] Create a theme with `shopify theme init`
- [On Unix] Publish this theme with `shopify theme push -u`
- [On Windows] Pull the theme above with `shopify theme pull -i THEME_ID`
- [On Unix] Open the `sections/announcement-bar.liquid` file with VSCode
- [On Unix] …

Fix `theme pull` to no longer add empty lines on Windows

---

lib/shopify_cli.rb
lib/shopify_cli/core/executor.rb
lib/shopify_cli/method_object.rb
lib/shopify_cli/result.rb
lib/shopify_cli/task.rb
vendor/deps/ruby2_keywords/LICENSE
vendor/deps/ruby2_keywords/README.md
vendor/deps/ruby2_keywords/Rakefile
vendor/deps/ruby2_keywords/lib/ruby2_keywords.rb
vendor/deps/ruby2_keywords/ruby2_keywords.gemspec
vendor/deps/ruby2_keywords/test/test_keyword.rb

Delegation in Ruby is extremely complicated when you're trying to support a broad range of versions, including future versions.
Using `ruby2_keywords` is the carefully thought-out best-practice way to do this.
* https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html
* https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
It uses `ruby2_keywords`, via the vendored gem.
There's one very tricky case, which is commented.

Use ruby2_keywords for delegation

---

CHANGELOG.md
lib/project_types/script/graphql/module_upload_url_generate.graphql
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/layers/infrastructure/script_uploader.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/layers/infrastructure/script_uploader_test.rb

In order to support a file size limit in GCS, the client must include the `x-goog-content-length-range` header in the upload request. Otherwise, GCS will not allow the file upload.
Related issue: https://github.com/Shopify/script-service/issues/4128
Backend PR: https://github.com/Shopify/script-service/pull/4158
Closes https://github.com/Shopify/script-service/issues/4129
1. Use my backend branch
2. Push a script => it should work
3. Lower the file size limit in the backend (e.g. 100 bytes)
4. Push a script => it should fail
- Notify @andrewhassan so the corresponding backend change can be shipped around the same time.
- [ x] I've included any post-release steps in the section above.

[Scripts] Limit module file size

---

CHANGELOG.md
lib/shopify_cli/theme/dev_server.rb
lib/shopify_cli/theme/dev_server/cdn/cdn_helper.rb
lib/shopify_cli/theme/dev_server/cdn_assets.rb
lib/shopify_cli/theme/dev_server/cdn_fonts.rb
lib/shopify_cli/theme/dev_server/local_assets.rb
test/shopify-cli/theme/dev_server/cdn/cdn_helper_test.rb
test/shopify-cli/theme/dev_server/cdn_assets_test.rb

Some assets don't load from the `LocalAssets` middleware because their path [doesn't match](https://github.com/Shopify/shopify-cli/blob/main/lib/shopify_cli/theme/dev_server/local_assets.rb#L7) or [is not a static](https://github.com/Shopify/shopify-cli/blob/main/lib/shopify_cli/theme/dev_server/local_assets.rb#L75) theme path. So, they load from the CDN, and cross-origin resource sharing errors happen.
Like the `CdnFonts` middleware, the `CdnAssets` requests assets to serve them locally. But, it checks if `LocalAssets` are not handling the file.
- Run `shopify theme init` to create a new theme
- Import product data from [products.csv](https://gist.githubusercontent.com/karreiro/2cc4724245a11e2549cc7e6711def453/raw/a11c91bc0cab186af910cbd5126de24102597b34/products_export.csv) in your …

Fix CORS (Cross-origin resource sharing) errors

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the Shopify CLI, 2.10.0, with the following changelog:
* [#1937](https://github.com/Shopify/shopify-cli/pull/1937): Fix `theme pull` to no longer add empty lines on Windows
* [#1952](https://github.com/Shopify/shopify-cli/pull/1952): Fix CORS (cross-origin resource sharing) errors
* [#1965](https://github.com/Shopify/shopify-cli/pull/1965): Revert: Fix partners ability to login to external shops. (#1873)
* [#1892](https://github.com/Shopify/shopify-cli/pull/1892): Add `-o`/`--only` parameter to filter files on `theme push`/`theme pull` commands

Packaging for release v2.10.0

---

lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/push_package.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/push_package_test.rb
test/project_types/script/test_helpers/fake_push_package_repository.rb

Follow up from https://github.com/Shopify/shopify-cli/pull/1936#discussion_r789967471
The `compiled_type` method in our task_runners are not very useful anymore. It used to be there when we needed to support non-wasm executables (graalVM + static), but the CLI has no more knowledge of those types. 
The only thing that still uses the `compiled_type` method is the `push_package_repository`. Instead of the task_runner having to know the `compiled_type` and pass it into the `push_package_repository` everytime, its cheaper and simpler to assume we are working with `wasm`, so I hardcoded `wasm` in the `push_package_repository`. If we ever need to support non-wasm executables then this is easy to revert, but we will also probably have to change many other things first so this change doesn't …

[scripts] remove TaskRunner#compiled_type

---

lib/project_types/script/graphql/app_script_set.graphql
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/script_project.rb
lib/project_types/script/layers/infrastructure/script_project_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/domain/script_project_test.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/test_helpers/fake_script_project_repository.rb

For fetch plans, we want to allow script authors to write a GraphQL query so that they can parametrize the input sent to their script.
Reads the content of `input.graphql` at the root of the script project directory, and sends it as the `inputQuery` param to script service's `appScriptSet` mutation.
I decided to not create `input.graphql` files on script create for now, because the feature isn't ready yet. It also brings a few questions that we can tackle later.
Depending on when you're testing this, you may need to checkout `jb/fetch-plans-input-query` on script-service.
1. Create a `input.graphql` file at the root of your script project. Put whatever in there (it's not validated at the moment).
2. `shopify script push`
3. Script service's `app_scripts.input_query` should be populated …

Send `input.graphql` to script service

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the Shopify CLI, 2.10.1, with the following changelog:
* [#1985](https://github.com/Shopify/shopify-cli/pull/1985): Revert "Fix CORS (Cross-origin resource sharing) errors (#1952)"

Packaging for release v2.10.1

---

lib/project_types/script/cli.rb
lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/application/build_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/domain/errors.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/wasm_task_runner.rb
lib/project_types/script/layers/infrastructure/metadata_repository.rb
lib/project_types/script/layers/infrastructure/push_package_repository.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/application/build_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/wasm_task_runner_test.rb
test/project_types/script/layers/infrastructure/metadata_repository_test.rb
test/project_types/script/test_helpers.rb
test/project_types/script/test_helpers/fake_metadata_repository.rb

Closes https://github.com/Shopify/script-service/issues/4124
This PR depends on https://github.com/Shopify/shopify-cli/pull/1905 being shipped first.
Adds the ability for the CLI to push script projects that provide a Wasm module directly.
It does so by:
- Reading the existing Wasm module during the the build step in `PushScript` if the project.language is Wasm
- Refactoring how we read metadata into `MetadataRepository`.
- Read from the files generated during the create step
- Slight change to how `ScriptService` class was building the variables for the GQL request.
- Copy over any random Wasm to `/script.wasm` in the root directory.
- `shopify script push`.

Support wasm push packages

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

I'm releasing a new version of the Shopify CLI, 2.10.2 with the following changelog:
* [#1983](https://github.com/Shopify/shopify-cli/pull/1983): Improve Windows compatibility
* [#1928](https://github.com/Shopify/shopify-cli/pull/1928): Ensure script Wasm file sizes don't exceed the limit

Packaging for release v2.10.2

---

lib/project_types/script/commands/connect.rb

Fixes https://github.com/Shopify/script-service/issues/4201
Currently, the `shopify script connect --help` commands outputs the string for "extensions", but we have a specific one available for scripts.
This PR uses the correct string.
- Run `shopify script connect --help`.

use correct message key for script connect

---

lib/project_types/extension/models/specification_handlers/default.rb
test/project_types/extension/commands/build_test.rb

For backwards compatibility reasons, we're renaming `shopifile.yml` to `extension.config.yml`. That's the name of the config that most extensions use today.
Changing the default values for the config file name for extensions from `shopifile.yml` to `extension.config.yml`.
1. Ensure you have `shopify-extensions-cli` installed
* `dev clone shopify-cli-extensions`
* `make build`
* `cd packages/shopify-cli-extensions && npm link`
2. Enable the development server beta: `shopify-local config feature extension_server_beta --enable`
3. Create a new extension with `shopify extension create`
4. Ensure that `extension.config.yml` exists and that `shopifile.yml` is absent
5. Run `npm link @shopify/shopify-cli-extensions`
6. Run `shopify extension build`
7. Ensure that the command finished successful …

Rename shopifile.yml to extension.config.yml

---

CHANGELOG.md
lib/project_types/extension/commands/build.rb
lib/project_types/extension/commands/check.rb
lib/project_types/extension/commands/create.rb
lib/project_types/extension/commands/push.rb
lib/project_types/extension/commands/serve.rb
lib/project_types/script/commands/connect.rb
lib/project_types/script/commands/create.rb
lib/project_types/script/commands/push.rb
lib/project_types/theme/commands/check.rb
lib/project_types/theme/commands/delete.rb
lib/project_types/theme/commands/init.rb
lib/project_types/theme/commands/language_server.rb
lib/project_types/theme/commands/package.rb
lib/project_types/theme/commands/publish.rb
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/commands/serve.rb
lib/shopify_cli/command.rb
lib/shopify_cli/command/sub_command.rb
lib/shopify_cli/commands/app/create.rb
lib/shopify_cli/commands/app/create/node.rb
lib/shopify_cli/commands/app/create/rails.rb
lib/shopify_cli/commands/app/deploy.rb
lib/shopify_cli/commands/app/serve.rb
lib/shopify_cli/constants.rb
lib/shopify_cli/environment.rb
lib/shopify_cli/exception_reporter.rb
test/project_types/extension/commands/build_test.rb
test/shopify-cli/environment_test.rb

Some users are running into issues because the version of the interpreters that they are using (e.g. Node, Ruby), is incompatible with the CLI. When that happens, users are often presented with cryptic errors that bubble up from deep pieces in the dependency graph and that makes the issues not very actionable for them.
This PR doesn't prevent that scenario from happening because the runtime developers use is outside of our control, but prints a warning if we detect the version they are using might be incompatible with the CLI. This helps them pin-point their issue with the warning and try with a different version before opening a support ticket on our side.
1. Check out the branch.
2. Switch to a Node version that's incompatible with the CLI, for example Node 17
3. Run any of the commands …

Warn users when they are using a Node/Ruby version that's outside of a default range

---

CHANGELOG.md
lib/shopify_cli/environment.rb

This supports the rewrite of the Spin CLI, specifically for fetching the FQDN while authenticating to a Spin instance. Otherwise, once the rewrite becomes introduced across the company (planned for **tomorrow**), the Shopify CLI will become broken with Spin.
For now, I'm supporting both spin-legacy and spin2. This will be helpful as we transition the company's default installation for the `spin` binary. Once `spin2` has hit and become the default for perhaps a week, then we can delete any code pertaining to `spin-legacy`.
I've marked the `SPIN_INSTANCE` environment variable as required, since it is now needed to specify your current instance identifier.
Assuming that `spin` still points to `spin-legacy` on your local machine, run some local `shopify` commands with the `SPIN=1 INFER_SPIN=1 …

Supports both spin-legacy and spin2 for Spin FQDN command

---

lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/ui/error_handler_test.rb

A couple of errors messages were malformed in https://github.com/Shopify/shopify-cli/pull/1997/files.
This passed CI because not every error class + message is tested in the `error_handler_test.rb`.
- Adds a test that the error_handler handles each error case properly. This means that if a broken error message happens again, we'll know about it. (But, we have to make sure each new error message adds a test here. Not sure if theres a way we can easily enforce that 🤔)
- Updates the broken messages so that they'll print properly. 
Throw `Script::Layers::Infrastructure::Errors::ScriptEnvAppNotConnectedError` and `Layers::Domain::Errors::MetadataNotFoundError.new('path/to/file')` and make sure you can see the error messages.

[scripts] fix some broken error messages

---

CHANGELOG.md
lib/shopify_cli/github/issue_url_generator.rb

Part of fixing #1972 
Currently if an error doesn't have a backtrace (which shouldn't happen under normal circumstances but seems to under certain edge cases), we lose the entire error, which is making it impossible to debug that issue.
If there's no error backtrace, just use `""` for the backtrace text.
Need to generate an error which triggers the message, `✗ An unexpected error occured.`
In `IssueURLGenerator::error_url`, before hitting the affected LOC, add `error.set_backtrace(nil)`
Also need to make sure `ExceptionReporter` reports even in `development`
Try with and without the change.
Before:
After:
It's not awesome since either way we don't see the stack trace, but at least we'll end up not totally crashing on an unrelated error.

Fix: More defensive URL generation

---

.github/ISSUE_TEMPLATE/bug_report.yaml
CHANGELOG.md
lib/shopify_cli/github/issue_url_generator.rb
test/shopify-cli/github/issue_url_generator_test.rb

The bug issue template is still a bit rough around the edges, here are some clear improvements.
Improving the UX of the bug issue template
In the console, try:
```ruby
begin
invalidcommand
rescue => e
ShopifyCLI::GitHub::IssueURLGenerator.error_url(e)
end
```
and see the stacktrace included as a param.

Template improvements II

---

lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/application/push_script.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/task_runner.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/wasm_task_runner.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/application/push_script_test.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/wasm_task_runner_test.rb

Fixes https://github.com/Shopify/script-service/issues/2796
Converts the base task_runner into more of an interface and then makes the specific_task_runners inherit from it.
Create / Push a script to ensure it all still works.
There's no real behaviour modification here.

add task_runner interface

---

CHANGELOG.md
lib/project_types/theme/commands/check.rb
lib/project_types/theme/commands/delete.rb
lib/project_types/theme/commands/init.rb
lib/project_types/theme/commands/language_server.rb
lib/project_types/theme/commands/package.rb
lib/project_types/theme/commands/publish.rb
lib/project_types/theme/commands/pull.rb
lib/project_types/theme/commands/push.rb
lib/project_types/theme/commands/serve.rb
lib/shopify_cli/command.rb
lib/shopify_cli/commands/app/create.rb
lib/shopify_cli/commands/app/create/rails.rb
lib/shopify_cli/commands/app/deploy.rb
lib/shopify_cli/commands/app/serve.rb
lib/shopify_cli/messages/messages.rb
test/project_types/script/commands/connect_test.rb
test/project_types/script/commands/create_test.rb
test/project_types/script/commands/javy_test.rb
test/test_helpers.rb
test/test_helpers/command.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2031
The recent introduction of warnings to warn the user if their Node and Ruby might be incompatible with the CLI caused [errors](https://github.com/Shopify/shopify-cli/issues/2031) for users that don't have Node installed.
I extended the logic to account for that scenario an abort the execution in that case.
1. Add `recommend_default_node_range` to `whoami.rb`
2. Simulate not having Node, for example changing the `if` statement to be true.
3. Run `bins/shopify whoami`.
4. You should see the error.

Abort if Node is necessary and it's not present

---

lib/shopify_cli/constants.rb
lib/shopify_cli/environment.rb
test/shopify-cli/environment_test.rb

The latest update for the spin CLI removed the `spin info fqdn` feature that we relied upon to get the latest spin instance fqdn.
A previous PR put up a warning instructing users to find their spin fqdn manually, but it's nice for users to not have to look this up.
It refactors the spin code so that we don't have 3 separate ways to retrieve the spin url and a number of possible invalid configurations.
The new system:
- If you have `SPIN` set, we'll use the spin url returned by the spin tool
- If you've set `SPIN_WORKSPACE`, `SPIN_NAMESPACE`, and `SPIN_HOST` we'll use those instead of asking spin for the FQDN.
- If you set `SPIN_INSTANCE`, we'll call `spin show --json` and get that particular instance
- If you don't set `SPIN_INSTANCE`, we'll call `spin show --latest --json` which gets the …

Simplify and fix Spin URL selection

---

CHANGELOG.md
lib/shopify_cli/theme/dev_server/proxy.rb
test/shopify-cli/theme/dev_server/proxy_test.rb

When users open URLs with multiple occurrences of the same parameter (`?param=A&param=B`), they lose one of the values (`A` or `B`).
This PR changes the proxy to no longer convert query parameters into a hash map so users do not lose values anymore.
- Run `shopify theme serve`
- Navigate to the collections page
- Apply multiple filters
**Before this PR**
**After this PR**
None.

Fix `theme serve` to accept parameters with multiple values

---

lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
test/project_types/extension/models/specification_handlers/theme_app_extension_test.rb

Theme app extensions will accept Locales directory. The new directory must only contain `.json` files.
This PR allows the CLI to identify Locales directory in theme app extension as valid directory.

[Feature] Support Locales directory in Theme App Extensions

---

CHANGELOG.md
packaging/homebrew/shopify-cli.base.rb

The changes [in this PR](https://github.com/Shopify/shopify-cli/pull/2033) broke the installation through Homebrew because the `def ruby_bin` method is trying to get the path to the Ruby binary from the wrong formula. I've updated it to read it from the `ruby@3.0` and taken the opportunity to improve installation errors.
Fix the template that we use to generate the formula at release time.
1. Add the changes to `/opt/homebrew/Library/Taps/shopify/homebrew-shopify/shopify-cli.rb`.
2. Uninstall the CLI with `brew uninstall shopify-cli`.
3. Run `brew install shopify-cli`.

Fix the Homebrew template

---

CHANGELOG.md
lib/project_types/extension/commands/build.rb
lib/project_types/extension/commands/check.rb
lib/project_types/extension/commands/create.rb
lib/project_types/extension/commands/push.rb
lib/project_types/extension/commands/serve.rb
lib/shopify_cli/command.rb
lib/shopify_cli/constants.rb
lib/shopify_cli/messages/messages.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2039
After adding a check to show the recommended versions for Ruby and Node in https://github.com/Shopify/shopify-cli/pull/1945 and https://github.com/Shopify/shopify-cli/pull/2032, we are now requiring Node for all the commands, even when they don't really need it.
- Fix the `check_version` method to only run it for the commands defining the recommended Node rage (`recommend_default_node_range`).
- Only check the Node versions for `app create rails` and `app create node`, as it was before.
We could add it as well for other commands like `app serve`, but we should check the type of app to avoid doing it for PHP. Also, we should carefully decide where we want to show it and check what operations really need it, so I'll leave it for …

Remove unneeded Node requirements

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2047](https://github.com/Shopify/shopify-cli/pull/2047): Fix the Homebrew installation
* [#2019](https://github.com/Shopify/shopify-cli/pull/2019): Provide helpful link when nokogiri fails to load
* [#2055](https://github.com/Shopify/shopify-cli/pull/2055): Remove unneeded Node requirements

Release 2.11.2

---

CHANGELOG.md
lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb
lib/shopify_cli/messages/messages.rb
test/project_types/extension/models/specification_handlers/checkout_ui_extension_test.rb

Fixes [internal issue](https://github.com/Shopify/checkout-web/issues/8565) 
As part of the [Localized Checkout Ui Extensions](https://docs.google.com/document/d/1Qg9AGnkSLGx10zetJIrLfzvt554_AKb7HykUK5y1_mA/edit#heading=h.62oius9y1lvr) project, we must update the `shopify-cli` codebase to allow developers to submit localization files along with their code updates when the Shopify CLI `shopify extension push` command is executed. 
This change applies to the Checkout Extension type of extensions only, for now.
<details>
<summary>Valid submission</summary>
This will be what is shown in the CLI when we will have merged in the code in the Shopify backend that will support this new localization feature.
</details>
<details>
<summary>Valid submission with unrecognized key warning</summary>
This …

[Feature] Add l10n support to CheckoutUiExtension

---

CHANGELOG.md
lib/shopify_cli/theme/syncer.rb
test/shopify-cli/theme/syncer_test.rb

These updates fix an issue where a local `package.json` file was being deleted despite being in the `.shopifyignore` file. 
In the Theme::Syncer `download_theme!` method, the files are actually `ShopifyCLI::Theme::File` objects that are getting passed to the IgnoreFilter, so the `match?` method is being called on a string representation of the File object rather than the actual `path` of the File object that should be compared. Because of that the package.json file was not matched and therefore not ignored.
This PR:
- updates `download_file!` method to use similar "ignore" handling as the `enqueue` method... using `ignore?` method added in #1892
- extracts `ignore_path?` method from `ignore?` method so it can be called separately from an `operation` argument
- updates `ignore_path?` to …

Fix Theme::Syncer `download_file!` handling of file deletions

---

lib/shopify_cli/messages/messages.rb
test/shopify-cli/tasks/ensure_dev_store_test.rb

Fixes https://github.com/Shopify/shopify-cli/issues/1149
Fixes https://github.com/Shopify/shopify-cli-planning/issues/49
Improve the error message shown when trying to serve an application without a development store.
1. Login with a partner account with no development stores
2. Run `shopify app serve`
3. It should show `Couldn't verify your store. If you don't have a development store set up, please create one in your Partners dashboard and run "shopify app connect".`

Improve app serve error message without dev stores

---

lib/project_types/script/cli.rb
lib/project_types/script/commands/push.rb
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator.rb
lib/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner.rb
lib/project_types/script/layers/infrastructure/languages/tool_version_checker.rb
lib/project_types/script/layers/infrastructure/languages/typescript_project_creator.rb
lib/project_types/script/layers/infrastructure/languages/typescript_task_runner.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
lib/shopify_cli/environment.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/assemblyscript_task_runner_test.rb
test/project_types/script/layers/infrastructure/languages/tool_version_checker_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_task_runner_test.rb
test/project_types/script/ui/error_handler_test.rb
test/shopify-cli/environment_test.rb

Fixes https://github.com/Shopify/script-service/issues/2202
Adds a new module which infra-layer classes can use to ensure the system tools have an appropriate version.
create / push an assembly/typescript script project.
Tweak the various `MIN_{TOOL}_VERSION` in that language's project_creator and task_runner to observe the different behaviours.

Perform node version checks with ToolVersionChecker module

---

CHANGELOG.md
lib/project_types/script/config/extension_points.yml

Follow up to https://github.com/Shopify/shopify-cli/pull/2061
Fixes https://github.com/Shopify/script-service/issues/4320
Removes the beta flag on the wasm language.
Do `shopify script create` with the `scripts_beta_languages` flag disabled.

Release Wasm Scripts Projects

---

CHANGELOG.md
bin/shopify

Followup to #2019
The previous PR didn't have a properly reviewed error message. This brings the message in line with our voice.
Not an easy way to test it properly without deliberately installing the wrong Nokogiri. I generated the preview image above by changing `require` to pretend it failed to load nokogiri and raise a LoadError.

Improve Nokogiri LoadError message

---

CHANGELOG.md
lib/project_types/theme/commands/serve.rb
lib/project_types/theme/messages/messages.rb
test/project_types/theme/commands/serve_test.rb

Currently, `theme pull`/`push` accept a `[ ROOT ]` argument as the first argument, but `theme serve` does not.
- This PR 
- updates `theme serve` to accept a root argument in the exact same way as `theme pull`/`push`.
- slight refactor to `serve_test.rb` to simplify testing, while adding test case for this update.
- have a dev theme setup and logged in
- `mkdir dist` inside your project folder
- `theme pull -d dist` to download the remote theme to the `dist` folder
- `theme serve dist` to serve the theme from the `dist` folder
- make a change to the theme (e.g. add random test class to body in `theme.liquid`) inside the `dist` folder and see the change served

[ feature ] Update `theme serve` to accept `root` argument

---

test/shopify-cli/theme/syncer_test.rb

The `ShopifyCLI::Theme::SyncerTest` class is intermittently failing in the CI (the unstable tests are `test_theme_files_are_pending_during_upload` and `test_logs_upload_error`).
This PR:
- Removes the `@syncer.start_threads` from the setup, so it's not called twice in some methods anymore (which avoids the intermittent issue in the `test_theme_files_are_pending_during_upload` test
- Improves the mocking mechanism of the `test_logs_upload_error`
- Run the following command in the `shopify-cli` repository directory:
```
for i in {1..5000}; do; echo $i; ruby -I test test/shopify-cli/theme/syncer_test.rb ; done;
```
- Notice that the `test_logs_upload_error` and `test_theme_files_are_pending_during_upload` tests no longer break intermittently
None.

Stabilize the `ShopifyCLI::Theme::SyncerTest` class

---

CHANGELOG.md
lib/project_types/theme/commands/pull.rb
test/project_types/theme/commands/pull_test.rb

fixes `NoMethodError: undefined method 'name'`
```
NoMethodError: undefined method `name' for nil:NilClass
/Users/johnroyall/shopify-cli-kilgore5/lib/project_types/theme/commands/pull.rb:78:in `find_theme'
```
The dev_theme object will be nil if the theme is not found, so this PR just passes `development` as a string to the error message instead of trying to access the non-existent theme
- delete dev theme
- run `SHOPIFY_CLI_STACKTRACE=1 shopify theme pull -d`
- see correct error message instead of NoMethodError

Fix `theme pull` error message when development theme doesn't exist

---

lib/project_types/extension/tasks/configure_features.rb
test/project_types/extension/tasks/configure_features_test.rb

Creating CLI extensions fails for Shopify Developers using Spin
Previously, extension surface areas that weren't properly configured would cause the CLI to error out. Now, the name of the extension gets updated with a warning that it is still under development. This will let Shopify developers working on new extensions know that further work is required while also not getting in the way when you create extension so a different type.
This issue should never occur in production. It surface because the extensions spin template activates beta flags for extensions that are still under development. One of these extensions still requires work in the CLI to be done to function properly. We now gracefully degrade if we know in advance that we can't proceed.
As this is concerning a feature that …

Gracefully handle unknow extension surface areas

---

CHANGELOG.md
lib/project_types/theme/commands/common/root_helper.rb
test/project_types/theme/commands/common/root_helper_test.rb

Users may successfully run `shopify-dev theme serve --live-reload off`. However, they face an error when they try to run `shopify-dev theme serve --live-reload=off`.
This PR slightly changes the `RootHelper` parse logic to support flags with an `equal` character between the option key and value.
- Go to a theme directory
- Run `shopify theme serve --live-reload=off`
- Notice the CLI no long raises an error
**Before this PR:**
**After this PR:**
None.

Fix `RootHelper` parse logic to support options with an equal (e.g.: `option=value`)

---

CHANGELOG.md
lib/project_types/theme/cli.rb
lib/project_types/theme/commands/list.rb
lib/project_types/theme/commands/open.rb
lib/project_types/theme/forms/select.rb
lib/project_types/theme/messages/messages.rb
lib/project_types/theme/presenters/theme_presenter.rb
lib/project_types/theme/presenters/themes_presenter.rb
test/project_types/theme/commands/list_test.rb
test/project_types/theme/commands/open_test.rb
test/project_types/theme/presenters/theme_presenter_test.rb
test/project_types/theme/presenters/themes_presenter_test.rb

Partners (#1867) need a command to list themes connected to their store and a command for opening the preview of a specific theme.
This PR introduces:
- the `theme list` command, which provides the list of themes connected to the current store; and
- the `theme open` command, which quickly provides a preview of the selected theme (this command accepts the following options: `-t, --theme=NAME_OR_ID`, `-l, --live`, and `-d, --development`).
From the code perspective, this PR introduces presenter classes to take care of the presenting logic. Thus, we've avoided duplication between `Theme::Forms::Select` and the new `Theme::Command::List`.
Also, this PR renames occurrences of the **Online Store Editor** term in favor of **Theme Editor**.
- Run `shopify theme list` and see the list of themes
- …

[Feature] Add new Theme CLI commands: `theme list` and `theme open`

---

lib/shopify_cli/commands/app/deploy.rb
lib/shopify_cli/core/monorail.rb
test/shopify-cli/core/monorail_test.rb

When we have more than two levels of arguments, for example `shopify app create rails`, there's a bug that causes only the first two arguments to be sent, `app create`. @jesalerno84 spotted this one while gathering data around how many apps are created with the different templates.
Fix the implementation by traversing the commands' hierarchy.
1. Comment out the line `executor.call(command, command_name, args)` in `entry_point.rb`
2. Add a log right below `full_command = self.full_command` in `monorail.rb` to print `full_command`.
3. Run `bin/shopify app create rails`.
4. `full_command` should represent the whole command.

Fix sending monorail events

---

lib/project_types/script/messages/messages.rb

Fixes https://github.com/Shopify/script-service/issues/4398
Simple text change to make it more clean and clear.
Easiest way is to:
- create a wasm project with `shopify script create`, 
- cd in, and 
- immediately attempt to `shopify script push`

improve error message when failing to find wasm binary

---

test/test_helper.rb

Fixes this runtime error when running Minitests in RubyMine:
```
$HOME/Library/Application Support/JetBrains/Toolbox/apps/RubyMine
/ch-0/213.6777.43/RubyMine.app/Contents/plugins/ruby/rb/testing/patch
/testunit/minitest/rm_reporter_plugin.rb:37:in 
`assert_no_minitest_reporters': (RuntimeError)
Current implementation of IntelliJ Minitest support conflicts with 
Minitest::Reporters. Please remove Minitest::Reporters.use! from your
test code or suppress the invocation if ENV['RM_INFO'] is defined, then
re-run your tests.
```
https://user-images.githubusercontent.com/4490738/157957963-ccd25080-1b84-4ddb-aea1-74a74d60dda4.mp4
See this issue: https://blog.jetbrains.com/ruby/2021/04/improved-minitest-support-action-required/
Run Minitests in Rubymine

Fix minitest RuntimeErrors in RubyMine

---

CHANGELOG.md
lib/shopify_cli/command.rb
lib/shopify_cli/messages/messages.rb
test/shopify-cli/commands/command_test.rb

We often see failed attempts to pass a store name. Sometimes they [mess up](https://app.bugsnag.com/shopify/shopify-cli/errors/615c602b14a5fc000787762e?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in][type]=gt&filters[release.seen_in][value]=2.7.3&event_id=61bf79e5008a8c9cb5d00000) [the name](https://app.bugsnag.com/shopify/shopify-cli/errors/615c602b14a5fc000787762e?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in][type]=gt&filters[release.seen_in][value]=2.7.3&event_id=61bf33b6008a9606f27c0000) of the param, other times they try to [pass it as a raw param](https://app.bugsnag.com/shopify/shopify-cli/errors/615c602b14a5fc000787762e?filters[event.since]=30d&filters[error.status]=open&event_id=61c20ac6008a8b0460f20000).
This attempts …

Recognize attempts to pass a store name and suggest correction

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

We now validate the input query in script-service. When the query is
invalid, a user error tagged `input_query_validation_error` is
returned. With this commit, we'll display this error as such:
```
Couldn't push script to app. Input query is invalid:
✗ Field 'doesntexit' doesn't exist on type 'PurchaseProposal' at 'query.purchaseProposal.doesntexit'.
Fix the query in the `input.graphql` file.
```
See instructions in Shopify/script-service#4532
-  ~I've added a CHANGELOG entry for this PR (if the change is public-facing)~
This feature is still in stealth mode, so no changelog.
------
#gsd:23093

[Feature] Handle invalid input query error

---

CHANGELOG.md
lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb
lib/shopify_cli/messages/messages.rb
test/project_types/extension/models/specification_handlers/checkout_ui_extension_test.rb

Fixes [internal issue 1](https://github.com/Shopify/checkout-web/issues/8687), [internal issue 2](https://github.com/Shopify/checkout-web/issues/8688)
Localization files not properly encoded in UTF-8 (without `bom`) could cause unexpected errors in the CLI when using the `extension push` command.
- Raise an explicit error on non-UTF-8 encodings
- Silently strip the UTF-8 `bom` from localization data if present
- Have a local setup ready for Checkout Extension development
- In a checkout extension project, create a `locales` folder, and within that folder create the following files:
- `en.default.json`
- Add some content to the files so that you do not get an empty file error.
- First Scenario: To see the encoding error, encode the locale file with an encoding other than UTF-8, such as …

Improve encoding error handling for Checkout Extension localization

---

CHANGELOG.md
lib/shopify_cli/services/app/create/rails_service.rb
lib/shopify_cli/services/app/serve/rails_service.rb
packaging/homebrew/shopify-cli.base.rb
vendor/deps/cli-ui/lib/cli/ui/os.rb

For whatever reason, it seems that the wrong Rails is found if the versions of Rails in the homebrew-installed CLI vs. your app have gotten out of sync, at least in certain environments.
Part of the issue seems to be that the gem path isn't passed through, and instead ends up pointing to the homebrew-installed gem path, but that won't be the same as the gems you've `bundle install`ed in your Rails app, so your app thinks it's missing dependencies!
After debugging with @pepicrft and @isaacroldan, it seems that we need to pass through the original environment when running the `bin/rails` executable; something in there is necessary for gems to load properly. And anyway, it makes sense to keep the environment consistent with what the user actually has set.
I'm honestly not sure. Locally, I …

Fix app serve after rails update

---

CHANGELOG.md

I've noticed the https://github.com/Shopify/shopify-cli/pull/2174 was not included in the https://github.com/Shopify/shopify-cli/releases page.
Also, I've checked the tags, and I'm updating the https://github.com/Shopify/shopify-cli/releases page and the 'CHANGELOG.md' file accordingly.

Fix 'CHANGELOG.md'

---

lib/project_types/script/cli.rb
lib/project_types/script/layers/application/create_script.rb
lib/project_types/script/layers/infrastructure/languages/project_creator.rb
lib/project_types/script/layers/infrastructure/sparse_checkout_details.rb
test/project_types/script/layers/application/create_script_test.rb
test/project_types/script/layers/infrastructure/languages/project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/typescript_project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/wasm_project_creator_test.rb
test/project_types/script/layers/infrastructure/sparse_checkout_details_test.rb

https://github.com/Shopify/script-service/issues/4501
This PR introduces a feature flag, `scripts_beta_input_queries`. When disabled, we will filter out input-query related files when performing the sparse-checkout of the project template. When enabled we will not filter out input-query related files.
I will make PR(s) in [scripts-apis-examples](https://github.com/Shopify/scripts-apis-examples) to add the schema and empty input query files.
Create a script without enabling the feature, see that the `input.graphql` and `schema.graphql` files are not included in the project:
```
shopify-dev script create --api=merchandise_discount_types --branch=ap.discounts-wasm-schema
```
Enable the feature
```
shopify-dev config feature scripts_beta_input_queries --enable
```
Create a script, see that …

Hide input query related files behind beta flag

---

.vscode/settings.json

To help me stay sane! I need to manually reset the theme every time.
Deletes the hard coded VS Code colour scheme that overrides users' editor preferences. This is simply not inclusive. Some people require colour-blind friendly or high contrast themes. We should not dictate a user's colour scheme.
By updating the `.vscode/settings.json` file.
None. This only effects the development environment.

Remove VS Code Color Scheme Preference

---

CHANGELOG.md
lib/shopify_cli/context.rb
lib/shopify_cli/messages/messages.rb
lib/shopify_cli/services/app/create/rails_service.rb
lib/shopify_cli/services/app/serve/rails_service.rb
test/fixtures/app_types/node/.env
test/fixtures/app_types/rails/.env
test/shopify-cli/services/app/create/rails_service_test.rb
test/shopify-cli/services/app/serve/rails_service_test.rb

We recently released a new major version of the `shopify_app` gem, used by the rails app. In v19, we don't need the CLI to set up the user agent initializer, and we don't need to remove the `HOST` value from the env vars.
Adding a new check to get the version of a gem in a project, and using that to tell whether we need to take the above actions when setting up a rails app.
I'm not entirely sure the context is the best place for this check, but I think it's useful enough that it can be quite generic.
By 🎩 ing and via unit tests.

Fix issues with Rails apps after v19

---

lib/shopify_cli/changelog.rb
lib/shopify_cli/release.rb

Fixes some issues spotted in #2220 
I noticed 2 problems:
1. The build failed because the generated changelog when there are no Unreleased contents doesn't include an Unreleased section.
2. The release notes weren't present.
Fixes:
1. Force an Unreleased section to be created during changelog parsing
2. The release notes were missing because following [these changes](https://github.com/Shopify/shopify-cli/pull/2197/commits/0d345d5a924e2917331d37fd2de47411d42a84df) we are actually reloading the changelog in memory during version update. So we shouldn't pull the version changes from the Unreleased section, but rather from the newly created `new_version` section.
1. The tests should cover it (and are actually probably the only situation where this would actually break!)
2. I'm pretty …

Fix changelog parsing and reading

---

CHANGELOG.md
lib/shopify_cli/messages/messages.rb
lib/shopify_cli/tunnel.rb
test/fixtures/ngrok.log
test/fixtures/ngrok_account.log
test/shopify-cli/tunnel_test.rb

@Arkham realized we are recommending to create an ngrok account, but it's mandatory now (the tunnel won't work)
When there is no authentication, abort and show an error.
Before:
After:
Remove your ngrok token (`~/.ngrok2/ngrok.yml`) and run `shopify app serve`

Show an error without ngrok account

---

lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
test/project_types/extension/models/specification_handlers/theme_app_extension_test.rb

Fixes [346424](https://github.com/Shopify/shopify/issues/346424) which is a bug that includes locales directory in the liquid file size validation.
1. Adding a condition to only increment the total size for liquid files for blocks and snippets directory within a theme app extension
Push your theme app extension code and ensure that the locales file size is not counted towards the validation for the maximum of 100KB for liquid files.
1. Follow up with the partner to ensure that they are no longer having an issue with the `locales` directory being counted towards the maximum of 100KB for liquid files

[Theme App Extension] - Fix liquid file size validation to disclude locales directory

---

packaging/homebrew/shopify-cli.base.rb

Fixes #2227
Ensuring that we require the JSON library before first use.
I actually don't know how to exactly test this change without releasing a new version. I created an example script that looked as follows to make sure that the `-r` flag behaves as expected:
```ruby
#!/usr/bin/env ruby -rjson
puts({a: 1}.to_json)
```
Testing instructions:
```
git checkout fix/homebrew-wrapper
rake build
rake package
cd packaging/builds/2.15.4
brew uninstall shopify-cli
brew install --formula ./shopify-cli.rb
/opt/homebrew/bin/shopify version # => 2.15.4 (Haven't bumped the version yet)
```
The script excuted as expected and output some JSON. Removing `-rjson` breaks the script.

Fix Homebrew Wrapper

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2237](https://github.com/Shopify/shopify-cli/pull/2237): Fix Homebrew Wrapper

Packaging for release v2.15.5

---

CHANGELOG.md
lib/shopify_cli/services/app/serve/serve_service.rb
lib/shopify_cli/tasks/update_dashboard_urls.rb
test/shopify-cli/services/app/serve/node_service_test.rb
test/shopify-cli/services/app/serve/php_service_test.rb
test/shopify-cli/services/app/serve/rails_service_test.rb
test/shopify-cli/tasks/update_dashboard_urls_test.rb

Related to [#1367 ](https://github.com/Shopify/shopify_app/issues/1367), [#198 ](https://github.com/Shopify/first-party-library-planning/issues/198)
After we run `shopify app serve` and accessing the url generated by the CLI we receive error 400
- Added functionality to support both callback paths: `"/auth/shopify/callback"` and `"/auth/callback"`  
1. Go to App Setup  -> Edit 
2. Replace `Allowed redirection URL(s)` values with `https://google.com/`
3. From your local app directory start the server:
```ruby
shopify app serve
```
Accessing the generated url works as expected
_none_

Fix callback urls for app serve

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2246](https://github.com/Shopify/shopify-cli/pull/2246): Fix callback urls for app serve

Packaging for release v2.15.6

---

Gemfile.lock
Tests.dockerfile
shopify-cli.gemspec

Ran `bundle update --bundler` to bump to the latest bundler which fixed a bundler crash.
Fixes a crash when running `bin/shopify help` on a fresh git pull of the main branch.
```
[58918, #<Thread:0x000000010504cd28 run>, #<NameError: uninitialized constant Gem::Source
(defined?(@source) && @source) || Gem::Source::Installed.new
^^^^^^^^
```
Pulls [in this fix from ruby gems](https://github.com/rubygems/rubygems/pull/5386).
Setup before:
- Bundler 2.3.8 with Ruby 3.1.0 my M1 crashed running bin/shopify help
Setup after:
- Bundler 2.3.11 with Ruby 3.1.0 my M1 crashed running bin/shopify help
Run `bundle` in the repo after checking out this branch.

[Bug] Fix a bundler crash when running `bin/shopify help`

---

lib/project_types/script/config/extension_points.yml
lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/languages/project_creator.rb
lib/project_types/script/layers/infrastructure/languages/task_runner.rb
test/project_types/script/layers/infrastructure/languages/project_creator_test.rb
test/project_types/script/layers/infrastructure/languages/task_runner_test.rb

I want to be able to use the CLI to create scripts from templates that don't yet have full support, like Rust, Zig, Go, etc.
The CLI currently has a lot of language specific code that makes that slow. As a result I'd have to make the script manually, then start using the tool again.
Pending the results of [this discussion](https://github.com/Shopify/script-service/discussions/4647), we might not have any language based code in the CLI long term anyway.
In cases that we do have a template for a language in scripts-apis-examples, but don't have CLI specific support, we just no-op on all the operations that would set up that language for your machine.
After this is merged, we'll be able to use Rust payment method scripts in the CLI.
Try making a rust script:
```
shopify-dev script create …
```

allow unknown languages

---

lib/project_types/extension/cli.rb
lib/project_types/extension/commands/create.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/npm_package.rb
lib/project_types/extension/tasks/execute_commands/base.rb
lib/project_types/extension/tasks/execute_commands/build.rb
lib/project_types/extension/tasks/execute_commands/outdated_extension_detection.rb
lib/project_types/extension/tasks/execute_commands/serve.rb
test/project_types/extension/commands/build_test.rb
test/project_types/extension/tasks/execute_commands/build_test.rb
test/project_types/extension/tasks/execute_commands/create_test.rb
test/project_types/extension/tasks/execute_commands/outdated_extension_detection_test.rb
test/project_types/extension/tasks/execute_commands/serve_test.rb

To prevent the CLI from crashing when running `shopify extensions build|serve` with the new extensions server without migrating the extension. Instead of crashing, the CLI will now emit an error message with detailed instructions.
- ShopifyCLI::Result#unwrap!
- OutdatedExtensionCheck

Detect outdated extensions

---

lib/shopify_cli/admin_api.rb
lib/shopify_cli/constants.rb
lib/shopify_cli/environment.rb
test/shopify-cli/admin_api_test.rb
test/shopify-cli/environment_test.rb

We need a way to execute some commands (that need Admin API access) without any interaction.
With this PR we introduce two new Environment variables that allow us to set a **store** and a **token** (with access to that store).
If provided, a command like `theme pull` will ignore any cached session/store and use the ones from the environment.
- Add `SHOPIFY_CLI_ADMIN_AUTH_TOKEN` to inject a custom admin token and avoid the auth process.
- Add `SHOPIFY_CLI_STORE` so all Admin requests use this store, the user must have access to this store.
Execute this command to get the list of themes of the given store.
`SHOPIFY_CLI_ADMIN_AUTH_TOKEN={your_token} SHOPIFY_CLI_STORE={store-name}.myshopify.com bundle exec shopify theme pull`
The provided {your_token} must grant access to {store-name}.

Add 2 new env vars: Admin token & store

---

CHANGELOG.md
lib/project_types/extension/models/development_server_requirements.rb
lib/project_types/extension/models/server_config/development_renderer.rb
lib/project_types/extension/tasks/configure_features.rb
test/project_types/extension/models/development_server_requirements_test.rb
test/project_types/extension/models/server_config/development_renderer_test.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2195
As we are developing `retail-ui-extension` for POS, we want 3P developers to install our package within Shopify CLI. `POS UI Extension` option needs to show up when the 3P developer runs command `shopify extension create`.
Added a new extension point and also surface area to render. Surface area does not need `git template` as we added the extension template into `shopify-cli-extension` (PR : https://github.com/Shopify/shopify-cli-extensions/pull/286)
Tested against development build. Here is the video: https://videobin.shopify.io/v/P0XEke
Steps:
1. Created a `extensions` spin environment which will automatically run all dependent process in a single spin environment.
2. Switched partner repo to `pos-ui-extensions` from `master`. …

[Feature]: Adding POS UI Extension configuration into Shopify CLI

---

CHANGELOG.md
lib/graphql/find_organization_with_apps.graphql
lib/project_types/extension/tasks/get_apps.rb
lib/project_types/extension/tasks/get_extensions.rb
lib/project_types/script/layers/application/connect_app.rb
lib/shopify_cli/partners_api/app_extensions.rb
lib/shopify_cli/partners_api/organizations.rb
lib/shopify_cli/tasks/ensure_env.rb
test/project_types/extension/extension_test_helpers/stubs/get_organizations.rb
test/project_types/extension/forms/questions/ask_app_test.rb
test/project_types/extension/tasks/get_apps_test.rb
test/project_types/extension/tasks/get_extensions_test.rb
test/project_types/script/layers/application/connect_app_test.rb
test/shopify-cli/partners_api/app_extensions_test.rb
test/shopify-cli/partners_api/organizations_test.rb
test/shopify-cli/tasks/ensure_env_test.rb

Fixes: https://github.com/Shopify/shopify-cli-planning/issues/90
When we show you apps to potentially connect your extension to via any of the `extension create / register / connect` commands, we show you all the apps that you have access to across all your partner accounts, not only the apps that are in your currently logged in partner account.
That behavior's a bit odd from an auth / permissions angle and we should fix that.
Related:
https://github.com/Shopify/shopify-cli/issues/1839 for `extension create`
https://github.com/Shopify/shopify-cli/issues/1899 for `extension connect`
https://github.com/Shopify/shopify-cli/issues/2234
- Updated `Task::GetApps.call` to return a list of apps for logged in organization
- Created new method `ShopifyCLI::PartnersAPI::Organizations.fetch_with_app` …

[Feature]: Changed interactive apps list scope for extension create|register|connect commands

---

CHANGELOG.md
lib/shopify_cli/partners_api/app_extensions.rb
lib/shopify_cli/services/app/create/rails_service.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2234
There's an issue with the thread pool management, causing the `extension connect` command to not load all the existing extensions sometimes.
- Limit the pool size to 1 thread to ensure we get all the extensions. This is a temporary solution until we fix the threads management. So it will get all the extensions sequentially now, slower but safer.
- Pin `shopify_app` gem to v19, to avoid problems if there are breaking changes in the future (unrelated change).
- Run `shopify extension connect` several times, having a few extensions on different apps

Fix extension loading for extension connect

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2279](https://github.com/Shopify/shopify-cli/pull/2279): Fix logout when there are theme permission issues
* [#2285](https://github.com/Shopify/shopify-cli/pull/2285): Fix extension loading for extension connect
* [#2284](https://github.com/Shopify/shopify-cli/pull/2284): Fix version check for Windows

Packaging for release v2.16.1

---

CHANGELOG.md
lib/project_types/extension/cli.rb
lib/project_types/extension/models/server_config/capabilities.rb
lib/project_types/extension/models/server_config/extension.rb
lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb
lib/project_types/extension/tasks/convert_server_config.rb
test/project_types/extension/models/specification_handlers/checkout_ui_extension_test.rb
test/project_types/extension/tasks/convert_server_config_test.rb

Resolves internal Shopify issue, should be paired with: https://github.com/Shopify/shopify-cli-extensions/pull/288.
Thanks to @ecbrodie for pairing!
Adds support for a `capabilities` dictionary within an extension's `extension.config.yml`, this dict will expand but for now includes only the `network_access` with a boolean flag.
All changes in this PR are only relevant to Checkout Extensions and hence if the [Extensions Dev Server](https://github.com/Shopify/shopify-cli-extensions) is being used via enabling the `extension_server_beta` feature.
No other `shopify` commands should be affected by this change. There should also be no changes to the legacy checkout extensions endpoint, `/query`.
<details>
<summary>Manual testing instructions</summary>
When running the below steps, make sure …

[Feature] Add `capabilities` permissions to checkout extensions config

---

CHANGELOG.md
lib/shopify_cli/context.rb
test/shopify-cli/context_test.rb

We are checking if there's a new update available once a day, but I've found a situation where it says this:
`⭑ A new version of Shopify CLI is available! You have version 2.16.1 and the latest version is 2.16.0.`
Related to https://github.com/Shopify/shopify-cli/pull/2189
This happened because:
- The CLI checked the latest version: 2.16.0 (and caches it for 24h)
- The CLI was updated to 2.16.1
- It detects that the version is different, so it supposes there's a new one
Only show update message when the new version is higher
1. Enable [these lines](https://github.com/Shopify/shopify-cli/blob/cb0df573adb1aa9c07347d9401dfd2d974e12a60/lib/shopify_cli/core/entry_point.rb#L13-L14) in your dev environment (need to play with the `if/elsif` or just copy the lines to after the conditional)
2. …

Only show update message when the new version is higher

---

lib/project_types/script/layers/infrastructure/errors.rb
lib/project_types/script/layers/infrastructure/script_service.rb
lib/project_types/script/messages/messages.rb
lib/project_types/script/ui/error_handler.rb
test/project_types/script/layers/infrastructure/script_service_test.rb
test/project_types/script/ui/error_handler_test.rb

Fixes https://github.com/Shopify/script-service/issues/4785
This PR introduces code to specifically handle the invalid App Bridge path responses from the backend.
Use [this](https://github.com/Shopify/script-service/pull/4836) backend branch and attempt to push an invalid path (e.g. it doesn't start with a leading `/`). You will see an error like the following:

Handle invalid App Bridge paths when pushing a script

---

lib/project_types/extension/models/server_config/development_renderer.rb

https://github.com/Shopify/ce-customer-behaviour/issues/984
The cli was unable to create the beacon_extension because of defensive code preventing the creation of an extension without a renderer
to allow for the creation of beacon extensions without having to specify a renderer
fixes bug that prevented the generation of the beacon extension project
`shopify extension create`
select beacon_extension
select javascript
provide name

explicitly set renderer for beacon extension to nil

---

lib/shopify_cli/core/monorail.rb

Monorail-edge.shopifycloud.com is backed by a single region (us-east), whereas monorail-edge.shopifysvc.com balances traffic between two regions (us-east and us-central) providing a highly available endpoint for monorail producers. Clients of monorail-edge.shopifycloud.com could experience outages and data loss if the us-east cluster went down. The monorail team intends to sunset the monorail-edge.shopifycloud.com domain in the next few weeks.

Switch to monorail-edge.shopifysvc.com endpoint

---

lib/project_types/script/config/extension_points.yml

This allows us to do `shopify script create --language=rust` and select `payment_customization` and `shipping_methods`
We have default rust scripts for them here https://github.com/Shopify/scripts-apis-examples/tree/master/checkout/rust

Allow shipping_methods and payment_customizations to pull rust script examples

---

lib/project_types/script/layers/infrastructure/script_project_repository.rb
lib/project_types/script/messages/messages.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb

https://github.com/Shopify/script-service/issues/4712
This PR requires that App Bridge paths are present when pushing a script. It also populates default App Bridge paths when creating a script.
- Create a new script and see that the App Bridge paths are present
- Push a script with App Bridge paths and see they are sent
- Push a script without App Bridge paths and see there is an error

Require App Bridge paths + populate them on script create

---

lib/shopify_cli/git.rb
test/shopify-cli/git_test.rb

This support is needed in order to use `cli_two` branches in app templates repositories for backwards compatibility.
If a `#branch_name` is added to the repository url passed into `ShopifyCLI::Git.clone`, the url will be split into `repo` and `branch` and that `branch` will be cloned instead of the default.
Unit test added to confirm functionality.
n/a

Adds support for git branches to git clone

---

lib/shopify_cli/services/app/create/node_service.rb
test/shopify-cli/services/app/create/node_service_test.rb

In preparation to launch new Node app template, the Node app repo used by `shopify app create node` is being renamed from `shopify-app-node` to `shopify-app-template-node`.
Closes Shopify/first-party-library-planning#212
Prerequisites before merging:
- repo rename to occur
- https://github.com/Shopify/shopify-cli/pull/2376 to be merged
☝🏻 See above!

Changes `shopify-app-node` to `shopify-app-template-node`

---

lib/shopify_cli/services/app/create/php_service.rb
test/shopify-cli/services/app/create/php_service_test.rb

In preparation to launch new PHP app template, the repo name is being changed from `shopify-app-php` to `shopify-app-template-php`
Prerequisites before merging:
- repo rename to occur
- https://github.com/Shopify/shopify-cli/pull/2376 to be merged
Closes https://github.com/Shopify/first-party-library-planning/issues/306
☝🏻 See above!

Changes php app repo to shopify-app-template-php

---

lib/project_types/extension/models/development_server_requirements.rb
test/project_types/extension/models/development_server_requirements_test.rb

This addresses part of https://github.com/Shopify/checkout-web/issues/11018
The [shopify-cli-extensions](https://github.com/Shopify/shopify-cli-extensions) server will not be enabled by default. A developer would have to explicitly enable the beta flag after this PR.
Why? The public beta of Checkout UI Extensions will use [CLI 3.0](https://github.com/Shopify/shopify-cli-next/).
I just used the unit tests

Honor dev server beta flag without special casing checkout_ui_extensions

---

CHANGELOG.md

* [#2368](https://github.com/Shopify/shopify-cli/pull/2368): Add performance enhancements to the `theme serve` and `theme push` commands
* [#2437](https://github.com/Shopify/shopify-cli/pull/2437): Add support to the `warnings` field in the assets API
* [#2446](https://github.com/Shopify/shopify-cli/pull/2446): Show a friendly message when developers use a browser without SSE support
* [#2418](https://github.com/Shopify/shopify-cli/pull/2418): Improve the help message of the `theme open -e/--editor` flag
* [#2444](https://github.com/Shopify/shopify-cli/pull/2444): Expose the `-s` option in the help text of `login`, `switch` etc.

Packaging for release v2.19.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2458](https://github.com/Shopify/shopify-cli/pull/2458): Fix shop URL in unauthorized error message
* [#2459](https://github.com/Shopify/shopify-cli/pull/2459): Fix `.json` file ignore issues with `shopify theme push`
* [#2460](https://github.com/Shopify/shopify-cli/pull/2460): Fix job retries for .json theme file dependencies and support wider range of asset API errors

Packaging for release v2.20.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify_cli/version.rb

* [#2453](https://github.com/Shopify/shopify-cli/pull/2453): Fix [#2382](https://github.com/Shopify/shopify-cli/issues/2382): Ensure we wait 24 hours to show update message again
* [#2463](https://github.com/Shopify/shopify-cli/pull/2463): Fix for "Keep the remote version" deletes files on new development theme
* [#2405](https://github.com/Shopify/shopify-cli/pull/2405): Fix `theme serve` to trigger page refresh when a file is deleted
* [#2489](https://github.com/Shopify/shopify-cli/pull/2489): Fix `theme serve` to hot reload many occurrences of a stylesheet
* [#2496](https://github.com/Shopify/shopify-cli/pull/2496): Accept storefront renderer token from ENV variable

Packaging for release v2.21.0

---

.github/workflows/shopify.yml

I've removed `macos-10.15` follow [this page](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) and [this issue](https://github.com/Shopify/shopify-cli/issues/2474).
Also, I've considered adding `macos-12`, however `macos-11` still is the latest stable image.

Remove `macos-10.15` from `workflows/shopify.yml`

---

CHANGELOG.md
lib/shopify_cli/core.rb
lib/shopify_cli/core/cli_version.rb
lib/shopify_cli/core/entry_point.rb
lib/shopify_cli/messages/messages.rb
lib/shopify_cli/project.rb
lib/shopify_cli/utilities.rb
test/shopify-cli/core/cli_version_test.rb
test/shopify-cli/utilities_test.rb

Closes https://github.com/Shopify/shopify-cli-planning/issues/278
Warns when using CLI 2.0 but you're inside a 3.0 project. Because you probably meant to use 3.0.
Currently just warns, but we might consider this a full-blown error condition.
Run any CLI command inside a 3.0 project

Warn when using CLI 2.0 in a CLI 3.0 project

---

lib/project_types/script/config/extension_points.yml
test/project_types/script/commands/push_test.rb
test/project_types/script/layers/infrastructure/script_project_repository_test.rb
test/project_types/script/ui/error_handler_test.rb

Part of https://github.com/Shopify/script-service/issues/5431
Unsure if we still need to update this repo, but opening this to be thorough because the [function-examples have been deleted](https://github.com/Shopify/function-examples/pull/100)
- Remove `payment_methods`
- Remove `shipping_methods` typescript

[Functions] Remove payment_methods and TS extension points

---

lib/project_types/extension/commands/serve.rb
lib/project_types/extension/messages/messages.rb
lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
test/project_types/extension/commands/serve_test.rb
test/project_types/extension/models/specification_handlers/theme_app_extension_test.rb

Fixes https://github.com/Shopify/shopify-cli/issues/2533 https://github.com/Shopify/shopify-cli/issues/2534
This PR adds support for the `--port`/`-T/--theme` flags. Notice that we needed to use the capitalized `-T` to disambiguate with the `-t` of the `--[no-]tunnel`
Still, I don't think that's a problem, because this command with be exposed at the [shopify/cli](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/commands/app/dev.ts#L55-L59) and fortunately the [`tunnel-url` doesn't have a `char:`](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/commands/app/dev.ts#L55-L59) property there.
- Run `shopify-dev extension serve --theme <THEME_ID_OR_NAME> --port <PORT>`

Add support for `--port`/`-T/--theme` flags

---

lib/project_types/extension/tasks/fetch_specifications.rb

This reverts commit 7df988d8d1a8bf003ba6d468904cb2b532c30d3e (as now we're relying on the SFR in production).

Revert "Add a temporary extension mock (#2485)"
